### ISSUE TITLE
[BUG] Zygote failed to start Webview sandboxed

### ISSUE THREAD

**Issue by MSkjel** [ElderDrivers/EdXposed#152]
When not having com.android.webview blacklisted sometimes the app using webview will crash.

Stacktrace from logcat:

ActivityManager: Failure starting process com.android.webview:sandboxed_process0
java.lang.RuntimeException: Starting VM process through Zygote failed
at android.os.ZygoteProcess.start(ZygoteProcess.java:239)
at android.os.Process.startWebView(Process.java:507)
at com.android.server.am.ActivityManagerService.startProcess(ActivityManagerService.java:4562)
at com.android.server.am.ActivityManagerService.lambda$startProcessLocked$0(ActivityManagerService.java:4516)
at com.android.server.am.-$$Lambda$ActivityManagerService$UgpguyCBuObHjnmry_xkrJGkFi0.run(Unknown Source:20)
at android.os.Handler.handleCallback(Handler.java:873)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:193)
at android.os.HandlerThread.run(HandlerThread.java:65)
at com.android.server.ServiceThread.run(ServiceThread.java:44)
Caused by: android.os.ZygoteStartFailedEx: Error connecting to primary zygote
at android.os.ZygoteProcess.openZygoteSocketIfNeeded(ZygoteProcess.java:570)
at android.os.ZygoteProcess.startViaZygote(ZygoteProcess.java:438)
at android.os.ZygoteProcess.start(ZygoteProcess.java:232)
... 9 more
Caused by: java.io.IOException: Connection refused
at android.net.LocalSocketImpl.connectLocal(Native Method)
at android.net.LocalSocketImpl.connect(LocalSocketImpl.java:292)
at android.net.LocalSocket.connect(LocalSocket.java:145)
at android.os.ZygoteProcess$ZygoteState.connect(ZygoteProcess.java:112)
at android.os.ZygoteProcess.openZygoteSocketIfNeeded(ZygoteProcess.java:568)
... 11 more
ActivityManager: Force stopping no.viafree.android appid=99017 user=0: start failure
ActivityManager: Killing 16814:no.viafree.android/u0a152 (adj 199): stop no.viafree.android

**Comment by solohsu** [comment]
Try v0.3.1.2

**Comment by danielehrhardt** [comment]
Same Issue here if i open Google Chrome
