### ISSUE TITLE
[BUG] 开机后卡死在锁屏界面 然后重启

### ISSUE THREAD

**Issue by coderstory** [ElderDrivers/EdXposed#154]
开机后卡死在锁屏界面 然后重启进入twrp
edxposed 3.0.0 beta2 
riru v16
小米9 android P（二月的安全补丁）

只安装框架不安装任何插件的话 能正常开机

其中一个错误如下
`
2019-03-11 19:38:12.799 6645-6645/? A/libc: Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 6645 (main), pid 6645 (main)
2019-03-11 19:38:12.891 7374-7374/? A/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
2019-03-11 19:38:12.891 7374-7374/? A/DEBUG: Build fingerprint: 'Xiaomi/cepheus/cepheus:9/PKQ1.181121.001/9.3.11:user/release-keys'
2019-03-11 19:38:12.891 7374-7374/? A/DEBUG: Revision: '0'
2019-03-11 19:38:12.891 7374-7374/? A/DEBUG: ABI: 'arm64'
2019-03-11 19:38:12.891 7374-7374/? A/DEBUG: pid: 6645, tid: 6645, name: main  >>> zygote64 <<<
2019-03-11 19:38:12.891 7374-7374/? A/DEBUG: signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
2019-03-11 19:38:12.891 7374-7374/? A/DEBUG: Abort message: 'jni_internal.cc:616] JNI FatalError called: (.dataservices) Not whitelisted : /data/data/com.coderstory.Purify/shared_prefs/UserSettings.xml'
2019-03-11 19:38:12.891 7374-7374/? A/DEBUG:     x0  0000000000000000  x1  00000000000019f5  x2  0000000000000006  x3  0000000000000008
2019-03-11 19:38:12.891 7374-7374/? A/DEBUG:     x4  0000000000000000  x5  0000000000000000  x6  0000000000000000  x7  0080808080808080
2019-03-11 19:38:12.891 7374-7374/? A/DEBUG:     x8  0000000000000083  x9  40b032c0619a0f1f  x10 0000000000000000  x11 fffffffc7ffffbdf
2019-03-11 19:38:12.891 7374-7374/? A/DEBUG:     x12 0000000000000001  x13 000000000000000b  x14 ffffffffffffffff  x15 00006f43aee9f45f
2019-03-11 19:38:12.891 7374-7374/? A/DEBUG:     x16 00000079038172b8  x17 0000007903736ee0  x18 0000000000000010  x19 00000000000019f5
2019-03-11 19:38:12.891 7374-7374/? A/DEBUG:     x20 00000000000019f5  x21 000000787e323770  x22 000000787ded415f  x23 000000787dece433
2019-03-11 19:38:12.891 7374-7374/? A/DEBUG:     x24 000000787dece2e7  x25 0000000000000001  x26 0000000000000000  x27 00000000000003e8
2019-03-11 19:38:12.891 7374-7374/? A/DEBUG:     x28 000000787e323750  x29 0000007ff5068c00
2019-03-11 19:38:12.891 7374-7374/? A/DEBUG:     sp  0000007ff5068bc0  lr  000000790372a354  pc  000000790372a37c
2019-03-11 19:38:13.064 7374-7374/? A/DEBUG: backtrace:
2019-03-11 19:38:13.064 7374-7374/? A/DEBUG:     #00 pc 000000000002237c  /system/lib64/libc.so (abort+116)
2019-03-11 19:38:13.064 7374-7374/? A/DEBUG:     #01 pc 0000000000465618  /system/lib64/libart.so (offset 0x375000) (art::Runtime::Abort(char const*)+1196)
2019-03-11 19:38:13.064 7374-7374/? A/DEBUG:     #02 pc 0000000000008ce0  /system/lib64/libbase.so (android::base::LogMessage::~LogMessage()+724)
2019-03-11 19:38:13.064 7374-7374/? A/DEBUG:     #03 pc 000000000032dfe0  /system/lib64/libart.so (offset 0x220000) (art::JNI::FatalError(_JNIEnv*, char const*)+196)
2019-03-11 19:38:13.064 7374-7374/? A/DEBUG:     #04 pc 000000000019f4f0  /system/lib64/libandroid_runtime.so (_ZZN12_GLOBAL__N_123ForkAndSpecializeCommonEP7_JNIEnvjjP10_jintArrayiP13_jobjectArraylliP8_jstringS7_bS3_S3_bS7_S7_ENK3$_0clERKNSt3__112basic_stringIcNS9_11char_traitsIcEENS9_9allocatorIcEEEE+164)
2019-03-11 19:38:13.064 7374-7374/? A/DEBUG:     #05 pc 000000000019f088  /system/lib64/libandroid_runtime.so ((anonymous namespace)::ForkAndSpecializeCommon(_JNIEnv*, unsigned int, unsigned int, _jintArray*, int, _jobjectArray*, long, long, int, _jstring*, _jstring*, bool, _jintArray*, _jintArray*, bool, _jstring*, _jstring*)+5568)
2019-03-11 19:38:13.064 7374-7374/? A/DEBUG:     #06 pc 000000000019d190  /system/lib64/libandroid_runtime.so (android::com_android_internal_os_Zygote_nativeForkAndSpecialize(_JNIEnv*, _jclass*, int, int, _jintArray*, int, _jobjectArray*, int, _jstring*, _jstring*, _jintArray*, _jintArray*, unsigned char, _jstring*, _jstring*)+588)
2019-03-11 19:38:13.064 7374-7374/? A/DEBUG:     #07 pc 000000000000fe08  /system/lib64/libmemtrack.so
2019-03-11 19:38:13.064 7374-7374/? A/DEBUG:     #08 pc 00000000024502d0  /system/framework/arm64/boot-framework.oat (offset 0xa29000) (com.android.internal.os.Zygote.nativeForkAndSpecialize+416)
2019-03-11 19:38:13.064 7374-7374/? A/DEBUG:     #09 pc 000000000244ff24  /system/framework/arm64/boot-framework.oat (offset 0xa29000) (com.android.internal.os.Zygote.forkAndSpecialize+228)
2019-03-11 19:38:13.064 7374-7374/? A/DEBUG:     #10 pc 000000000245413c  /system/framework/arm64/boot-framework.oat (offset 0xa29000) (com.android.internal.os.ZygoteConnection.processOneCommand+1580)
2019-03-11 19:38:13.064 7374-7374/? A/DEBUG:     #11 pc 000000000245c3c0  /system/framework/arm64/boot-framework.oat (offset 0xa29000) (com.android.internal.os.ZygoteServer.runSelectLoop+928)
2019-03-11 19:38:13.064 7374-7374/? A/DEBUG:     #12 pc 0000000002456334  /system/framework/arm64/boot-framework.oat (offset 0xa29000) (com.android.internal.os.ZygoteInit.main+1972)
2019-03-11 19:38:13.064 7374-7374/? A/DEBUG:     #13 pc 000000000055764c  /system/lib64/libart.so (offset 0x375000) (art_quick_invoke_static_stub+604)
2019-03-11 19:38:13.064 7374-7374/? A/DEBUG:     #14 pc 00000000000cfce8  /system/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+232)
2019-03-11 19:38:13.064 7374-7374/? A/DEBUG:     #15 pc 000000000045dd10  /system/lib64/libart.so (offset 0x375000) (art::(anonymous namespace)::InvokeWithArgArray(art::ScopedObjectAccessAlreadyRunnable const&, art::ArtMethod*, art::(anonymous namespace)::ArgArray*, art::JValue*, char const*)+104)
2019-03-11 19:38:13.064 7374-7374/? A/DEBUG:     #16 pc 000000000045d970  /system/lib64/libart.so (offset 0x375000) (art::InvokeWithVarArgs(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jmethodID*, std::__va_list)+424)
2019-03-11 19:38:13.064 7374-7374/? A/DEBUG:     #17 pc 0000000000362cd4  /system/lib64/libart.so (offset 0x220000) (art::JNI::CallStaticVoidMethodV(_JNIEnv*, _jclass*, _jmethodID*, std::__va_list)+652)
2019-03-11 19:38:13.064 7374-7374/? A/DEBUG:     #18 pc 00000000000b2644  /system/lib64/libandroid_runtime.so (_JNIEnv::CallStaticVoidMethod(_jclass*, _jmethodID*, ...)+116)
2019-03-11 19:38:13.064 7374-7374/? A/DEBUG:     #19 pc 00000000000b51e0  /system/lib64/libandroid_runtime.so (android::AndroidRuntime::start(char const*, android::Vector<android::String8> const&, bool)+924)
2019-03-11 19:38:13.064 7374-7374/? A/DEBUG:     #20 pc 0000000000002528  /system/bin/app_process64 (main+2012)
2019-03-11 19:38:13.064 7374-7374/? A/DEBUG:     #21 pc 00000000000c888c  /system/lib64/libc.so (__libc_init+88)
`

这个出错的xml是xp插件内的配置文件，我记得chmod 755处理了

以及以下其他的art错误
`
2019-03-11 19:38:01.504 5350-5427/? E/SensorService: Reported power 0.000000 not deemed sane, clamping to 0.001000
2019-03-11 19:38:01.505 5431-5431/? E/sensors-hal: unregister_direct_channel:323, unregister_direct_channel : unable to find channel handle -1
2019-03-11 19:38:01.543 5350-5376/? E/PinnerService: Could not pin file /data/dalvik-cache/arm64/system@framework@boot.oat
    android.system.ErrnoException: open failed: ELOOP (Too many symbolic links encountered)
        at libcore.io.Linux.open(Native Method)
        at libcore.io.BlockGuardOs.open(BlockGuardOs.java:210)
        at android.system.Os.open(Os.java:358)
        at com.android.server.PinnerService.pinFileRanges(PinnerService.java:478)
        at com.android.server.PinnerService.pinFile(PinnerService.java:358)
        at com.android.server.PinnerService.handlePinOnStart(PinnerService.java:163)
        at com.android.server.PinnerService.access$600(PinnerService.java:70)
        at com.android.server.PinnerService$PinnerHandler.handleMessage(PinnerService.java:657)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:201)
        at android.os.HandlerThread.run(HandlerThread.java:65)
2019-03-11 19:38:01.543 5350-5376/? E/PinnerService: Failed to pin file = /data/dalvik-cache/arm64/system@framework@boot.oat
2019-03-11 19:38:01.543 5350-5376/? E/PinnerService: Could not pin file /data/dalvik-cache/arm/system@framework@boot.oat
    android.system.ErrnoException: open failed: ELOOP (Too many symbolic links encountered)
        at libcore.io.Linux.open(Native Method)
        at libcore.io.BlockGuardOs.open(BlockGuardOs.java:210)
        at android.system.Os.open(Os.java:358)
        at com.android.server.PinnerService.pinFileRanges(PinnerService.java:478)
        at com.android.server.PinnerService.pinFile(PinnerService.java:358)
        at com.android.server.PinnerService.handlePinOnStart(PinnerService.java:163)
        at com.android.server.PinnerService.access$600(PinnerService.java:70)
        at com.android.server.PinnerService$PinnerHandler.handleMessage(PinnerService.java:657)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:201)
        at android.os.HandlerThread.run(HandlerThread.java:65)
2019-03-11 19:38:01.543 5350-5376/? E/PinnerService: Failed to pin file = /data/dalvik-cache/arm/system@framework@boot.oat
2019-03-11 19:38:01.543 5350-5376/? E/PinnerService: Could not pin file /data/dalvik-cache/arm64/system@framework@services.jar@classes.dex
    android.system.ErrnoException: open failed: ENOENT (No such file or directory)
        at libcore.io.Linux.open(Native Method)
        at libcore.io.BlockGuardOs.open(BlockGuardOs.java:210)
        at android.system.Os.open(Os.java:358)
        at com.android.server.PinnerService.pinFileRanges(PinnerService.java:478)
        at com.android.server.PinnerService.pinFile(PinnerService.java:358)
        at com.android.server.PinnerService.handlePinOnStart(PinnerService.java:163)
        at com.android.server.PinnerService.access$600(PinnerService.java:70)
        at com.android.server.PinnerService$PinnerHandler.handleMessage(PinnerService.java:657)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:201)
        at android.os.HandlerThread.run(HandlerThread.java:65)
2019-03-11 19:38:01.543 5350-5376/? E/PinnerService: Failed to pin file = /data/dalvik-cache/arm64/system@framework@services.jar@classes.dex
`

https://blog.coderstory.cn/wp-content/uploads/2019/03/新建文本文档.txt

**Comment by xiaomengxinyo** [comment]
我是应用卡死，进入后什么也点不了，关机键都不行，只能强行重启

**Comment by coderstory** [comment]
群里的刷了就ok了
