### ISSUE TITLE
[BUG] OnePlus bootloop

### ISSUE THREAD

**Issue by Fingalzzz** [ElderDrivers/EdXposed#156]
**什么情况/What happened?**

device: oneplus 6t, OOS 9.0.12 with NoLimits installed, android 9.  

bootloop while installed EdXposed v3.0.1.2_beta and v.3.0.0_beta2.

Success to boot while installed EdXposed v3.0.0_beta3_snapshot from https://github.com/ElderDrivers/EdXposed/issues/125#issuecomment-471152156

**Xposed模块列表/Xposed Module List**

Ampilify, Greenify, WeXposed, DisableFlagSecure

**Magisk模块列表/Magisk Module List**

logcat, mm, riru-core, riru-edxposed, riru-storage redirect, shizuku-boot, xXx NoLimits ROM

**EdXposed及Riru版本/Versions of EdXposed and Riru**

EdXposed: v0.3.1.2 beta

Riru: v16

**相关Logcat/Logcat**

有助于定位问题，必须使用我们的log抓取模块抓取/It can help us to locate issue, must use our logcat module
[bootloop-1970-01-20-22-38-51.log](https://github.com/ElderDrivers/EdXposed/files/2963191/bootloop-1970-01-20-22-38-51.log)

**Comment by tuyennn** [comment]
@Fingalzzz I'm using this on my Oneplus 6t without any issue: GravityBox[P], MaxLock. MinMinGuar, SMS Code Extractor

**Comment by mshinni80** [comment]
@Fingalzzz
Maybe try flashing the latest riru core (17.1)..I also encountered a bootloops with my OP5 (OOS 9.0.4) after I flashed the lasted EdXposed beta.. But when I flashed the beta again and right after riro core 17.1 it booted just fine..

**Comment by Fingalzzz** [comment]
Tried on riru core v17.1 with edxposed v0.3.1.2, still encounter bootloop

**Comment by solohsu** [comment]
Please disable all xposed modules and boot again to see if it's caused by any xposed module.
To disable all xposed modules, you can boot into recovery mode and delete `/data/user_de/0/com.solohsu.android.edxp.manager/conf/`.

**Comment by Fingalzzz** [comment]
Tried disable all the Xposed modules but still encounter bootloop.

On 15 Mar 2019 17:14, solohsu <notifications@github.com> wrote:

Please disable all xposed modules and boot again to see if it's caused by any xposed module.
To disable all xposed modules, you can boot into recovery mode and delete /data/user_de/0/com.solohsu.android.edxp.manager/conf/.

**Comment by solohsu** [comment]
logs plz.

**Comment by Fingalzzz** [comment]
The original log is attached in the first post, log below is the one with all xposed modules disabled. 
[bootloop-1970-01-22-23-19-39.log](https://github.com/ElderDrivers/EdXposed/files/2972640/bootloop-1970-01-22-23-19-39.log)

**Comment by solohsu** [comment]
@Fingalzzz I can confirm that the xXx NoLimits ROM module had overridden some system props set by EdXposed, at least prop `compiler-filter`.
You can disable the xXx NoLimits ROM module and see if EdXposed works.

**Comment by Fingalzzz** [comment]
@solohsu 
After disable xXx NoLimits ROM it success to boot. Is there any solution to fix this like EdXposed v3.0.0_beta3_snapshot from https://github.com/ElderDrivers/EdXposed/issues/125#issuecomment-471152156 did?

**Comment by solohsu** [comment]
> ## [UPDATE]
> After success to boot, I tried to re-enable xXx NoLimits ROM again with v3.0.1.2_beta it still be able to boot, cannot figure not why.
> @solohsu
> After disable xXx NoLimits ROM it success to boot. Is there any solution to fix this like EdXposed v3.0.0_beta3_snapshot from [#125 (comment)](https://github.com/ElderDrivers/EdXposed/issues/125#issuecomment-471152156) did?

Because EdXposed dexes has been compiled after you disabled xXx. If you clear dalvik-cache, and reboot I believe you would get into boot loops again.
Please try this build.
Enable both EdXposed and xXx, go to recovery mode, clear the dalvik-cache, and reboot.
[magisk-EdXposed-v0.3.1.5_beta-SNAPSHOT-release.zip](https://github.com/ElderDrivers/EdXposed/files/2973551/magisk-EdXposed-v0.3.1.5_beta-SNAPSHOT-release.zip)

**Comment by C3C0** [comment]
The same. Bootloop on Oreo 8.0 (OxygenOS).
```
03-16 08:14:36.496  1737  1876 E AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: android.ui
03-16 08:14:36.496  1737  1876 E AndroidRuntime: java.lang.IllegalAccessError: Illegal class access: 'ed_' attempting to access 'com.android.server.am.ProcessRecord' (declaration of 'ed_' appears in Anonymous-DexFile@0x7884f8b000-0x7884f8ba84)
03-16 08:14:36.496  1737  1876 E AndroidRuntime: 	at ed_.hook(Unknown Source:159)
03-16 08:14:36.496  1737  1876 E AndroidRuntime: 	at com.android.server.am.ActivityManagerService.broadcastIntentLocked(ActivityManagerService.java:21568)
03-16 08:14:36.496  1737  1876 E AndroidRuntime: 	at com.android.server.am.ActivityManagerService.broadcastIntent(ActivityManagerService.java:21710)
03-16 08:14:36.496  1737  1876 E AndroidRuntime: 	at android.app.ContextImpl.sendStickyBroadcastAsUser(ContextImpl.java:1305)
03-16 08:14:36.496  1737  1876 E AndroidRuntime: 	at com.android.server.policy.PhoneWindowManager.setHdmiPlugged(PhoneWindowManager.java:6445)
03-16 08:14:36.496  1737  1876 E AndroidRuntime: 	at com.android.server.policy.PhoneWindowManager.initializeHdmiState(PhoneWindowManager.java:6481)
03-16 08:14:36.496  1737  1876 E AndroidRuntime: 	at com.android.server.policy.PhoneWindowManager.init(PhoneWindowManager.java:2457)
03-16 08:14:36.496  1737  1876 E AndroidRuntime: 	at ed_.hook(Unknown Source:150)
03-16 08:14:36.496  1737  1876 E AndroidRuntime: 	at com.android.server.policy.OemPhoneWindowManager.init(OemPhoneWindowManager.java:423)
03-16 08:14:36.496  1737  1876 E AndroidRuntime: 	at com.android.server.wm.WindowManagerService$3.run(WindowManagerService.java:1100)
03-16 08:14:36.496  1737  1876 E AndroidRuntime: 	at android.os.Handler$BlockingRunnable.run(Handler.java:809)
03-16 08:14:36.496  1737  1876 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:789)
03-16 08:14:36.496  1737  1876 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:98)
03-16 08:14:36.496  1737  1876 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
03-16 08:14:36.496  1737  1876 E AndroidRuntime: 	at android.os.HandlerThread.run(HandlerThread.java:65)
03-16 08:14:36.496  1737  1876 E AndroidRuntime: 	at com.android.server.ServiceThread.run(ServiceThread.java:46)
03-16 08:14:36.496  1737  1876 E AndroidRuntime: 	at com.android.server.UiThread.run(UiThread.java:42)
03-16 08:14:36.500  1594  1594 E Typeface: Error mapping font file /system/fonts/NotoSansCJKsc-Thin.otf
03-16 08:14:36.501  1594  1594 E Typeface: Error mapping font file /system/fonts/NotoSansCJKsc-Light.otf
03-16 08:14:36.501  1594  1594 E Typeface: Error mapping font file /system/fonts/NotoSansCJKsc-Regular.otf
03-16 08:14:36.501  1594  1594 E Typeface: Error mapping font file /system/fonts/NotoSansCJKsc-Medium.otf
03-16 08:14:36.501   457   457 E SELinux : selinux_android_service_open_context_handle: Error getting service context handle (Permission denied)
03-16 08:14:36.502  1594  1594 E Typeface: Error mapping font file /system/fonts/NotoSansCJKsc-Bold.otf
03-16 08:14:36.502   457   457 I SELinux : avc:  received policyload notice (seqno=6)
03-16 08:14:36.502  1594  1594 E Typeface: Error mapping font file /system/fonts/NotoSansCJKsc-Black.otf
03-16 08:14:36.503  1737  1737 D SDService-JNI: DisplayColor init  is succesfull
03-16 08:14:36.504  1594  1594 E Typeface: Error mapping font file /system/fonts/RobotoCondensed-Thin.ttf
03-16 08:14:36.506  1737  1988 I SystemServer: StartHidlServices
03-16 08:14:36.506  1737  1737 I SystemServer: StartVrManagerService
03-16 08:14:36.506  1737  1737 I SystemServiceManager: Starting com.android.server.vr.VrManagerService
03-16 08:14:36.510   456   456 W /system/bin/hwservicemanager: getTransportFromManifest: Cannot find entry android.hardware.vr@1.0::IVr in either framework or device manifest, using default transport.
03-16 08:14:36.512  1737  1884 E hw-IPCThreadState: binder thread pool (5 threads) starved for 2569 ms
03-16 08:14:36.513  1737  1737 W VrManagerService: init_native: Could not open IVr interface
03-16 08:14:36.516  1088  1152 E slim_daemon: [NDK] bindNDKSensors: Found Sensor Name: LSM6DS3 Accelerometer Vendor: STMicroelectronics Type: android.sensor.accelerometer (1) Min Delay: 5000 us handle: 1
03-16 08:14:36.516  1088  1152 E slim_daemon: [NDK] bindNDKSensors: Found Sensor Name: LSM6DS3 Gyroscope Uncalibrated Vendor: STMicroelectronics Type: android.sensor.gyroscope_uncalibrated (16) Min Delay: 5000 us handle: 6
03-16 08:14:36.516  1088  1152 E slim_daemon: [NDK] bindNDKSensors: Found Sensor Name: MMC3416PJ Magnetometer Vendor: MEMSIC Type: android.sensor.magnetic_field (2) Min Delay: 19230 us handle: 3
03-16 08:14:36.516  1088  1152 E slim_daemon: [NDK] bindNDKSensors: Found Sensor Name: MMC3416PJ Magnetometer Uncalibrated Vendor: MEMSIC Type: android.sensor.magnetic_field_uncalibrated (14) Min Delay: 19230 us handle: 4
03-16 08:14:36.517  1737  1737 I SystemServer: SetWindowManagerService
03-16 08:14:36.523  1737  1737 I SystemServer: StartInputManager
03-16 08:14:36.523  1737  1737 I InputManager: Starting input manager
03-16 08:14:36.528   959   959 W installd: Ignoring /data/user_de/0/com.android.bluetooth/lib with unexpected GID 0 instead of 1002
03-16 08:14:36.539  1737  1737 I SystemServer: DisplayManagerWindowManagerAndInputReady
03-16 08:14:36.539  1737  1737 I SystemServer: StartBluetoothService
03-16 08:14:36.539  1737  1737 I SystemServiceManager: Starting com.android.server.BluetoothService
03-16 08:14:36.552  1737  2006 D EventHub: No input device configuration file found for device 'msm8996-tasha-mtp-snd-card Button Jack'.
03-16 08:14:36.558  1737  2006 W EventHub: Unable to disable kernel key repeat for /dev/input/event7: Function not implemented
03-16 08:14:36.558  1737  2006 I EventHub: New device: id=1, fd=124, path='/dev/input/event7', name='msm8996-tasha-mtp-snd-card Button Jack', classes=0x1, configuration='', keyLayout='/system/usr/keylayout/Generic.kl', keyCharacterMap='/system/usr/keychars/Generic.kcm', builtinKeyboard=false, wakeMechanism=EPOLLWAKEUP, usingClockIoctl=true
03-16 08:14:36.558  1737  2006 D EventHub: No input device configuration file found for device 'msm8996-tasha-mtp-snd-card Headset Jack'.
03-16 08:14:36.558  1737  2006 I EventHub: New device: id=2, fd=127, path='/dev/input/event6', name='msm8996-tasha-mtp-snd-card Headset Jack', classes=0x80, configuration='', keyLayout='', keyCharacterMap='', builtinKeyboard=false, wakeMechanism=EPOLLWAKEUP, usingClockIoctl=true
03-16 08:14:36.559  1737  1737 D BluetoothManagerService: Loading stored name and address
03-16 08:14:36.559  1737  1737 D BluetoothManagerService: Stored bluetooth Name=OnePlus 3T,Address=C0:EE:FB:E2:DA:85
03-16 08:14:36.559  1737  1737 D BluetoothManagerService: Bluetooth persisted state: 0
03-16 08:14:36.560  1737  1737 I SystemServer: IpConnectivityMetrics
03-16 08:14:36.560  1737  1737 I SystemServiceManager: Starting com.android.server.connectivity.IpConnectivityMetrics
03-16 08:14:36.560  1737  2006 W EventHub: Unable to disable kernel key repeat for /dev/input/event2: Function not implemented
03-16 08:14:36.560  1737  2006 I EventHub: New device: id=3, fd=128, path='/dev/input/event2', name='fpc1020', classes=0x1, configuration='/system/usr/idc/fpc1020.idc', keyLayout='/system/usr/keylayout/fpc1020.kl', keyCharacterMap='/system/usr/keychars/Generic.kcm', builtinKeyboard=false, wakeMechanism=EPOLLWAKEUP, usingClockIoctl=true
03-16 08:14:36.561  1737  2006 E EventHub: could not get driver version for /dev/input/mouse0, Not a typewriter
03-16 08:14:36.562  1737  1737 I SystemServer: PinnerService
03-16 08:14:36.562  1737  1737 I SystemServiceManager: Starting com.android.server.PinnerService
03-16 08:14:36.563  1737  1737 I SystemServer: LongScreenShot Manager
03-16 08:14:36.565  1737  1737 I SystemServer: StartInputMethodManagerLifecycle
03-16 08:14:36.565  1737  1737 I SystemServiceManager: Starting com.android.server.InputMethodManagerService$Lifecycle
03-16 08:14:36.578  1737  1737 I SystemServer: StartAccessibilityManagerService
03-16 08:14:36.585  1737  1737 I SystemServer: MakeDisplayReady
03-16 08:14:36.589  1737  1737 I ActivityManager: Config changes=5df8 {1.0 0 ?mcc?mnc [en_US] ldltr sw411dp w411dp h731dp 420dpi nrml long port ?uimode ?night -touch -keyb/v/h -nav/h appBounds=Rect(0, 0 - 1080, 1920) s.2mThemeChanged = 0}
03-16 08:14:36.623  1737  1737 W SystemServer: ***********************************************
03-16 08:14:36.623  1737  1737 E SystemServer: BOOT FAILURE making display ready
03-16 08:14:36.623  1737  1737 E SystemServer: java.lang.IllegalAccessError: Illegal class access: 'ed_' attempting to access 'com.android.server.am.ProcessRecord' (declaration of 'ed_' appears in Anonymous-DexFile@0x7884f8b000-0x7884f8ba84)
03-16 08:14:36.623  1737  1737 E SystemServer: 	at ed_.hook(Unknown Source:159)
03-16 08:14:36.623  1737  1737 E SystemServer: 	at com.android.server.am.ActivityManagerService.broadcastIntentLocked(ActivityManagerService.java:21568)
03-16 08:14:36.623  1737  1737 E SystemServer: 	at com.android.server.am.ActivityManagerService.updateGlobalConfiguration(ActivityManagerService.java:22386)
03-16 08:14:36.623  1737  1737 E SystemServer: 	at com.android.server.am.ActivityManagerService.updateConfigurationLocked(ActivityManagerService.java:22267)
03-16 08:14:36.623  1737  1737 E SystemServer: 	at com.android.server.am.ActivityManagerService.updateConfiguration(ActivityManagerService.java:22206)
03-16 08:14:36.623  1737  1737 E SystemServer: 	at com.android.server.wm.WindowManagerService.displayReady(WindowManagerService.java:5011)
03-16 08:14:36.623  1737  1737 E SystemServer: 	at com.android.server.SystemServer.startOtherServices(SystemServer.java:965)
03-16 08:14:36.623  1737  1737 E SystemServer: 	at com.android.server.SystemServer.run(SystemServer.java:412)
03-16 08:14:36.623  1737  1737 E SystemServer: 	at com.android.server.SystemServer.main(SystemServer.java:276)
03-16 08:14:36.623  1737  1737 E SystemServer: 	at java.lang.reflect.Method.invoke(Native Method)
03-16 08:14:36.623  1737  1737 E SystemServer: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
03-16 08:14:36.623  1737  1737 E SystemServer: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
03-16 08:14:36.624  1737  1737 I SystemServer: StartStorageManagerService
03-16 08:14:36.624  1737  1737 I SystemServiceManager: Starting com.android.server.StorageManagerService$Lifecycle
03-16 08:14:36.631  1737  1737 I SystemServer: StartStorageStatsService
03-16 08:14:36.632  1737  1737 I SystemServiceManager: Starting com.android.server.usage.StorageStatsService$Lifecycle
03-16 08:14:36.633  1737  2008 D StorageManagerService: Thinking about init, mSystemReady=false, mDaemonConnected=true
03-16 08:14:36.633  1737  2008 D StorageManagerService: Thinking about reset, mSystemReady=false, mDaemonConnected=true
03-16 08:14:36.633  1737  2008 D StorageManagerService: Thinking about init, mSystemReady=false, mDaemonConnected=true
03-16 08:14:36.633  1737  2008 D StorageManagerService: Thinking about reset, mSystemReady=false, mDaemonConnected=true
03-16 08:14:36.633  1737  2008 D CryptdConnector: SND -> {1 cryptfs getfield SystemLocale}
03-16 08:14:36.643  1737  2010 D CryptdConnector: RCV <- {113 1 en-US}
03-16 08:14:36.644  1737  2010 D CryptdConnector: RCV <- {200 1 0}
03-16 08:14:36.645  1737  2008 D StorageManagerService: Got locale en-US from mount service
03-16 08:14:36.646  1737  2008 I ActivityManager: Config changes=100 {1.0 0 ?mcc?mnc [en_US] ldltr sw411dp w411dp h731dp 420dpi nrml long port ?uimode ?night -touch -keyb/v/h -nav/h appBounds=Rect(0, 0 - 1080, 1920) s.3mThemeChanged = 0}
03-16 08:14:36.662  1737  1737 I SystemServer: StartUiModeManager
03-16 08:14:36.663  1737  1737 I SystemServiceManager: Starting com.android.server.UiModeManagerService
03-16 08:14:36.665  1594  1594 E ActivityRecognitionHardware: activity_recognition HAL is deprecated. class_init is effectively a no-op
03-16 08:14:36.672  1737  1989 I ActivityManager: Config changes=200 {1.0 0 ?mcc?mnc [en_US] ldltr sw411dp w411dp h731dp 420dpi nrml long port night -touch -keyb/v/h -nav/h appBounds=Rect(0, 0 - 1080, 1920) s.4mThemeChanged = 0}
03-16 08:14:36.673  1737  2008 E Process : Killed system process
```

**Comment by solohsu** [comment]
@Fingalzzz @tuyennn @C3C0 lol. Sorry for the inconvenience. Fixed with 20fce38004d8ae774de968d8bf7f8d172b49967a.
[magisk-EdXposed-v0.3.1.5_beta-SNAPSHOT-release.zip](https://github.com/ElderDrivers/EdXposed/files/2973610/magisk-EdXposed-v0.3.1.5_beta-SNAPSHOT-release.zip)

**Comment by C3C0** [comment]
Boots ok with that one. Thanks.

**Comment by Fingalzzz** [comment]
Works perfectly fine for me.
