### ISSUE TITLE
最新版使用哔哩布丁闪退

### ISSUE THREAD

**Issue by ShmilyChen** [ElderDrivers/EdXposed#185]
哔哩哔哩 5.37
edxp 3.1.7
布丁1.5.6

闪退日志
java.lang.NoClassDefFoundError: tv.danmaku.bili.ui.theme.a
	at tv.danmaku.bili.ui.theme.b.a(BL:31)
	at b.dyt.k(BL:504)
	at b.dyt.c(BL:120)
	at com.bilibili.lib.ui.a.onCreate(BL:43)
	at tv.danmaku.bili.MainActivityV2.onCreate(BL:110)
	at android.app.Activity.performCreate(Activity.java:7224)
	at android.app.Activity.performCreate(Activity.java:7213)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1272)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2926)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3081)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1831)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:201)
	at android.app.ActivityThread.main(ActivityThread.java:6806)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
Caused by: java.lang.ExceptionInInitializerError
	at java.lang.Class.classForName(Native Method)
	at java.lang.Class.forName(Class.java:453)
	at com.elderdrivers.riru.xposed.dexmaker.MethodInfo.getClassForSure(MethodInfo.java:61)
	at de.robv.android.xposed.XposedBridge.hookMethod(XposedBridge.java:202)
	at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:187)
	at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:260)
	at com.zzz.pudding.b.c.j.a(EditTheme.java:96)
	at com.zzz.pudding.BiliHook$4.beforeHookedMethod(BiliHook.java:75)
	at de.robv.android.xposed.XC_MethodHook.callBeforeHookedMethod(XC_MethodHook.java:51)
	at EdHooker_.hook(Unknown Source:94)
	at android.app.Instrumentation.newApplication(Instrumentation.java:1122)
	at android.app.LoadedApk.makeApplication(LoadedApk.java:1065)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5916)
	at com.elderdrivers.riru.xposed.entry.hooker.HandleBindAppHooker.hook(HandleBindAppHooker.java:85)
	at android.app.ActivityThread.access$1200(ActivityThread.java:200)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1673)
	... 6 more
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources android.app.Application.getResources()' on a null object reference
	at tv.danmaku.bili.ui.theme.a.<clinit>(BL:67)
	... 22 more

**Comment by solohsu** [comment]
可能需要模块作者来修复，具体原因的话可以参考下面这个链接里的说明。
https://github.com/ElderDrivers/EdXposed/issues/77#issuecomment-470576541
