### ISSUE TITLE
[Question]请问，是否还不支持ssl抓包模块 just trust me

### ISSUE THREAD

**Issue by chenchengyuan** [ElderDrivers/EdXposed#190]
**什么情况/What happened?**

模块无效

**Xposed模块列表/Xposed Module List**

https://github.com/Fuzion24/JustTrustMe

**Magisk模块列表/Magisk Module List**

**EdXposed及Riru版本/Versions of EdXposed and Riru**

EdXposed:2.2.4

Riru:0.3.1.7

**相关Logcat/Logcat**

```
--------- beginning of head
EdXposed Log
Powered by Log Catcher
QQ chat group 855219808
--------- beginning of system info
Android version: 9
Android sdk: 28
Android build: PKQ1.180729.001
Fingerprint: Xiaomi/dipper/dipper:9/PKQ1.180729.001/V10.2.2.0.PEACNXM:user/release-keys
ROM build description: dipper-user 9 PKQ1.180729.001 V10.2.2.0.PEACNXM release-keys
EdXposed Version: 0.3.1.7_beta (3170)
Architecture: arm64-v8a
Device: dipper
Manufacture: Xiaomi
Brand: Xiaomi
Product: dipper
--------- beginning of main
--------- beginning of system
03-25 16:20:44.245   679   679 I EdXposed-Bridge: Loading modules from /data/app/just.trust.me-m7u7Ul3rQLM6QKbdd9ZZZQ==/base.apk
03-25 16:20:44.251   679   679 I EdXposed-Bridge:   Loading class just.trust.me.Main
03-25 16:20:44.449  1408  1408 E EdXposed-Bridge: java.lang.NoClassDefFoundError: Failed resolution of: Lorg/apache/http/impl/client/DefaultHttpClient;
03-25 16:20:44.449  1408  1408 E EdXposed-Bridge: 	at just.trust.me.Main.handleLoadPackage(Main.java:67)
03-25 16:20:44.449  1408  1408 E EdXposed-Bridge: 	at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(IXposedHookLoadPackage.java:34)
03-25 16:20:44.449  1408  1408 E EdXposed-Bridge: 	at de.robv.android.xposed.callbacks.XC_LoadPackage.call(XC_LoadPackage.java:61)
03-25 16:20:44.449  1408  1408 E EdXposed-Bridge: 	at de.robv.android.xposed.callbacks.XCallback.callAll(XCallback.java:117)
03-25 16:20:44.449  1408  1408 E EdXposed-Bridge: 	at com.elderdrivers.riru.xposed.entry.hooker.StartBootstrapServicesHooker.hook(StartBootstrapServicesHooker.java:43)
03-25 16:20:44.449  1408  1408 E EdXposed-Bridge: 	at com.android.server.SystemServer.run(SystemServer.java:444)
03-25 16:20:44.449  1408  1408 E EdXposed-Bridge: 	at com.android.server.SystemServer.main(SystemServer.java:309)
03-25 16:20:44.449  1408  1408 E EdXposed-Bridge: 	at java.lang.reflect.Method.invoke(Native Method)
03-25 16:20:44.449  1408  1408 E EdXposed-Bridge: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
03-25 16:20:44.449  1408  1408 E EdXposed-Bridge: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:853)
03-25 16:20:44.449  1408  1408 E EdXposed-Bridge: Caused by: java.lang.ClassNotFoundException: Didn't find class "org.apache.http.impl.client.DefaultHttpClient" on path: DexPathList[[zip file "/data/app/just.trust.me-m7u7Ul3rQLM6QKbdd9ZZZQ==/base.apk"],nativeLibraryDirectories=[/system/lib64, /vendor/lib64]]
03-25 16:20:44.449  1408  1408 E EdXposed-Bridge: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:171)
03-25 16:20:44.449  1408  1408 E EdXposed-Bridge: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
03-25 16:20:44.449  1408  1408 E EdXposed-Bridge: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
03-25 16:20:44.449  1408  1408 E EdXposed-Bridge: 	... 10 more
03-25 16:20:45.666  1408  1408 E EdXposed-Bridge: java.lang.NoClassDefFoundError: Failed resolution of: Lorg/apache/http/impl/client/DefaultHttpClient;
03-25 16:20:45.666  1408  1408 E EdXposed-Bridge: 	at just.trust.me.Main.handleLoadPackage(Main.java:67)
03-25 16:20:45.666  1408  1408 E EdXposed-Bridge: 	at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(IXposedHookLoadPackage.java:34)
03-25 16:20:45.666  1408  1408 E EdXposed-Bridge: 	at de.robv.android.xposed.callbacks.XC_LoadPackage.call(XC_LoadPackage.java:61)
03-25 16:20:45.666  1408  1408 E EdXposed-Bridge: 	at de.robv.android.xposed.callbacks.XCallback.callAll(XCallback.java:117)
03-25 16:20:45.666  1408  1408 E EdXposed-Bridge: 	at com.elderdrivers.riru.xposed.entry.hooker.LoadedApkConstructorHooker.hook(LoadedApkConstructorHooker.java:88)
03-25 16:20:45.666  1408  1408 E EdXposed-Bridge: 	at android.app.ActivityThread.getPackageInfo(ActivityThread.java:2102)
03-25 16:20:45.666  1408  1408 E EdXposed-Bridge: 	at android.app.ActivityThread.getPackageInfo(ActivityThread.java:2057)
03-25 16:20:45.666  1408  1408 E EdXposed-Bridge: 	at android.app.ActivityThread.getPackageInfo(ActivityThread.java:2029)
03-25 16:20:45.666  1408  1408 E EdXposed-Bridge: 	at android.app.ContextImpl.createPackageContextAsUser(ContextImpl.java:2112)
03-25 16:20:45.666  1408  1408 E EdXposed-Bridge: 	at android.app.ContextImpl.createPackageContext(ContextImpl.java:2099)
03-25 16:20:45.666  1408  1408 E EdXposed-Bridge: 	at android.content.ContextWrapper.createPackageContext(ContextWrapper.java:862)
03-25 16:20:45.666  1408  1408 E EdXposed-Bridge: 	at android.app.ActivityThread.installProvider(ActivityThread.java:6487)
03-25 16:20:45.666  1408  1408 E EdXposed-Bridge: 	at android.app.ActivityThread.installContentProviders(ActivityThread.java:6021)
03-25 16:20:45.666  1408  1408 E EdXposed-Bridge: 	at android.app.ActivityThread.installSystemProviders(ActivityThread.java:6715)
03-25 16:20:45.666  1408  1408 E EdXposed-Bridge: 	at com.android.server.am.ActivityManagerService.installSystemProviders(ActivityManagerService.java:13311)
03-25 16:20:45.666  1408  1408 E EdXposed-Bridge: 	at com.android.server.SystemServer.startOtherServices(SystemServer.java:856)
03-25 16:20:45.666  1408  1408 E EdXposed-Bridge: 	at com.android.server.SystemServer.run(SystemServer.java:446)
03-25 16:20:45.666  1408  1408 E EdXposed-Bridge: 	at com.android.server.SystemServer.main(SystemServer.java:309)
03-25 16:20:45.666  1408  1408 E EdXposed-Bridge: 	at java.lang.reflect.Method.invoke(Native Method)
03-25 16:20:45.666  1408  1408 E EdXposed-Bridge: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
03-25 16:20:45.666  1408  1408 E EdXposed-Bridge: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:853)
03-25 16:20:45.666  1408  1408 E EdXposed-Bridge: Caused by: java.lang.ClassNotFoundException: Didn't find class "org.apache.http.impl.client.DefaultHttpClient" on path: DexPathList[[zip file "/data/app/just.trust.me-m7u7Ul3rQLM6QKbdd9ZZZQ==/base.apk"],nativeLibraryDirectories=[/system/lib64, /vendor/lib64]]
03-25 16:20:45.666  1408  1408 E EdXposed-Bridge: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:171)
03-25 16:20:45.666  1408  1408 E EdXposed-Bridge: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
03-25 16:20:45.666  1408  1408 E EdXposed-Bridge: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
03-25 16:20:45.666  1408  1408 E EdXposed-Bridge: 	... 21 more
03-25 16:20:46.679   680   680 I EdXposed-Bridge: Loading modules from /data/app/just.trust.me-m7u7Ul3rQLM6QKbdd9ZZZQ==/base.apk
03-25 16:20:46.684   680   680 I EdXposed-Bridge:   Loading class just.trust.me.Main
03-25 16:20:46.730  1865  1865 E EdXposed-Bridge: java.lang.NoClassDefFoundError: Failed resolution of: Lorg/apache/http/impl/client/DefaultHttpClient;
03-25 16:20:46.730  1865  1865 E EdXposed-Bridge: 	at just.trust.me.Main.handleLoadPackage(Main.java:67)
03-25 16:20:46.730  1865  1865 E EdXposed-Bridge: 	at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(IXposedHookLoadPackage.java:34)
03-25 16:20:46.730  1865  1865 E EdXposed-Bridge: 	at de.robv.android.xposed.callbacks.XC_LoadPackage.call(XC_LoadPackage.java:61)
03-25 16:20:46.730  1865  1865 E EdXposed-Bridge: 	at de.robv.android.xposed.callbacks.XCallback.callAll(XCallback.java:117)
03-25 16:20:46.730  1865  1865 E EdXposed-Bridge: 	at com.elderdrivers.riru.xposed.entry.hooker.HandleBindAppHooker.hook(HandleBindAppHooker.java:74)
03-25 16:20:46.730  1865  1865 E EdXposed-Bridge: 	at android.app.ActivityThread.access$1200(ActivityThread.java:200)
03-25 16:20:46.730  1865  1865 E EdXposed-Bridge: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1673)
03-25 16:20:46.730  1865  1865 E EdXposed-Bridge: 	at android.os.Handler.dispatchMessage(Handler.java:106)
03-25 16:20:46.730  1865  1865 E EdXposed-Bridge: 	at android.os.Looper.loop(Looper.java:201)
03-25 16:20:46.730  1865  1865 E EdXposed-Bridge: 	at android.app.ActivityThread.main(ActivityThread.java:6806)
03-25 16:20:46.730  1865  1865 E EdXposed-Bridge: 	at java.lang.reflect.Method.invoke(Native Method)
03-25 16:20:46.730  1865  1865 E EdXposed-Bridge: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
03-25 16:20:46.730  1865  1865 E EdXposed-Bridge: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
03-25 16:20:46.730  1865  1865 E EdXposed-Bridge: Caused by: java.lang.ClassNotFoundException: Didn't find class "org.apache.http.impl.client.DefaultHttpClient" on path: DexPathList[[zip file "/data/app/just.trust.me-m7u7Ul3rQLM6QKbdd9ZZZQ==/base.apk"],nativeLibraryDirectories=[/system/lib64, /vendor/lib64]]
03-25 16:20:46.730  1865  1865 E EdXposed-Bridge: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:171)
03-25 16:20:46.730  1865  1865 E EdXposed-Bridge: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
03-25 16:20:46.730  1865  1865 E EdXposed-Bridge: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
03-25 16:20:46.730  1865  1865 E EdXposed-Bridge: 	... 13 more
03-25 16:20:46.738  1876  1876 E EdXposed-Bridge: java.lang.NoClassDefFoundError: Failed resolution of: Lorg/apache/http/impl/client/DefaultHttpClient;
03-25 16:20:46.738  1876  1876 E EdXposed-Bridge: 	at just.trust.me.Main.handleLoadPackage(Main.java:67)
03-25 16:20:46.738  1876  1876 E EdXposed-Bridge: 	at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(IXposedHookLoadPackage.java:34)
03-25 16:20:46.738  1876  1876 E EdXposed-Bridge: 	at de.robv.android.xposed.callbacks.XC_LoadPackage.call(XC_LoadPackage.java:61)
03-25 16:20:46.738  1876  1876 E EdXposed-Bridge: 	at de.robv.android.xposed.callbacks.XCallback.callAll(XCallback.java:117)
03-25 16:20:46.738  1876  1876 E EdXposed-Bridge: 	at com.elderdrivers.riru.xposed.entry.hooker.HandleBindAppHooker.hook(HandleBindAppHooker.java:74)
03-25 16:20:46.738  1876  1876 E EdXposed-Bridge: 	at android.app.ActivityThread.access$1200(ActivityThread.java:200)
03-25 16:20:46.738  1876  1876 E EdXposed-Bridge: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1673)
03-25 16:20:46.738  1876  1876 E EdXposed-Bridge: 	at android.os.Handler.dispatchMessage(Handler.java:106)
03-25 16:20:46.738  1876  1876 E EdXposed-Bridge: 	at android.os.Looper.loop(Looper.java:201)
03-25 16:20:46.738  1876  1876 E EdXposed-Bridge: 	at android.app.ActivityThread.main(ActivityThread.java:6806)
03-25 16:20:46.738  1876  1876 E EdXposed-Bridge: 	at java.lang.reflect.Method.invoke(Native Method)
03-25 16:20:46.738  1876  1876 E EdXposed-Bridge: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
03-25 16:20:46.738  1876  1876 E EdXposed-Bridge: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
03-25 16:20:46.738  1876  1876 E EdXposed-Bridge: Caused by: java.lang.ClassNotFoundException: Didn't find class "org.apache.http.impl.client.DefaultHttpClient" on path: DexPathList[[zip file "/data/app/just.trust.me-m7u7Ul3rQLM6QKbdd9ZZZQ==/base.apk"],nativeLibraryDirectories=[/system/lib64, /vendor/lib64]]
03-25 16:20:46.738  1876  1876 E EdXposed-Bridge: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:171)
03-25 16:20:46.738  1876  1876 E EdXposed-Bridge: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
03-25 16:20:46.738  1876  1876 E EdXposed-Bridge: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
03-25 16:20:46.738  1876  1876 E EdXposed-Bridge: 	... 13 more
```

**Comment by solohsu** [comment]
看起来不像是框架的问题。

**Comment by chenchengyuan** [comment]
我也不知道什么情况，之前在VirtualXposed上用这个模块是可以的

**Comment by cnbjx** [comment]
为什么不换一种思路，把用户证书提升为系统证书，只需要ROOT权限，啥问题都解决了而且还没有各种BUG。 

1、安装证书，如 fiddler 
2、把  /data/misc/user/0/cacerts-added/ 下的证书移动到 /system/etc/security/cacerts/ 目录
3、删除 /data/misc/user/0/cacerts-added/ 下的证书 
4、重启手机

**Comment by lubocheng** [comment]
我也遇到了同样的情况,手机型号是:Mi9 se...
话说..这个bug都2个月了...没有大神跟进解决吗..

**Comment by KieronQuinn** [comment]
This can be solved by editing the module:
Clone JustTrustMe (the release APK is ancient anyway)
Update the gradle files and target SDK as necessary to get it to compile
Add the following as a dependency:
`implementation 'org.apache.httpcomponents:httpclient:4.5.6'`
And the following packagingOptions:
```
packagingOptions {
        exclude 'META-INF/DEPENDENCIES'
        exclude 'META-INF/LICENSE'
        exclude 'META-INF/LICENSE.txt'
        exclude 'META-INF/license.txt'
        exclude 'META-INF/NOTICE'
        exclude 'META-INF/NOTICE.txt'
        exclude 'META-INF/notice.txt'
        exclude 'META-INF/ASL2.0'
}
```
Build and install

The module will now work.

**Comment by lubocheng** [comment]
why close without any suggestion or solution?

**Comment by KieronQuinn** [comment]
Because there is a solution, it's one post above your comment 🙄

**Comment by Seumi** [comment]
> This can be solved by editing the module:
> Clone JustTrustMe (the release APK is ancient anyway)
> Update the gradle files and target SDK as necessary to get it to compile
> Add the following as a dependency:
> `implementation 'org.apache.httpcomponents:httpclient:4.5.6'`
> And the following packagingOptions:
> 
> ```
> packagingOptions {
>         exclude 'META-INF/DEPENDENCIES'
>         exclude 'META-INF/LICENSE'
>         exclude 'META-INF/LICENSE.txt'
>         exclude 'META-INF/license.txt'
>         exclude 'META-INF/NOTICE'
>         exclude 'META-INF/NOTICE.txt'
>         exclude 'META-INF/notice.txt'
>         exclude 'META-INF/ASL2.0'
> }
> ```
> 
> Build and install
> 
> The module will now work.

Does it still work for you now？ I build the moudle follow the way，but it still not work（Android 9 Edxposed90）

**Comment by Seumi** [comment]
> 我也遇到了同样的情况,手机型号是:Mi9 se...
> 话说..这个bug都2个月了...没有大神跟进解决吗..

你有解决方案了吗

**Comment by MlgmXyysd** [comment]
This module too old, pls use Move Cert. Magisk module

**Comment by KieronQuinn** [comment]
> This module too old, pls use Move Cert. Magisk module

Move Cert, to my knowledge anyway, does not disable cert pinning. Only an Xposed module or smali modding of an app can do that

**Comment by MlgmXyysd** [comment]
> > This module too old, pls use Move Cert. Magisk module
> 
> Move Cert, to my knowledge anyway, does not disable cert pinning. Only an Xposed module or smali modding of an app can do that

you can try this solution

> This can be solved by editing the module:
> Clone JustTrustMe (the release APK is ancient anyway)
> Update the gradle files and target SDK as necessary to get it to compile
> Add the following as a dependency:
> `implementation 'org.apache.httpcomponents:httpclient:4.5.6'`
> And the following packagingOptions:
> 
> ```
> packagingOptions {
>         exclude 'META-INF/DEPENDENCIES'
>         exclude 'META-INF/LICENSE'
>         exclude 'META-INF/LICENSE.txt'
>         exclude 'META-INF/license.txt'
>         exclude 'META-INF/NOTICE'
>         exclude 'META-INF/NOTICE.txt'
>         exclude 'META-INF/notice.txt'
>         exclude 'META-INF/ASL2.0'
> }
> ```
> 
> Build and install
> 
> The module will now work.

**Comment by MlgmXyysd** [comment]
> > This module too old, pls use Move Cert. Magisk module
> 
> Move Cert, to my knowledge anyway, does not disable cert pinning. Only an Xposed module or smali modding of an app can do that

well, this module is too old to be missing a lot

**Comment by chenchengyuan** [comment]
Use this module, https://github.com/ViRb3/TrustMeAlready
