### ISSUE TITLE
[BUG] 后台崩溃日志，使用了SettingsCompat库。

### ISSUE THREAD

**Issue by captain-miao** [ElderDrivers/EdXposed#219]
**什么情况/What happened?**

后台崩溃日志，使用了[SettingsCompat](https://github.com/czy1121/settingscompat)库。

// 调用的方法
```
    public static String getProp(String name) {
        String line = null;
        BufferedReader input = null;
        try {
            Process p = Runtime.getRuntime().exec("getprop " + name);
            input = new BufferedReader(new InputStreamReader(p.getInputStream()), 1024);
            line = input.readLine();
            input.close();
        } catch (IOException ex) {
            Log.e(TAG, "Unable to read prop " + name, ex);
            return null;
        } finally {
            if (input != null) {
                try {
                    input.close();
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }
        }
        return line;
    }
```

**Xposed模块列表/Xposed Module List**

允许截图/Screenshot allowed

**Magisk模块列表/Magisk Module List**

允许截图/Screenshot allowed

**EdXposed及Riru版本/Versions of EdXposed and Riru**

EdXposed:v90.0-0.3.1.7-beta

Riru:v0.3.1.7_beta

**相关Logcat/Logcat**

Fatal Exception: java.lang.StackOverflowError: stack size 8MB
       at de.robv.android.xposed.XposedBridge.log(XposedBridge.java:186)
       at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:377)
       at java.lang.ProcessBuilder.start(ProcessBuilder.java)
       at xpomdu.nijigenirubasho.shelldisable.X$100000001.replaceHookedMethod(X.java:62)
       at de.robv.android.xposed.XC_MethodReplacement.beforeHookedMethod(XC_MethodReplacement.java:29)
       at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:341)
       at java.lang.ProcessBuilder.start(ProcessBuilder.java)
       at xpomdu.nijigenirubasho.shelldisable.X$100000001.replaceHookedMethod(X.java:62)
       at de.robv.android.xposed.XC_MethodReplacement.beforeHookedMethod(XC_MethodReplacement.java:29)
       at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:341)
       at java.lang.ProcessBuilder.start(ProcessBuilder.java)
       at xpomdu.nijigenirubasho.shelldisable.X$100000001.replaceHookedMethod(X.java:62)
       at de.robv.android.xposed.XC_MethodReplacement.beforeHookedMethod(XC_MethodReplacement.java:29)
       at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:341)
       at java.lang.ProcessBuilder.start(ProcessBuilder.java)
       at xpomdu.nijigenirubasho.shelldisable.X$100000001.replaceHookedMethod(X.java:62)
       at de.robv.android.xposed.XC_MethodReplacement.beforeHookedMethod(XC_MethodReplacement.java:29)
       at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:341)
       at java.lang.ProcessBuilder.start(ProcessBuilder.java)
       at xpomdu.nijigenirubasho.shelldisable.X$100000001.replaceHookedMethod(X.java:62)
       at de.robv.android.xposed.XC_MethodReplacement.beforeHookedMethod(XC_MethodReplacement.java:29)
       at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:341)
       at java.lang.ProcessBuilder.start(ProcessBuilder.java)
       at xpomdu.nijigenirubasho.shelldisable.X$100000001.replaceHookedMethod(X.java:62)
       at de.robv.android.xposed.XC_MethodReplacement.beforeHookedMethod(XC_MethodReplacement.java:29)
       at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:341)
       at java.lang.ProcessBuilder.start(ProcessBuilder.java)
       at xpomdu.nijigenirubasho.shelldisable.X$100000001.replaceHookedMethod(X.java:62)
       at de.robv.android.xposed.XC_MethodReplacement.beforeHookedMethod(XC_MethodReplacement.java:29)
       at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:341)
       at java.lang.ProcessBuilder.start(ProcessBuilder.java)
       at xpomdu.nijigenirubasho.shelldisable.X$100000001.replaceHookedMethod(X.java:62)
       at de.robv.android.xposed.XC_MethodReplacement.beforeHookedMethod(XC_MethodReplacement.java:29)
       at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:341)
       at java.lang.ProcessBuilder.start(ProcessBuilder.java)
       at xpomdu.nijigenirubasho.shelldisable.X$100000001.replaceHookedMethod(X.java:62)
       at de.robv.android.xposed.XC_MethodReplacement.beforeHookedMethod(XC_MethodReplacement.java:29)
       at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:341)
       at java.lang.ProcessBuilder.start(ProcessBuilder.java)
       at xpomdu.nijigenirubasho.shelldisable.X$100000001.replaceHookedMethod(X.java:62)
       at de.robv.android.xposed.XC_MethodReplacement.beforeHookedMethod(XC_MethodReplacement.java:29)
       at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:341)
       at java.lang.ProcessBuilder.start(ProcessBuilder.java)
       at java.lang.Runtime.exec(Runtime.java:692)
       at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(XposedBridge.java)
       at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:361)
       at java.lang.Runtime.exec(Runtime.java)
       at java.lang.Runtime.exec(Runtime.java:525)
       at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(XposedBridge.java)
       at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:361)
       at java.lang.Runtime.exec(Runtime.java)
       at java.lang.Runtime.exec(Runtime.java:422)
       at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(XposedBridge.java)
       at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:361)
       at java.lang.Runtime.exec(Runtime.java)
       at ezy.assist.compat.RomUtil.getProp(RomUtil.java:127)
       at ezy.assist.compat.RomUtil.check(RomUtil.java:101)
       at ezy.assist.compat.RomUtil.isMiui(RomUtil.java:58)

**Comment by solohsu** [comment]
at xpomdu.nijigenirubasho.shelldisable.X$100000001.replaceHookedMethod(X.java:62)
这个模块hook了
at java.lang.ProcessBuilder.start(ProcessBuilder.java)
这个方法， 死循环了。
