### ISSUE TITLE
SandHook Throwable (?)

### ISSUE THREAD

**Issue by Mikanoshi** [ElderDrivers/EdXposed#229]
Error appeared after updating to SandHook version. Happens during module loading, doesn't affect anything it seems, modules are still working.

```
E/EdXposed-Bridge: java.lang.Throwable
        at de.robv.android.xposed.XposedInit$7.beforeHookedMethod(XposedInit.java:274)
        at de.robv.android.xposed.XC_MethodHook.callBeforeHookedMethod(XC_MethodHook.java:51)
        at com.swift.sandhook.xposedcompat.hookstub.HookStubManager.hookBridge(HookStubManager.java:276)
        at com.swift.sandhook.xposedcompat.hookstub.MethodHookerStubs64.stub_hook_2(MethodHookerStubs64.java:570)
        at android.util.apk.ApkSignatureVerifier.verifyV1Signature(Unknown Source:591)
        at android.util.apk.ApkSignatureVerifier.plsCertsNoVerifyOnlyCerts(Unknown Source:216)
        at android.content.pm.PackageParser.collectCertificates(Unknown Source:16)
        at android.content.pm.PackageParser.collectCertificatesInternal(Unknown Source:19)
        at android.content.pm.PackageParser.collectCertificates(Unknown Source:0)
        at com.android.server.pm.PackageManagerService.collectCertificatesLI(Unknown Source:161)
        at com.android.server.pm.PackageManagerService.addForInitLI(Unknown Source:593)
        at com.android.server.pm.PackageManagerService.scanPackageChildLI(Unknown Source:38)
        at com.android.server.pm.PackageManagerService.scanDirLI(Unknown Source:213)
        at com.android.server.pm.PackageManagerService.scanDirTracedLI(Unknown Source:33)
        at com.android.server.pm.PackageManagerService.<init>(Unknown Source:1326)
        at com.android.server.pm.PackageManagerService.main(Unknown Source:5)
        at com.android.server.SystemServer.startBootstrapServices(Unknown Source:326)
        at com.elderdrivers.riru.edxp.sandhook.entry.hooker.StartBootstrapServicesHooker.hook(StartBootstrapServicesHooker.java:74)
        at com.android.server.SystemServer.run(Unknown Source:267)
        at com.android.server.SystemServer.main(Unknown Source:10)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
        at com.android.internal.os.ZygoteInit.main(Unknown Source:249)
```

Also this error bugs me all the time, happens on boot too.
```
E/EdXposed-Fwk: error when hooking LoadedApk.<init>: pkg=com.miui.securitycenter, prc=com.miui.securitycenter
    java.lang.NullPointerException
        at java.io.File.<init>(File.java:283)
        at dalvik.system.DexPathList.addNativePath(DexPathList.java:617)
        at dalvik.system.BaseDexClassLoader.addNativePath(BaseDexClassLoader.java:201)
        at android.app.ApplicationLoaders.addNative(Unknown Source:7)
        at android.app.LoadedApk.createOrUpdateClassLoaderLocked(Unknown Source:396)
        at android.app.LoadedApk.getClassLoader(Unknown Source:6)
        at com.elderdrivers.riru.edxp.sandhook.entry.hooker.LoadedApkConstructorHooker.hook(LoadedApkConstructorHooker.java:90)
        at android.app.ContextCompat.createLoadedApk(Unknown Source:101)
        at android.app.ContextCompat.createApplicationContext(Unknown Source:0)
        at com.miui.securitycenter.dynamic.ApkLoader.getDynamicContext(Unknown Source:36)
        at com.miui.securitycenter.dynamic.DynamicServiceManager.createOrUpdateManagerWT(Unknown Source:2)
        at com.miui.securitycenter.dynamic.DynamicServiceManager.connectWT(Unknown Source:19)
        at com.miui.securitycenter.dynamic.DynamicServiceManager.access$400(Unknown Source:0)
        at com.miui.securitycenter.dynamic.DynamicServiceManager$DynamicWorkHandler.handleMessage(Unknown Source:35)
        at android.os.Handler.dispatchMessage(Unknown Source:21)
        at android.os.Looper.loop(Unknown Source:208)
        at android.os.HandlerThread.run(Unknown Source:28)
```

Errors are not caused by 3rd party hooks. I only have 2 modules active and they are both mine.

**Comment by solohsu** [comment]
The first one has been fixed and the second one is a caught throwable which should do no harm.

**Comment by Mikanoshi** [comment]
They do no harm, but clutter the Xposed log. I always look for errors in my module and always have to ignore this one :)
