### ISSUE TITLE
[BUG] [8.1.0] Failed resolution of: xposed.dummy.XTypedArraySuperClass

### ISSUE THREAD

**Issue by C3C0** [ElderDrivers/EdXposed#236]
**What happened?**
Resource related error flood in logcat when PackageManager is parsing packages (see attached log) on Android Oreo 8.1.0 (Nexus5X official ROM OPM7.181205.001)

**Xposed Module List**
No modules installed

**Magisk Module List**
- riru
- EdXposed 

**Versions of EdXposed and Riru**
- EdXposed: v0.4.1.2_beta (Sandhook)
- Riru: v17.1

**Logcat**
[log.txt](https://github.com/ElderDrivers/EdXposed/files/3140886/log.txt)

**Comment by C3C0** [comment]
The same issue for YAHFA version as well.

**Comment by Mikanoshi** [comment]
I hope this error is what causes Xposed module with resource hooks to crash, otherwise I have no idea how it's possible that application cannot find xml layout that is there in its own apk :)
It was working on 0.3.1.7 (without resource hooks ofc).

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{name.mikanoshi.customiuizer/name.mikanoshi.customiuizer.MainActivity}: android.content.res.Resources$NotFoundException: File res/layout/activity_main.xml from xml type layout resource ID #0x7f0a0000
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2814)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892)
	at android.app.ActivityThread.-wrap11(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1613)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:176)
	at android.app.ActivityThread.main(ActivityThread.java:6635)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)
Caused by: android.content.res.Resources$NotFoundException: File res/layout/activity_main.xml from xml type layout resource ID #0x7f0a0000
	at android.content.res.ResourcesImpl.loadXmlResourceParser(ResourcesImpl.java:1181)
	at android.content.res.Resources.loadXmlResourceParser(Resources.java:2161)
	at android.content.res.Resources.getLayout(Resources.java:1157)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:425)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
	at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:419)
	at android.app.Activity.setContentView(Activity.java:2724)
	at name.mikanoshi.customiuizer.ActivityEx.onCreate(ActivityEx.java:18)
	at name.mikanoshi.customiuizer.MainActivity.onCreate(MainActivity.java:31)
	at android.app.Activity.performCreate(Activity.java:7084)
	at android.app.Activity.performCreate(Activity.java:7075)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1215)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2767)
	... 9 more
Caused by: java.io.FileNotFoundException: res/layout/activity_main.xml
	at android.content.res.AssetManager.openXmlAssetNative(Native Method)
	at android.content.res.AssetManager.openXmlBlockAsset(AssetManager.java:550)
	at android.content.res.ResourcesImpl.loadXmlResourceParser(ResourcesImpl.java:1166)
	... 21 more
```
