### ISSUE TITLE
[BUG] 无法兼容PUBG Tool

### ISSUE THREAD

**Issue by Pr0j3c1X** [ElderDrivers/EdXposed#266]
**什么情况/What happened?**

打开PUBG Tool闪退。

**Xposed模块列表/Xposed Module List**

允许截图/Screenshot allowed

不需要

**Magisk模块列表/Magisk Module List**

允许截图/Screenshot allowed

不需要

**EdXposed及Riru版本/Versions of EdXposed and Riru**

EdXposed:0.4.2.3-SandHook

Riru:19.1

**相关Logcat/Logcat**
java.lang.InternalError: Attempt to register dex file /data/app/com.yaxisvip.pubgtoolalpha.pro-pFqQM_QuGdmjM3SheKmDvg==/base.apk with multiple class loaders
	at dalvik.system.DexFile.defineClassNative(Native Method)
	at dalvik.system.DexFile.defineClass(DexFile.java:283)
	at dalvik.system.DexFile.loadClassBinaryName(DexFile.java:276)
	at dalvik.system.DexPathList$Element.findClass(DexPathList.java:724)
	at dalvik.system.DexPathList.findClass(DexPathList.java:486)
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:132)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at com.tencent.StubShell.TxAppEntry.attachBaseContext(Unknown Source:34)
	at android.app.Application.attach(Unknown Source:0)
	at android.app.Instrumentation.newApplication(Unknown Source:12)
	at android.app.LoadedApk.makeApplication(Unknown Source:61)
	at android.app.ActivityThread.handleBindApplication(Unknown Source:1134)
	at com.elderdrivers.riru.edxp.sandhook._hooker.HandleBindAppHooker.hook(HandleBindAppHooker.java:105)
	at android.app.ActivityThread.access$1200(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(Unknown Source:703)
	at android.os.Handler.dispatchMessage(Unknown Source:21)
	at android.os.Looper.loop(Unknown Source:208)
	at android.app.ActivityThread.main(Unknown Source:107)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
	at com.android.internal.os.ZygoteInit.main(Unknown Source:274)

有助于定位问题，必须使用我们的log抓取模块抓取/It can help us to locate issue, must use our logcat module

**Comment by solohsu** [comment]
Fixed.
