### ISSUE TITLE
[BUG] error when hooking

### ISSUE THREAD

**Issue by iQuick** [ElderDrivers/EdXposed#277]
**什么情况/What happened?**

在酷派 Adnroid 9.0 上 hook 我的模块 io.xiakeapp 报错

**EdXposed及Riru版本/Versions of EdXposed and Riru**

EdXposed: v0.4.1.2_beta

Riru: 19.2

**相关Logcat/Logcat**

2019-06-04 10:20:34.634 4846-4846/io.xiakeapp:p2 E/====DreamHook===: io.xiakeapp这个是包名
2019-06-04 10:20:40.110 4846-4846/com.tencent.mm E/EdXposed-Fwk: error when hooking LoadedApk.<init>: pkg=io.xiakeapp, prc=io.xiakeapp
    java.lang.NullPointerException: Attempt to read from null array
        at android.app.LoadedApk.setupJitProfileSupport(LoadedApk.java:844)
        at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:803)
        at android.app.LoadedApk.getClassLoader(LoadedApk.java:810)
        at com.elderdrivers.riru.edxp.sandhook.entry.hooker.LoadedApkConstructorHooker.hook(LoadedApkConstructorHooker.java:90)
        at android.app.ActivityThread.getPackageInfo(ActivityThread.java:2092)
        at android.app.ActivityThread.getPackageInfo(ActivityThread.java:2047)
        at android.app.ActivityThread.getPackageInfo(ActivityThread.java:2019)
        at android.app.ContextImpl.createPackageContextAsUser(ContextImpl.java:2100)
        at android.app.ContextImpl.createPackageContext(ContextImpl.java:2087)
        at com.lody.virtual.client.VClientImpl.createPackageContext(VClientImpl.java:724)
        at com.lody.virtual.client.VClientImpl.bindApplicationNoCheck(VClientImpl.java:415)
        at com.lody.virtual.client.VClientImpl.bindApplication(VClientImpl.java:268)
        at com.lody.virtual.client.VClientImpl.handleReceiver(VClientImpl.java:892)
        at com.lody.virtual.client.VClientImpl.access$700(VClientImpl.java:113)
        at com.lody.virtual.client.VClientImpl$H.handleMessage(VClientImpl.java:980)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6746)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by solohsu** [comment]
Fixed with 92568985030a9ae7a5e3b957713cfb91384f727f.
