### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by 3412566455** [ElderDrivers/EdXposed#301]
微信打开转账界面后微信崩溃

hook 7.0.4微信中的 com.tencent.mm.plugin.remittance.model.e 类的 b 方法
当打开微信转账界面的时候 微信发生崩溃情况

com.tencent.mm E/EdXposed-dexmaker: error when getClassForSure
    java.lang.ExceptionInInitializerError
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:453)
        at com.elderdrivers.riru.edxp.yahfa.dexmaker.MethodInfo.getClassForSure(MethodInfo.java:61)
        at com.elderdrivers.riru.edxp.yahfa.dexmaker.DexMakerUtils.findMethodNative(DexMakerUtils.java:251)
        at com.elderdrivers.riru.edxp.yahfa.config.YahfaHookProvider.findMethodNative(YahfaHookProvider.java:26)
        at de.robv.android.xposed.XposedBridge.hookMethod(XposedBridge.java:233)
        at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:187)
        at com.ac.wechat.TestHook.handleLoadPackage(TestHook.java:38)
        at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(IXposedHookLoadPackage.java:34)
        at de.robv.android.xposed.callbacks.XC_LoadPackage.call(XC_LoadPackage.java:61)
        at de.robv.android.xposed.callbacks.XCallback.callAll(XCallback.java:116)
        at com.elderdrivers.riru.edxp.yahfa._hooker.HandleBindAppHooker.hook(HandleBindAppHooker.java:76)
        at android.app.ActivityThread.-wrap1(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1706)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:176)
        at android.app.ActivityThread.main(ActivityThread.java:6656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
请大神赐教

**Comment by solohsu** [comment]
新版中已解决。
