### ISSUE TITLE
[BUG] Broken module resources

### ISSUE THREAD

**Issue by Mikanoshi** [ElderDrivers/EdXposed#305]
Right after module APK is installed, resources are available - activity from module opens, launcher icon is displayed, etc. But as soon as you activate module and reboot none of the resources work.
I don't experience it on my device (Android 9), but I get bug reports from users of my module (30+ reports with this problem now and counting) and they all have the same error which only happens on Android 8-8.1. Module settings activity cannot be launched because it cannot find the layout xml file in resources. Icon in launchers changes to a default system icon, most likely because original is not available.

Error happens on a wide range of EdXposed versions up to 0.4.3.7_alpha.
All devices are Xiaomi devices with MIUI ROMs.
Xposed logs (from older versions, where they were working) don't contain any errors that could explain what's wrong.

Activity crash stack trace:
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{name.mikanoshi.customiuizer/name.mikanoshi.customiuizer.MainActivity}: android.content.res.Resources$NotFoundException: File res/layout/activity_main.xml from xml type layout resource ID #0x7f0b0000
	at android.app.ActivityThread.performLaunchActivity(Unknown Source:524)
	at android.app.ActivityThread.handleLaunchActivity(Unknown Source:37)
	at android.app.ActivityThread.-wrap11(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(Unknown Source:80)
	at android.os.Handler.dispatchMessage(Unknown Source:21)
	at android.os.Looper.loop(Unknown Source:152)
	at android.app.ActivityThread.main(Unknown Source:65)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
	at com.android.internal.os.ZygoteInit.main(Unknown Source:338)
Caused by: android.content.res.Resources$NotFoundException: File res/layout/activity_main.xml from xml type layout resource ID #0x7f0b0000
	at android.content.res.ResourcesImpl.loadXmlResourceParser(Unknown Source:190)
	at android.content.res.Resources.loadXmlResourceParser(Unknown Source:23)
	at android.content.res.Resources.getLayout(Unknown Source:3)
	at android.content.res.XResources.getLayout(XResources.java:962)
	at android.view.LayoutInflater.inflate(Unknown Source:16)
	at android.view.LayoutInflater.inflate(Unknown Source:3)
	at com.android.internal.policy.PhoneWindow.setContentView(Unknown Source:70)
	at android.app.Activity.setContentView(Unknown Source:4)
	at name.mikanoshi.customiuizer.MainActivity.onCreate(MainActivity.java:41)
	at android.app.Activity.performCreate(Unknown Source:48)
	at android.app.Activity.performCreate(Unknown Source:1)
	at android.app.Instrumentation.callActivityOnCreate(Unknown Source:3)
	at android.app.ActivityThread.performLaunchActivity(Unknown Source:466)
	... 9 more
Caused by: java.io.FileNotFoundException: res/layout/activity_main.xml
	at android.content.res.AssetManager.openXmlAssetNative(Native Method)
	at android.content.res.AssetManager.openXmlBlockAsset(Unknown Source:17)
	at android.content.res.ResourcesImpl.loadXmlResourceParser(Unknown Source:48)
	... 21 more
```

**Comment by solohsu** [comment]
> ... 21 more

Need the complete stacktrace.

**Comment by Mikanoshi** [comment]
Isn't it just the replacement for previous lines?
... 9 more means 9 last lines from exception above, ... 21 more means the same for the second exception.

**Comment by Mikanoshi** [comment]
Also some reports have this errors before the activity crash:
```
06-13 15:01:58.918 W/zygote64( 7558): miui_dex2oat:　OatFile: /data/dalvik-cache/arm64/data@app@name.mikanoshi.customiuizer-TLQb7_1drEfn4A_Oe9ZhuQ==@base.apk@classes.dex Compiler-Filter = quicken
06-13 15:01:58.926 D/SandHook( 7558): method <public void name.mikanoshi.customiuizer.MainFragment.onActivityCreated(android.os.Bundle)> hook <replacement> success!
06-13 15:01:58.938 W/ResourceType( 7558): No package identifier when getting name for resource number 0x00000000
06-13 15:01:58.943 W/ResourceType( 7558): No package identifier when getting name for resource number 0x00000000
06-13 15:01:58.945 E/ziparchive( 7558): Zip: failed to read at offset 0
06-13 15:01:58.945 W/ziparchive( 7558): Zip: failed reading lfh name from offset 0
06-13 15:01:58.946 W/PackageParser( 7558): Failed to parse /data/app/name.mikanoshi.customiuizer-TLQb7_1drEfn4A_Oe9ZhuQ==/base.apk
06-13 15:01:58.946 W/PackageParser( 7558): java.io.FileNotFoundException: AndroidManifest.xml
06-13 15:01:58.946 W/PackageParser( 7558): 	at android.content.res.AssetManager.openXmlAssetNative(Native Method)
06-13 15:01:58.946 W/PackageParser( 7558): 	at android.content.res.AssetManager.openXmlBlockAsset(AssetManager.java:550)
06-13 15:01:58.946 W/PackageParser( 7558): 	at android.content.res.AssetManager.openXmlResourceParser(AssetManager.java:518)
06-13 15:01:58.946 W/PackageParser( 7558): 	at android.content.pm.PackageParser.parseApkLite(PackageParser.java:1831)
06-13 15:01:58.946 W/PackageParser( 7558): 	at android.content.pm.PackageParser.parseMonolithicPackageLite(PackageParser.java:894)
06-13 15:01:58.946 W/PackageParser( 7558): 	at android.content.pm.PackageParser.parsePackageLite(PackageParser.java:887)
06-13 15:01:58.946 W/PackageParser( 7558): 	at android.content.res.XResources.getPackageName(XResources.java:166)
06-13 15:01:58.946 W/PackageParser( 7558): 	at android.content.res.XResources.initObject(XResources.java:97)
06-13 15:01:58.946 W/PackageParser( 7558): 	at de.robv.android.xposed.XposedInit.cloneToXResources(XposedInit.java:272)
06-13 15:01:58.946 W/PackageParser( 7558): 	at de.robv.android.xposed.XposedInit.access$000(XposedInit.java:53)
06-13 15:01:58.946 W/PackageParser( 7558): 	at de.robv.android.xposed.XposedInit$2.afterHookedMethod(XposedInit.java:138)
06-13 15:01:58.946 W/PackageParser( 7558): 	at de.robv.android.xposed.XC_MethodHook.callAfterHookedMethod(XC_MethodHook.java:68)
06-13 15:01:58.946 W/PackageParser( 7558): 	at com.swift.sandhook.xposedcompat.hookstub.HookStubManager.hookBridge(HookStubManager.java:313)
06-13 15:01:58.946 W/PackageParser( 7558): 	at com.swift.sandhook.xposedcompat.hookstub.MethodHookerStubs64.stub_hook_0(MethodHookerStubs64.java:558)
06-13 15:01:58.946 W/PackageParser( 7558): 	at android.app.ResourcesManager.getResources(ResourcesManager.java:718)
06-13 15:01:58.946 W/PackageParser( 7558): 	at android.app.LoadedApk.getResources(LoadedApk.java:953)
06-13 15:01:58.946 W/PackageParser( 7558): 	at android.app.ContextImpl.createAppContext(ContextImpl.java:2282)
06-13 15:01:58.946 W/PackageParser( 7558): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5722)
06-13 15:01:58.946 W/PackageParser( 7558): 	at java.lang.reflect.Method.invoke(Native Method)
06-13 15:01:58.946 W/PackageParser( 7558): 	at com.swift.sandhook.SandHook.callOriginMethod(SandHook.java:176)
06-13 15:01:58.946 W/PackageParser( 7558): 	at com.swift.sandhook.SandHook.callOriginMethod(SandHook.java:154)
06-13 15:01:58.946 W/PackageParser( 7558): 	at com.swift.sandhook.xposedcompat.hookstub.HookStubManager.hookBridge(HookStubManager.java:299)
06-13 15:01:58.946 W/PackageParser( 7558): 	at com.swift.sandhook.xposedcompat.hookstub.MethodHookerStubs64.stub_hook_0(MethodHookerStubs64.java:198)
06-13 15:01:58.946 W/PackageParser( 7558): 	at android.app.ActivityThread.-wrap1(Unknown Source:0)
06-13 15:01:58.946 W/PackageParser( 7558): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1685)
06-13 15:01:58.946 W/PackageParser( 7558): 	at android.os.Handler.dispatchMessage(Handler.java:106)
06-13 15:01:58.946 W/PackageParser( 7558): 	at android.os.Looper.loop(Looper.java:176)
06-13 15:01:58.946 W/PackageParser( 7558): 	at android.app.ActivityThread.main(ActivityThread.java:6651)
06-13 15:01:58.946 W/PackageParser( 7558): 	at java.lang.reflect.Method.invoke(Native Method)
06-13 15:01:58.946 W/PackageParser( 7558): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
06-13 15:01:58.946 W/PackageParser( 7558): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:824)
06-13 15:01:58.953 W/ResourceType( 7558): No package identifier when getting name for resource number 0x00000000
06-13 15:01:58.956 D/miuisdk ( 7558): current sdk level is 15
06-13 15:01:58.957 D/        ( 7558): InitMiuiSdkHookClasses
06-13 15:01:58.957 I/        ( 7558): create_mem miui-classproxy page:0x753c360000, size:4096
06-13 15:01:58.957 I/        ( 7558): Jit enabled JitInlinerInsertMethod for jit inline
06-13 15:01:58.960 I/chatty  ( 7558): uid=10234(name.mikanoshi.customiuizer) identical 39 lines
06-13 15:01:58.960 I/        ( 7558): Jit enabled JitInlinerInsertMethod for jit inline
06-13 15:01:58.961 I/        ( 7558): Never hook EnableMethodTracing
06-13 15:01:58.961 I/        ( 7558): Never hook DisableMethodTracing
06-13 15:01:58.961 I/        ( 7558): sConfigureStubsHookFlag is 0x3, so we must hook ConfigureStubs for methodtracing
06-13 15:01:58.961 I/        ( 7558): Hook ConfigureStubs
06-13 15:01:58.961 I/        ( 7558): create_mem miui-classproxy page:0x753c1ad000, size:4096
06-13 15:01:58.974 I/ACRA    ( 7558): ACRA is enabled for name.mikanoshi.customiuizer, initializing...
06-13 15:01:58.993 W/ResourceType( 7558): No package identifier when getting name for resource number 0x00000000
06-13 15:01:58.996 W/ResourceType( 7558): No package identifier when getting name for resource number 0x00000000
06-13 15:01:58.999 E/ziparchive( 7558): Zip: failed to read at offset 0
06-13 15:01:58.999 W/ziparchive( 7558): Zip: failed reading lfh name from offset 0
06-13 15:01:59.000 W/PackageParser( 7558): Failed to parse /data/app/name.mikanoshi.customiuizer-TLQb7_1drEfn4A_Oe9ZhuQ==/base.apk
06-13 15:01:59.000 W/PackageParser( 7558): java.io.FileNotFoundException: AndroidManifest.xml
06-13 15:01:59.000 W/PackageParser( 7558): 	at android.content.res.AssetManager.openXmlAssetNative(Native Method)
06-13 15:01:59.000 W/PackageParser( 7558): 	at android.content.res.AssetManager.openXmlBlockAsset(AssetManager.java:550)
06-13 15:01:59.000 W/PackageParser( 7558): 	at android.content.res.AssetManager.openXmlResourceParser(AssetManager.java:518)
06-13 15:01:59.000 W/PackageParser( 7558): 	at android.content.pm.PackageParser.parseApkLite(PackageParser.java:1831)
06-13 15:01:59.000 W/PackageParser( 7558): 	at android.content.pm.PackageParser.parseMonolithicPackageLite(PackageParser.java:894)
06-13 15:01:59.000 W/PackageParser( 7558): 	at android.content.pm.PackageParser.parsePackageLite(PackageParser.java:887)
06-13 15:01:59.000 W/PackageParser( 7558): 	at android.content.res.XResources.getPackageName(XResources.java:166)
06-13 15:01:59.000 W/PackageParser( 7558): 	at android.content.res.XResources.initObject(XResources.java:97)
06-13 15:01:59.000 W/PackageParser( 7558): 	at de.robv.android.xposed.XposedInit.cloneToXResources(XposedInit.java:272)
06-13 15:01:59.000 W/PackageParser( 7558): 	at de.robv.android.xposed.XposedInit.access$000(XposedInit.java:53)
06-13 15:01:59.000 W/PackageParser( 7558): 	at de.robv.android.xposed.XposedInit$2.afterHookedMethod(XposedInit.java:138)
06-13 15:01:59.000 W/PackageParser( 7558): 	at de.robv.android.xposed.XC_MethodHook.callAfterHookedMethod(XC_MethodHook.java:68)
06-13 15:01:59.000 W/PackageParser( 7558): 	at com.swift.sandhook.xposedcompat.hookstub.HookStubManager.hookBridge(HookStubManager.java:313)
06-13 15:01:59.000 W/PackageParser( 7558): 	at com.swift.sandhook.xposedcompat.hookstub.MethodHookerStubs64.stub_hook_0(MethodHookerStubs64.java:558)
06-13 15:01:59.000 W/PackageParser( 7558): 	at android.app.ResourcesManager.getResources(ResourcesManager.java:718)
06-13 15:01:59.000 W/PackageParser( 7558): 	at android.app.ContextImpl.createResources(ContextImpl.java:2005)
06-13 15:01:59.000 W/PackageParser( 7558): 	at android.app.ContextImpl.createConfigurationContext(ContextImpl.java:2116)
06-13 15:01:59.000 W/PackageParser( 7558): 	at android.content.ContextWrapper.createConfigurationContext(ContextWrapper.java:880)
06-13 15:01:59.000 W/PackageParser( 7558): 	at name.mikanoshi.customiuizer.utils.Helpers.getLocaleContext(Helpers.java:474)
06-13 15:01:59.000 W/PackageParser( 7558): 	at name.mikanoshi.customiuizer.utils.Helpers.getProtectedContext(Helpers.java:486)
06-13 15:01:59.000 W/PackageParser( 7558): 	at name.mikanoshi.customiuizer.utils.Helpers.getProtectedContext(Helpers.java:490)
06-13 15:01:59.000 W/PackageParser( 7558): 	at name.mikanoshi.customiuizer.SharedPrefsProvider.onCreate(SharedPrefsProvider.java:36)
06-13 15:01:59.000 W/PackageParser( 7558): 	at android.content.ContentProvider.attachInfo(ContentProvider.java:1935)
06-13 15:01:59.000 W/PackageParser( 7558): 	at android.content.ContentProvider.attachInfo(ContentProvider.java:1910)
06-13 15:01:59.000 W/PackageParser( 7558): 	at android.app.ActivityThread.installProvider(ActivityThread.java:6386)
06-13 15:01:59.000 W/PackageParser( 7558): 	at android.app.ActivityThread.installContentProviders(ActivityThread.java:5900)
06-13 15:01:59.000 W/PackageParser( 7558): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5808)
06-13 15:01:59.000 W/PackageParser( 7558): 	at java.lang.reflect.Method.invoke(Native Method)
06-13 15:01:59.000 W/PackageParser( 7558): 	at com.swift.sandhook.SandHook.callOriginMethod(SandHook.java:176)
06-13 15:01:59.000 W/PackageParser( 7558): 	at com.swift.sandhook.SandHook.callOriginMethod(SandHook.java:154)
06-13 15:01:59.000 W/PackageParser( 7558): 	at com.swift.sandhook.xposedcompat.hookstub.HookStubManager.hookBridge(HookStubManager.java:299)
06-13 15:01:59.000 W/PackageParser( 7558): 	at com.swift.sandhook.xposedcompat.hookstub.MethodHookerStubs64.stub_hook_0(MethodHookerStubs64.java:198)
06-13 15:01:59.000 W/PackageParser( 7558): 	at android.app.ActivityThread.-wrap1(Unknown Source:0)
06-13 15:01:59.000 W/PackageParser( 7558): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1685)
06-13 15:01:59.000 W/PackageParser( 7558): 	at android.os.Handler.dispatchMessage(Handler.java:106)
06-13 15:01:59.000 W/PackageParser( 7558): 	at android.os.Looper.loop(Looper.java:176)
06-13 15:01:59.000 W/PackageParser( 7558): 	at android.app.ActivityThread.main(ActivityThread.java:6651)
06-13 15:01:59.000 W/PackageParser( 7558): 	at java.lang.reflect.Method.invoke(Native Method)
06-13 15:01:59.000 W/PackageParser( 7558): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
06-13 15:01:59.000 W/PackageParser( 7558): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:824)
06-13 15:01:59.009 W/ResourceType( 7558): No package identifier when getting name for resource number 0x00000000
06-13 15:01:59.012 W/ResourceType( 7558): No package identifier when getting name for resource number 0x00000000
06-13 15:01:59.014 E/ziparchive( 7558): Zip: failed to read at offset 0
06-13 15:01:59.015 W/ziparchive( 7558): Zip: failed reading lfh name from offset 0
06-13 15:01:59.016 W/PackageParser( 7558): Failed to parse /data/app/name.mikanoshi.customiuizer-TLQb7_1drEfn4A_Oe9ZhuQ==/base.apk
06-13 15:01:59.016 W/PackageParser( 7558): java.io.FileNotFoundException: AndroidManifest.xml
06-13 15:01:59.016 W/PackageParser( 7558): 	at android.content.res.AssetManager.openXmlAssetNative(Native Method)
06-13 15:01:59.016 W/PackageParser( 7558): 	at android.content.res.AssetManager.openXmlBlockAsset(AssetManager.java:550)
06-13 15:01:59.016 W/PackageParser( 7558): 	at android.content.res.AssetManager.openXmlResourceParser(AssetManager.java:518)
06-13 15:01:59.016 W/PackageParser( 7558): 	at android.content.pm.PackageParser.parseApkLite(PackageParser.java:1831)
06-13 15:01:59.016 W/PackageParser( 7558): 	at android.content.pm.PackageParser.parseMonolithicPackageLite(PackageParser.java:894)
06-13 15:01:59.016 W/PackageParser( 7558): 	at android.content.pm.PackageParser.parsePackageLite(PackageParser.java:887)
06-13 15:01:59.016 W/PackageParser( 7558): 	at android.content.res.XResources.getPackageName(XResources.java:166)
06-13 15:01:59.016 W/PackageParser( 7558): 	at android.content.res.XResources.initObject(XResources.java:97)
06-13 15:01:59.016 W/PackageParser( 7558): 	at de.robv.android.xposed.XposedInit.cloneToXResources(XposedInit.java:272)
06-13 15:01:59.016 W/PackageParser( 7558): 	at de.robv.android.xposed.XposedInit.access$000(XposedInit.java:53)
06-13 15:01:59.016 W/PackageParser( 7558): 	at de.robv.android.xposed.XposedInit$2.afterHookedMethod(XposedInit.java:138)
06-13 15:01:59.016 W/PackageParser( 7558): 	at de.robv.android.xposed.XC_MethodHook.callAfterHookedMethod(XC_MethodHook.java:68)
06-13 15:01:59.016 W/PackageParser( 7558): 	at com.swift.sandhook.xposedcompat.hookstub.HookStubManager.hookBridge(HookStubManager.java:313)
06-13 15:01:59.016 W/PackageParser( 7558): 	at com.swift.sandhook.xposedcompat.hookstub.MethodHookerStubs64.stub_hook_0(MethodHookerStubs64.java:558)
06-13 15:01:59.016 W/PackageParser( 7558): 	at android.app.ResourcesManager.createBaseActivityResources(ResourcesManager.java:569)
06-13 15:01:59.016 W/PackageParser( 7558): 	at android.app.ContextImpl.createActivityContext(ContextImpl.java:2321)
06-13 15:01:59.016 W/PackageParser( 7558): 	at android.app.ActivityThread.createBaseContextForActivity(ActivityThread.java:2850)
06-13 15:01:59.016 W/PackageParser( 7558): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2704)
06-13 15:01:59.016 W/PackageParser( 7558): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2895)
06-13 15:01:59.016 W/PackageParser( 7558): 	at android.app.ActivityThread.-wrap11(Unknown Source:0)
06-13 15:01:59.016 W/PackageParser( 7558): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1616)
06-13 15:01:59.016 W/PackageParser( 7558): 	at android.os.Handler.dispatchMessage(Handler.java:106)
06-13 15:01:59.016 W/PackageParser( 7558): 	at android.os.Looper.loop(Looper.java:176)
06-13 15:01:59.016 W/PackageParser( 7558): 	at android.app.ActivityThread.main(ActivityThread.java:6651)
06-13 15:01:59.016 W/PackageParser( 7558): 	at java.lang.reflect.Method.invoke(Native Method)
06-13 15:01:59.016 W/PackageParser( 7558): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
06-13 15:01:59.016 W/PackageParser( 7558): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:824)
06-13 15:01:59.019 W/ResourceType( 7558): No package identifier when getting name for resource number 0x00000000
06-13 15:01:59.067 D/AccessibilityManager( 7558): AccessibilityManager status: mPackageName = name.mikanoshi.customiuizer, mOptimizeEnabled = false, mIsEnabled = false, mIsUiAutomationEnabled = false, mIsInterestedPackage =false
06-13 15:01:59.129 E/ziparchive( 7558): Zip: failed to read at offset 238262
06-13 15:01:59.129 W/ziparchive( 7558): Zip: failed reading lfh name from offset 238262
```
