### ISSUE TITLE
[BUG] Kmod FWA module not activated and crash report 

### ISSUE THREAD

**Issue by beeshyams** [ElderDrivers/EdXposed#346]
**什么情况/What happened?**

Edit : As can be seen from comments, the problem appears to that of SELinux . I understand that this happens only with EdXposed and not Xposed. SELinux permissive is a security concern

1. KMOD FWA module (https://forum.xda-developers.com/showpost.php?p=80072069&postcount=2540) does not get activated both on YAHFA and Sandhook. Tried multiple reboots, reboot from framework, shutdown and restart, clear cache etc. It says Xposed not installed. 

Please note that developer of module says that it works on some devices on Pie 

2. I am just an user and not a developer but here is the error thrown up by Scoop Xposed module 

> java.lang.IllegalStateException: The application's PagerAdapter changed the adapter's contents without calling PagerAdapter#notifyDataSetChanged! Expected adapter item count: 1, found: 4 Pager id: org.meowcat.edxposed.manager:id/pager Pager class: class androidx.viewpager.widget.ViewPager Problematic adapter: class de.robv.android.xposed.installer.installation.AdvancedInstallerFragment$TabsAdapter
	at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1143)
	at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1092)
	at androidx.viewpager.widget.ViewPager.onMeasure(ViewPager.java:1622)
	at android.view.View.measure(View.java:23181)
	at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:715)
	at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:461)
	at android.view.View.measure(View.java:23181)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6749)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
	at android.view.View.measure(View.java:23181)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6749)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
	at android.view.View.measure(View.java:23181)
	at androidx.drawerlayout.widget.DrawerLayout.onMeasure(DrawerLayout.java:1119)
	at android.view.View.measure(View.java:23181)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6749)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
	at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:143)
	at android.view.View.measure(View.java:23181)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6749)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
	at android.view.View.measure(View.java:23181)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6749)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
	at android.view.View.measure(View.java:23181)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6749)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1535)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:825)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:704)
	at android.view.View.measure(View.java:23181)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6749)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:716)
	at android.view.View.measure(View.java:23181)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2727)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2283)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1468)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7208)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1004)
	at android.view.Choreographer.doCallbacks(Choreographer.java:816)
	at android.view.Choreographer.doFrame(Choreographer.java:751)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:990)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6762)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
无法开机/模块无效等

**Xposed模块列表/Xposed Module List**

允许截图/Screenshot allowed

**Magisk模块列表/Magisk Module List**

允许截图/Screenshot allowed

**EdXposed及Riru版本/Versions of EdXposed and Riru**

EdXposed: 0.4.5.1 beta 4463 YAHFA ( also with Sandhook) 

Riru: 19.4 latest Magisk module

**相关Logcat/Logcat**

有助于定位问题，必须使用我们的log抓取模块抓取/It can help us to locate issue, must use our logcat module
https://my.pcloud.com/publink/show?code=XZyQkc7ZJksEPKu14Sb2NxOB7CYKXjmvhXA7

**Comment by beeshyams** [comment]
Sorry, from mobile unable to upload images, hence links below (no access to laptop) 
 Xposed modules
1.https://my.pcloud.com/publink/show?code=XZMjkc7ZSyK1abKgDmX8HCN5vBJMSy1svgkV
2. https://my.pcloud.com/publink/show?code=XZ2ukc7Z7g52YrJ0Bm7nSNYOcNvIo7QQ0tik
3. https://my.pcloud.com/publink/show?code=XZwukc7ZtQG9Rrd9emVeeKpQqncl8QHhPFmV

Magisk module list

1.https://my.pcloud.com/publink/show?code=XZiukc7ZMI498DjJvaJCtkELtTFmWBNnQ4tk
2. https://my.pcloud.com/publink/show?code=XZJfkc7ZSJlE8hGDjhuMOBwlNUmLBFCKzfxk
3. https://my.pcloud.com/publink/show?code=XZNfkc7ZPRAuUbyVCv8qA2Yt7ju1vHdu2EXV
4. https://my.pcloud.com/publink/show?code=XZkBkc7Z1JrcdoFwNkhyBCXQGjOTBue1gjJy
5. https://my.pcloud.com/publink/show?code=XZ4Bkc7ZQaxtcPWFq07sNIIlDCMrf76Y8CJX
6. https://my.pcloud.com/publink/show?code=XZ9Bkc7ZEcn2Ld5gWbk3lopbrTReyREgnxSy
7. https://my.pcloud.com/publink/show?code=XZlBkc7Zd7sYMuuwqAyLzOGq9RQn650RjmGy

**Comment by yonijuerga** [comment]
Please, solve the issues with Kmod... I need it!! 😁

**Comment by beeshyams** [comment]
This may help you solve the problem - following a tip on the app XDA thread, "NFS Injector" Magisk module was flashed. After this, KMod Fwa was recognized and started working.

**Comment by Alex193a** [comment]
"NFS Injector" makes the module to work because it sets SELinux in **Permissive mode**, probably.
Can you take a test?

- Disable the NFS Injector module and restart the phone.
- Check that Kmod is NOT working.
- Use a terminal emulator app and give the commands "su" and then "getenforce"
- if the result is "Enforcing" give the command "setenforce 0"
- Force close WhatsApp and check if Kmod is working now.

Let me know if you can do this test 😃

**Comment by beeshyams** [comment]
> "NFS Injector" makes the module to work because it sets SELinux in **Permissive mode**.
> Can you take a test?
> 
> * Disable the NFS Injector module and restart the phone.
> * Check that Kmod is NOT working.
> * Use a terminal emulator app and give the commands "su" and then "getenforce"
> * If the result is "Enforcing" give the command "setenforce 0"
> * Force close WhatsApp and check if Kmod is working now.
> 
> Let me know if you can do this test

I did notice in the NFS description that it sets it to permissive but sadly ignored the risk because I need the module. After reading your view, I did something different, opposite of what you suggested(reason is that enabling, disabling, rebooting etc often requires multiple reboots and I am not going to spend time on that). From terminal emulator, getenforce showed the status as permissive as expected. I changed it to enforcing by setenforce 1 and verified that it is enforcing. KMOD FWA is working fine. I am not sure if this arrangement will work

**Comment by Alex193a** [comment]
Hmm okay, I was pretty sure this was the problem.  The same thing happens with my module, it only works with SELinux in permissive mode.

**Comment by beeshyams** [comment]
> Hmm okay, I was pretty sure this was the problem. The same thing happens with my module, it only works with SELinux in permissive mode.

You are correct. This seems to be the reason. KMOD FWA stopped working after a while and on making device permissive, works again. I hope the developers of EdXposed can fix this soon.

**Comment by Phineas019** [comment]
Is that any fix available for that i tried the steps mentioned here like changing selinux to permissive / enforcing or through shell este force 1 and 0 but no luck. Tried restarting device multiple times and clear the cache nothing happened.

I'm running on android 10 and whatsapp 2.20.xxx still i got this all the time 
 https://drive.google.com/file/d/1-7LU_xtcHNoV3BgQ4Rf5e0IsF3GhmhMi/view?usp=drivesdk
https://drive.google.com/file/d/1-A-KHZ0hhepWFZwqOO204FAVktbP2gZo/view?usp=drivesdk

Hope for some help !!

**Comment by kotori2** [comment]
From the [XDA comments](https://forum.xda-developers.com/t/xposed-mod-4-0-22-05-2020-kmod-fwa-v2-8-1-whatsapp-privacy-customization.3223791/post-84018221) it seems this was fixed by the module developer.
