### ISSUE TITLE
[BUG] MIUI 应用双开，双开的应用无法正常使用

### ISSUE THREAD

**Issue by gam2046** [ElderDrivers/EdXposed#397]
**什么情况/What happened?**

1、对于微信使用MIUI的应用双开功能（即多用户），存在A1/A2两个应用
2、存在插件X通过EdXposed注入应用A
3、A1（系统宿主用户）X注入正常，A2（双开用户）X注入异常，导致A2无法正常启动

**Xposed模块列表/Xposed Module List**

微X模块 2.3

**Magisk模块列表/Magisk Module List**

Riru - Core

**EdXposed及Riru版本/Versions of EdXposed and Riru**

EdXposed: 90.0-v0.4.6.0_beta(SandHook)

Riru: v19.5

**相关Logcat/Logcat**

模块日志:
```
11-28 18:36:28.303 10094 10094 E EdXposed-Bridge: Cannot load any modules because /data/user_de/0/org.meowcat.edxposed.manager/conf/modules.list was not found
```

详细日志:
```
11-28 18:36:28.303 10094 10094 E EdXposed-Bridge: Cannot load any modules because /data/user_de/0/org.meowcat.edxposed.manager/conf/modules.list was not found
11-28 18:37:20.967  3042  3413 E EdXposed-Bridge: android.content.pm.PackageManager$NameNotFoundException: com.google.android.wearable.app
11-28 18:37:20.967  3042  3413 E EdXposed-Bridge: 	at android.app.ApplicationPackageManager.getPackageInfoAsUser(ApplicationPackageManager.java:194)
11-28 18:37:20.967  3042  3413 E EdXposed-Bridge: 	at android.app.ApplicationPackageManager.getPackageInfo(ApplicationPackageManager.java:161)
11-28 18:37:20.967  3042  3413 E EdXposed-Bridge: 	at java.lang.reflect.Method.invoke(Native Method)
11-28 18:37:20.967  3042  3413 E EdXposed-Bridge: 	at com.swift.sandhook.SandHook.callOriginMethod(SandHook.java:176)
11-28 18:37:20.967  3042  3413 E EdXposed-Bridge: 	at com.swift.sandhook.SandHook.callOriginMethod(SandHook.java:154)
11-28 18:37:20.967  3042  3413 E EdXposed-Bridge: 	at com.swift.sandhook.xposedcompat.hookstub.HookStubManager.hookBridge(HookStubManager.java:299)
11-28 18:37:20.967  3042  3413 E EdXposed-Bridge: 	at com.swift.sandhook.xposedcompat.hookstub.MethodHookerStubs32.stub_hook_2(MethodHookerStubs32.java:392)
11-28 18:37:20.967  3042  3413 E EdXposed-Bridge: 	at com.tencent.mm.plugin.wear.model.h.KZ(SourceFile:286)
11-28 18:37:20.967  3042  3413 E EdXposed-Bridge: 	at com.tencent.mm.plugin.wear.model.a.a.isAvailable(SourceFile:31)
11-28 18:37:20.967  3042  3413 E EdXposed-Bridge: 	at com.tencent.mm.plugin.wear.model.d.cIA(SourceFile:50)
11-28 18:37:20.967  3042  3413 E EdXposed-Bridge: 	at com.tencent.mm.plugin.wear.model.d.cIz(SourceFile:46)
11-28 18:37:20.967  3042  3413 E EdXposed-Bridge: 	at com.tencent.mm.plugin.wear.model.f.c.execute(SourceFile:16)
11-28 18:37:20.967  3042  3413 E EdXposed-Bridge: 	at com.tencent.mm.plugin.wear.model.f.d.run(SourceFile:20)
11-28 18:37:20.967  3042  3413 E EdXposed-Bridge: 	at com.tencent.mm.plugin.wear.model.j$a.handleMessage(SourceFile:68)
11-28 18:37:20.967  3042  3413 E EdXposed-Bridge: 	at com.tencent.mm.sdk.platformtools.am.handleMessage(SourceFile:185)
11-28 18:37:20.967  3042  3413 E EdXposed-Bridge: 	at com.tencent.mm.sdk.platformtools.am.dispatchMessage(SourceFile:140)
11-28 18:37:20.967  3042  3413 E EdXposed-Bridge: 	at android.os.Looper.loop(Looper.java:224)
11-28 18:37:20.967  3042  3413 E EdXposed-Bridge: 	at android.os.HandlerThread.run(HandlerThread.java:67)
11-28 18:37:20.967  3042  3413 E EdXposed-Bridge: 	at com.tencent.mm.sdk.g.c.a$a.run(SourceFile:71)
11-28 18:37:20.968  3042  3413 E EdXposed-Bridge: android.content.pm.PackageManager$NameNotFoundException: com.google.android.wearable.app.cn
11-28 18:37:20.968  3042  3413 E EdXposed-Bridge: 	at android.app.ApplicationPackageManager.getPackageInfoAsUser(ApplicationPackageManager.java:194)
11-28 18:37:20.968  3042  3413 E EdXposed-Bridge: 	at android.app.ApplicationPackageManager.getPackageInfo(ApplicationPackageManager.java:161)
11-28 18:37:20.968  3042  3413 E EdXposed-Bridge: 	at java.lang.reflect.Method.invoke(Native Method)
11-28 18:37:20.968  3042  3413 E EdXposed-Bridge: 	at com.swift.sandhook.SandHook.callOriginMethod(SandHook.java:176)
11-28 18:37:20.968  3042  3413 E EdXposed-Bridge: 	at com.swift.sandhook.SandHook.callOriginMethod(SandHook.java:154)
11-28 18:37:20.968  3042  3413 E EdXposed-Bridge: 	at com.swift.sandhook.xposedcompat.hookstub.HookStubManager.hookBridge(HookStubManager.java:299)
11-28 18:37:20.968  3042  3413 E EdXposed-Bridge: 	at com.swift.sandhook.xposedcompat.hookstub.MethodHookerStubs32.stub_hook_2(MethodHookerStubs32.java:392)
11-28 18:37:20.968  3042  3413 E EdXposed-Bridge: 	at com.tencent.mm.plugin.wear.model.h.KY(SourceFile:274)
11-28 18:37:20.968  3042  3413 E EdXposed-Bridge: 	at com.tencent.mm.plugin.wear.model.a.a.isAvailable(SourceFile:31)
11-28 18:37:20.968  3042  3413 E EdXposed-Bridge: 	at com.tencent.mm.plugin.wear.model.d.cIA(SourceFile:50)
11-28 18:37:20.968  3042  3413 E EdXposed-Bridge: 	at com.tencent.mm.plugin.wear.model.d.cIz(SourceFile:46)
11-28 18:37:20.968  3042  3413 E EdXposed-Bridge: 	at com.tencent.mm.plugin.wear.model.f.c.execute(SourceFile:16)
11-28 18:37:20.968  3042  3413 E EdXposed-Bridge: 	at com.tencent.mm.plugin.wear.model.f.d.run(SourceFile:20)
11-28 18:37:20.968  3042  3413 E EdXposed-Bridge: 	at com.tencent.mm.plugin.wear.model.j$a.handleMessage(SourceFile:68)
11-28 18:37:20.968  3042  3413 E EdXposed-Bridge: 	at com.tencent.mm.sdk.platformtools.am.handleMessage(SourceFile:185)
11-28 18:37:20.968  3042  3413 E EdXposed-Bridge: 	at com.tencent.mm.sdk.platformtools.am.dispatchMessage(SourceFile:140)
11-28 18:37:20.968  3042  3413 E EdXposed-Bridge: 	at android.os.Looper.loop(Looper.java:224)
11-28 18:37:20.968  3042  3413 E EdXposed-Bridge: 	at android.os.HandlerThread.run(HandlerThread.java:67)
11-28 18:37:20.968  3042  3413 E EdXposed-Bridge: 	at com.tencent.mm.sdk.g.c.a$a.run(SourceFile:71)
11-28 18:37:33.370  3042  3413 E EdXposed-Bridge: android.content.pm.PackageManager$NameNotFoundException: com.google.android.wearable.app
11-28 18:37:33.370  3042  3413 E EdXposed-Bridge: 	at android.app.ApplicationPackageManager.getPackageInfoAsUser(ApplicationPackageManager.java:194)
11-28 18:37:33.370  3042  3413 E EdXposed-Bridge: 	at android.app.ApplicationPackageManager.getPackageInfo(ApplicationPackageManager.java:161)
11-28 18:37:33.370  3042  3413 E EdXposed-Bridge: 	at java.lang.reflect.Method.invoke(Native Method)
11-28 18:37:33.370  3042  3413 E EdXposed-Bridge: 	at com.swift.sandhook.SandHook.callOriginMethod(SandHook.java:176)
11-28 18:37:33.370  3042  3413 E EdXposed-Bridge: 	at com.swift.sandhook.SandHook.callOriginMethod(SandHook.java:154)
11-28 18:37:33.370  3042  3413 E EdXposed-Bridge: 	at com.swift.sandhook.xposedcompat.hookstub.HookStubManager.hookBridge(HookStubManager.java:299)
11-28 18:37:33.370  3042  3413 E EdXposed-Bridge: 	at com.swift.sandhook.xposedcompat.hookstub.MethodHookerStubs32.stub_hook_2(MethodHookerStubs32.java:392)
11-28 18:37:33.370  3042  3413 E EdXposed-Bridge: 	at com.tencent.mm.plugin.wear.model.h.KZ(SourceFile:286)
11-28 18:37:33.370  3042  3413 E EdXposed-Bridge: 	at com.tencent.mm.plugin.wear.model.a.a.isAvailable(SourceFile:31)
11-28 18:37:33.370  3042  3413 E EdXposed-Bridge: 	at com.tencent.mm.plugin.wear.model.d.cIA(SourceFile:50)
11-28 18:37:33.370  3042  3413 E EdXposed-Bridge: 	at com.tencent.mm.plugin.wear.model.d.cIz(SourceFile:46)
11-28 18:37:33.370  3042  3413 E EdXposed-Bridge: 	at com.tencent.mm.plugin.wear.model.f.c.execute(SourceFile:16)
11-28 18:37:33.370  3042  3413 E EdXposed-Bridge: 	at com.tencent.mm.plugin.wear.model.f.d.run(SourceFile:20)
11-28 18:37:33.370  3042  3413 E EdXposed-Bridge: 	at com.tencent.mm.plugin.wear.model.j$a.handleMessage(SourceFile:68)
11-28 18:37:33.370  3042  3413 E EdXposed-Bridge: 	at com.tencent.mm.sdk.platformtools.am.handleMessage(SourceFile:185)
11-28 18:37:33.370  3042  3413 E EdXposed-Bridge: 	at com.tencent.mm.sdk.platformtools.am.dispatchMessage(SourceFile:140)
11-28 18:37:33.370  3042  3413 E EdXposed-Bridge: 	at android.os.Looper.loop(Looper.java:224)
11-28 18:37:33.370  3042  3413 E EdXposed-Bridge: 	at android.os.HandlerThread.run(HandlerThread.java:67)
11-28 18:37:33.370  3042  3413 E EdXposed-Bridge: 	at com.tencent.mm.sdk.g.c.a$a.run(SourceFile:71)
11-28 18:37:33.372  3042  3413 E EdXposed-Bridge: android.content.pm.PackageManager$NameNotFoundException: com.google.android.wearable.app.cn
11-28 18:37:33.372  3042  3413 E EdXposed-Bridge: 	at android.app.ApplicationPackageManager.getPackageInfoAsUser(ApplicationPackageManager.java:194)
11-28 18:37:33.372  3042  3413 E EdXposed-Bridge: 	at android.app.ApplicationPackageManager.getPackageInfo(ApplicationPackageManager.java:161)
11-28 18:37:33.372  3042  3413 E EdXposed-Bridge: 	at java.lang.reflect.Method.invoke(Native Method)
11-28 18:37:33.372  3042  3413 E EdXposed-Bridge: 	at com.swift.sandhook.SandHook.callOriginMethod(SandHook.java:176)
11-28 18:37:33.372  3042  3413 E EdXposed-Bridge: 	at com.swift.sandhook.SandHook.callOriginMethod(SandHook.java:154)
11-28 18:37:33.372  3042  3413 E EdXposed-Bridge: 	at com.swift.sandhook.xposedcompat.hookstub.HookStubManager.hookBridge(HookStubManager.java:299)
11-28 18:37:33.372  3042  3413 E EdXposed-Bridge: 	at com.swift.sandhook.xposedcompat.hookstub.MethodHookerStubs32.stub_hook_2(MethodHookerStubs32.java:392)
11-28 18:37:33.372  3042  3413 E EdXposed-Bridge: 	at com.tencent.mm.plugin.wear.model.h.KY(SourceFile:274)
11-28 18:37:33.372  3042  3413 E EdXposed-Bridge: 	at com.tencent.mm.plugin.wear.model.a.a.isAvailable(SourceFile:31)
11-28 18:37:33.372  3042  3413 E EdXposed-Bridge: 	at com.tencent.mm.plugin.wear.model.d.cIA(SourceFile:50)
11-28 18:37:33.372  3042  3413 E EdXposed-Bridge: 	at com.tencent.mm.plugin.wear.model.d.cIz(SourceFile:46)
11-28 18:37:33.372  3042  3413 E EdXposed-Bridge: 	at com.tencent.mm.plugin.wear.model.f.c.execute(SourceFile:16)
11-28 18:37:33.372  3042  3413 E EdXposed-Bridge: 	at com.tencent.mm.plugin.wear.model.f.d.run(SourceFile:20)
11-28 18:37:33.372  3042  3413 E EdXposed-Bridge: 	at com.tencent.mm.plugin.wear.model.j$a.handleMessage(SourceFile:68)
11-28 18:37:33.372  3042  3413 E EdXposed-Bridge: 	at com.tencent.mm.sdk.platformtools.am.handleMessage(SourceFile:185)
11-28 18:37:33.372  3042  3413 E EdXposed-Bridge: 	at com.tencent.mm.sdk.platformtools.am.dispatchMessage(SourceFile:140)
11-28 18:37:33.372  3042  3413 E EdXposed-Bridge: 	at android.os.Looper.loop(Looper.java:224)
11-28 18:37:33.372  3042  3413 E EdXposed-Bridge: 	at android.os.HandlerThread.run(HandlerThread.java:67)
11-28 18:37:33.372  3042  3413 E EdXposed-Bridge: 	at com.tencent.mm.sdk.g.c.a$a.run(SourceFile:71)
```
有助于定位问题，必须使用我们的log抓取模块抓取/It can help us to locate issue, must use our logcat module

**Comment by tupac55** [comment]
For MIUI (Xiaomi device) use Yahfa version .. fixed my issues with my Mi 9T

**Comment by gam2046** [comment]
尝试了以下版本：

- SandHook v0.4.6.0 bata 4471
- YAHFA v0.4.6.0 bata 4471
- SandHook v0.4.6.1 oacavrdt 4491
- YAHFA v0.4.6.1 oacavrdt 4491

均出现一样的提示：
```
--------- beginning of head
EdXposed Log
Powered by Log Catcher
QQ support group: 855219808
Telegram support group: @Code_Of_MeowCat
--------- beginning of information
Manufacturer: Xiaomi
Brand: Xiaomi
Device: raphael
Product: raphael
Model: Redmi K20 Pro Premium Edition
Fingerprint: Xiaomi/raphael/raphael:10/QKQ1.190825.002/V11.0.4.0.QFKCNXM:user/release-keys
ROM description: raphael-user 10 QKQ1.190825.002 V11.0.4.0.QFKCNXM release-keys
Architecture: arm64-v8a
Android build: QKQ1.190825.002
Android version: 10
Android sdk: 29
EdXposed version: v0.4.6.1 (4491)-oacavrdt (YAHFA)
EdXposed api: 90.0
Riru version: v19.5 (27)
Riru api: 4
Magisk: 20.1:MAGISKSU (20100)
--------- beginning of main
--------- beginning of system
01-07 09:26:09.079   731   731 I EdXposed: onModuleLoaded: welcome to EdXposed!
01-07 09:26:09.079   731   731 I EdXposed: Start to install inline hooks
01-07 09:26:09.079   731   731 I EdXposed: Using api level 29
01-07 09:26:09.079   731   731 I EdXposed: Start to install Riru hook
01-07 09:26:09.089   731   731 I EdXposed: Riru hooks installed
01-07 09:26:09.128   732   732 I EdXposed: onModuleLoaded: welcome to EdXposed!
01-07 09:26:09.128   732   732 I EdXposed: Start to install inline hooks
01-07 09:26:09.128   732   732 I EdXposed: Using api level 29
01-07 09:26:09.128   732   732 I EdXposed: Start to install Riru hook
01-07 09:26:09.137   732   732 I EdXposed: Riru hooks installed
01-07 09:26:09.235   731   731 I EdXposed: ART hooks installed
01-07 09:26:09.236   731   731 I EdXposed: system_property_get: dalvik.vm.dex2oat-filter -> quicken
01-07 09:26:09.236   731   731 I EdXposed: system_property_get: dalvik.vm.dex2oat-flags -> --inline-max-code-units=0
01-07 09:26:09.316   732   732 I EdXposed: ART hooks installed
01-07 09:26:09.317   732   732 I EdXposed: system_property_get: dalvik.vm.dex2oat-filter -> quicken
01-07 09:26:09.317   732   732 I EdXposed: system_property_get: dalvik.vm.dex2oat-flags -> --inline-max-code-units=0
01-07 09:26:09.645   731   731 I EdXposed: using installer org.meowcat.edxposed.manager
01-07 09:26:09.646   731   731 I EdXposed: black/white list mode: false, using whitelist: false
01-07 09:26:09.646   731   731 I EdXposed: dynamic modules mode: false
01-07 09:26:09.646   731   731 I EdXposed: resources hook: true
01-07 09:26:09.646   731   731 I EdXposed: deopt boot image: false
01-07 09:26:09.650   732   732 I EdXposed: using installer org.meowcat.edxposed.manager
01-07 09:26:09.650   732   732 I EdXposed: black/white list mode: false, using whitelist: false
01-07 09:26:09.650   732   732 I EdXposed: dynamic modules mode: false
01-07 09:26:09.650   732   732 I EdXposed: resources hook: true
01-07 09:26:09.650   732   732 I EdXposed: deopt boot image: false
--------- beginning of crash
01-07 09:26:11.923   731   731 E EdXposed-Bridge: Cannot load any modules because /data/user_de/0/org.meowcat.edxposed.manager/conf/modules.list was not found
01-07 09:26:12.120  1670  1670 E EdXposed: mmap failed, errno = Permission denied
01-07 09:26:12.120  1670  1670 E EdXposed: cannot hook method
01-07 09:26:12.120  1670  1670 E EdXposed: error when hooking com.elderdrivers.riru.edxp._hooker.yahfa.StartBootstrapServicesHooker
01-07 09:26:12.120  1670  1670 E EdXposed: java.lang.RuntimeException: Failed to hook private void com.android.server.SystemServer.startBootstrapServices() with public static void com.elderdrivers.riru.edxp._hooker.yahfa.StartBootstrapServicesHooker.hook(java.lang.Object) throws java.lang.Throwable
01-07 09:26:12.120  1670  1670 E EdXposed: 	at com.elderdrivers.riru.edxp.core.yahfa.HookMain.backupAndHook(HookMain.java:136)
01-07 09:26:12.120  1670  1670 E EdXposed: 	at com.elderdrivers.riru.edxp.core.yahfa.HookMain.doHookDefault(HookMain.java:3097)
01-07 09:26:12.120  1670  1670 E EdXposed: 	at com.elderdrivers.riru.edxp.proxy.BaseRouter.startSystemServerHook(BaseRouter.java:134)
01-07 09:26:12.120  1670  1670 E EdXposed: 	at com.elderdrivers.riru.edxp._hooker.impl.SystemMain.afterHookedMethod(SystemMain.java:27)
01-07 09:26:12.120  1670  1670 E EdXposed: 	at de.robv.android.xposed.XC_MethodHook.callAfterHookedMethod(XC_MethodHook.java:68)
01-07 09:26:12.120  1670  1670 E EdXposed: 	at com.elderdrivers.riru.edxp._hooker.yahfa.SystemMainHooker.hook(SystemMainHooker.java:25)
01-07 09:26:12.120  1670  1670 E EdXposed: 	at com.android.server.SystemServer.createSystemContext(SystemServer.java:624)
01-07 09:26:12.120  1670  1670 E EdXposed: 	at com.android.server.SystemServer.run(SystemServer.java:507)
01-07 09:26:12.120  1670  1670 E EdXposed: 	at com.android.server.SystemServer.main(SystemServer.java:362)
01-07 09:26:12.120  1670  1670 E EdXposed: 	at java.lang.reflect.Method.invoke(Native Method)
01-07 09:26:12.120  1670  1670 E EdXposed: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
01-07 09:26:12.120  1670  1670 E EdXposed: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:928)
01-07 09:26:14.344  1670  1670 E EdXposed: mmap failed, errno = Permission denied
01-07 09:26:14.344  1670  1670 E EdXposed: cannot hook method
01-07 09:26:14.344  1670  1670 E EdXposed: error occur when generating dex. dexDir=null
01-07 09:26:14.344  1670  1670 E EdXposed: java.lang.RuntimeException: Failed to hook public java.lang.ClassLoader android.app.LoadedApk.getClassLoader() with public static java.lang.Object EdHooker_.hook(java.lang.Object)
01-07 09:26:14.344  1670  1670 E EdXposed: 	at com.elderdrivers.riru.edxp.core.yahfa.HookMain.backupAndHook(HookMain.java:136)
01-07 09:26:14.344  1670  1670 E EdXposed: 	at com.elderdrivers.riru.edxp.yahfa.dexmaker.DynamicBridge.hookMethod(DynamicBridge.java:6225)
01-07 09:26:14.344  1670  1670 E EdXposed: 	at com.elderdrivers.riru.edxp.yahfa.config.YahfaHookProvider.hookMethod(YahfaHookProvider.java:19)
01-07 09:26:14.344  1670  1670 E EdXposed: 	at de.robv.android.xposed.XposedBridge.hookMethodNative(XposedBridge.java:458)
01-07 09:26:14.344  1670  1670 E EdXposed: 	at de.robv.android.xposed.XposedBridge.hookMethod(XposedBridge.java:235)
01-07 09:26:14.344  1670  1670 E EdXposed: 	at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:187)
01-07 09:26:14.344  1670  1670 E EdXposed: 	at com.elderdrivers.riru.edxp._hooker.impl.LoadedApkCstr.afterHookedMethod(LoadedApkCstr.java:64)
01-07 09:26:14.344  1670  1670 E EdXposed: 	at de.robv.android.xposed.XC_MethodHook.callAfterHookedMethod(XC_MethodHook.java:68)
01-07 09:26:14.344  1670  1670 E EdXposed: 	at com.elderdrivers.riru.edxp._hooker.yahfa.LoadedApkConstructorHooker.hook(LoadedApkConstructorHooker.java:35)
01-07 09:26:14.344  1670  1670 E EdXposed: 	at android.app.ActivityThread.getPackageInfo(ActivityThread.java:2343)
01-07 09:26:14.344  1670  1670 E EdXposed: 	at android.app.ActivityThread.getPackageInfo(ActivityThread.java:2286)
01-07 09:26:14.344  1670  1670 E EdXposed: 	at android.app.ActivityThread.getPackageInfo(ActivityThread.java:2257)
01-07 09:26:14.344  1670  1670 E EdXposed: 	at android.app.ContextImpl.createPackageContextAsUser(ContextImpl.java:2195)
01-07 09:26:14.344  1670  1670 E EdXposed: 	at android.app.ContextImpl.createPackageContext(ContextImpl.java:2182)
01-07 09:26:14.344  1670  1670 E EdXposed: 	at android.content.ContextWrapper.createPackageContext(ContextWrapper.java:886)
01-07 09:26:14.344  1670  1670 E EdXposed: 	at android.app.ActivityThread.installProvider(ActivityThread.java:7106)
01-07 09:26:14.344  1670  1670 E EdXposed: 	at android.app.ActivityThread.installContentProviders(ActivityThread.java:6630)
01-07 09:26:14.344  1670  1670 E EdXposed: 	at android.app.ActivityThread.installSystemProviders(ActivityThread.java:7333)
01-07 09:26:14.344  1670  1670 E EdXposed: 	at com.android.server.am.ActivityManagerService.installSystemProviders(ActivityManagerService.java:7799)
01-07 09:26:14.344  1670  1670 E EdXposed: 	at com.android.server.SystemServer.startOtherServices(SystemServer.java:1009)
01-07 09:26:14.344  1670  1670 E EdXposed: 	at com.android.server.SystemServer.run(SystemServer.java:525)
01-07 09:26:14.344  1670  1670 E EdXposed: 	at com.android.server.SystemServer.main(SystemServer.java:362)
01-07 09:26:14.344  1670  1670 E EdXposed: 	at java.lang.reflect.Method.invoke(Native Method)
01-07 09:26:14.344  1670  1670 E EdXposed: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
01-07 09:26:14.344  1670  1670 E EdXposed: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:928)
01-07 09:26:21.558   732   732 E EdXposed-Bridge: Cannot load any modules because /data/user_de/0/org.meowcat.edxposed.manager/conf/modules.list was not found
```

**Comment by MlgmXyysd** [comment]
4491兼容旧版(20.2以下)面具之后会出现随机设备的sepolicy未正常加载的问题

**Comment by MlgmXyysd** [comment]
@MlgmXyysd 更新20.2可解决
