### ISSUE TITLE
[BUG] 短信相关模块不工作

### ISSUE THREAD

**Issue by Greyh4t** [ElderDrivers/EdXposed#420]
**什么情况/What happened?**
pixel4 手机，android 10，升级12月的安全OTA后，短信Hook相关的模块都无法工作，看日志发现找不到hook短信的方法，OTA之前是能工作的，目前测试了下面两个模块都报同样的错误
https://github.com/apsun/NekoSMS
https://github.com/tianma8023/XposedSmsCode

**Xposed模块列表/Xposed Module List**
Fingerface
NekoSMS
![Screenshot_20191229-222012](https://user-images.githubusercontent.com/8017380/71558222-b1cc5300-2a8b-11ea-8f07-ca4abf8696b2.png)
![Screenshot_20191229-222017](https://user-images.githubusercontent.com/8017380/71558223-b42ead00-2a8b-11ea-985a-3f6445593ffa.png)

**Magisk模块列表/Magisk Module List**
EnablePixel4VolteForCU
EnableSoli
Riru - Core
Riru -EdXposed
Riru - Location Report Enabler
Riru - Storage Redirect(Enhanced mode)
Systemless Hosts
![Screenshot_20191229-221954](https://user-images.githubusercontent.com/8017380/71558231-c0b30580-2a8b-11ea-972b-0c3d369197dc.png)
![Screenshot_20191229-222003](https://user-images.githubusercontent.com/8017380/71558234-c3155f80-2a8b-11ea-9ae3-abd897c0cddb.png)

**EdXposed及Riru版本/Versions of EdXposed and Riru**

EdXposed: Riru -EdXposed v0.4.5.5_beta(4470)(YAHFA)
Riru: Riru - Core v19.5

**相关Logcat/Logcat**
--------- beginning of head
EdXposed Log
Powered by Log Catcher
QQ chat group 855219808
--------- beginning of system info
Android version: 10
Android sdk: 29
Android build: QQ1C.191205.016.A1
Fingerprint: google/flame/flame:10/QQ1C.191205.016.A1/6015682:user/release-keys
ROM build description: flame-user 10 QQ1C.191205.016.A1 6015682 release-keys
EdXposed Version: v0.4.5.5_beta(4470) (Yahfa)
Architecture: arm64-v8a
Device: flame
Manufacture: Google
Brand: google
Product: flame
--------- beginning of system
--------- beginning of main
12-29 22:27:36.190  1707  1707 I EdXposed: onModuleLoaded: welcome to EdXposed!
12-29 22:27:36.190  1707  1707 I EdXposed: Start to install inline hooks
12-29 22:27:36.190  1707  1707 I EdXposed: Using api level 29
12-29 22:27:36.190  1707  1707 I EdXposed: Start to install Riru hook
12-29 22:27:36.197  1708  1708 I EdXposed: onModuleLoaded: welcome to EdXposed!
12-29 22:27:36.197  1708  1708 I EdXposed: Start to install inline hooks
12-29 22:27:36.197  1708  1708 I EdXposed: Using api level 29
12-29 22:27:36.197  1708  1708 I EdXposed: Start to install Riru hook
12-29 22:27:36.197  1707  1707 I EdXposed: Riru hooks installed
12-29 22:27:36.206  1708  1708 I EdXposed: Riru hooks installed
12-29 22:27:36.207  1707  1707 I EdXposed: ART hooks installed
12-29 22:27:36.207  1707  1707 I EdXposed: system_property_get: dalvik.vm.dex2oat-filter -> quicken
12-29 22:27:36.207  1707  1707 I EdXposed: system_property_get: dalvik.vm.dex2oat-flags -> --inline-max-code-units=0
12-29 22:27:36.212  1708  1708 I EdXposed: ART hooks installed
12-29 22:27:36.212  1708  1708 I EdXposed: system_property_get: dalvik.vm.dex2oat-filter -> quicken
12-29 22:27:36.212  1708  1708 I EdXposed: system_property_get: dalvik.vm.dex2oat-flags -> --inline-max-code-units=0
12-29 22:27:36.240  1707  1707 I EdXposed: using installer org.meowcat.edxposed.manager
12-29 22:27:36.241  1708  1708 I EdXposed: using installer org.meowcat.edxposed.manager
12-29 22:27:36.242  1708  1708 I EdXposed: black/white list mode: true, using whitelist: false
12-29 22:27:36.242  1708  1708 I EdXposed: dynamic modules mode: false
12-29 22:27:36.242  1708  1708 I EdXposed: resources hook: true
12-29 22:27:36.242  1708  1708 I EdXposed: deopt boot image: false
12-29 22:27:36.242  1707  1707 I EdXposed: black/white list mode: true, using whitelist: false
12-29 22:27:36.242  1707  1707 I EdXposed: dynamic modules mode: false
12-29 22:27:36.242  1707  1707 I EdXposed: resources hook: true
12-29 22:27:36.242  1707  1707 I EdXposed: deopt boot image: false
12-29 22:27:36.243  1707  1707 I EdXposed: blacklist: com.google.android.gsf
12-29 22:27:36.243  1707  1707 I EdXposed: blacklist: com.google.android.gms
12-29 22:27:36.243  1707  1707 I EdXposed: blacklist: com.android.vending
12-29 22:27:36.243  1707  1707 I EdXposed: blacklist: com.google.android.apps.walletnfcrel
12-29 22:27:36.243  1708  1708 I EdXposed: blacklist: com.google.android.gsf
12-29 22:27:36.243  1708  1708 I EdXposed: blacklist: com.google.android.gms
12-29 22:27:36.243  1708  1708 I EdXposed: blacklist: com.android.vending
12-29 22:27:36.243  1708  1708 I EdXposed: blacklist: com.google.android.apps.walletnfcrel
12-29 22:27:36.625  1707  1707 I EdXposed-Bridge: Loading modules from /data/app/com.crossbowffs.nekosms-mDW4JU1erTvFnhMW8NBxGg==/base.apk
12-29 22:27:36.686  1707  1707 I EdXposed-Bridge:   Loading class com.crossbowffs.nekosms.xposed.SmsHandlerHook
12-29 22:27:36.687  1707  1707 I EdXposed-Bridge:   Loading class com.crossbowffs.nekosms.xposed.XposedUtilsHook
12-29 22:27:36.688  1707  1707 I EdXposed-Bridge: Loading modules from /data/app/com.edison.fingerface-7gNYWM_iae9nxw-eGJ7tWg==/base.apk
12-29 22:27:36.694  1707  1707 I EdXposed-Bridge:   Loading class com.edison.fingerface.XposedHandler
12-29 22:27:39.461  2235  2235 E EdXposed: can't access config path, using snapshot use_white_list: /data/user_de/0/vendor.qti.hardware.cacert.server
12-29 22:27:39.461  2235  2235 E EdXposed: can't access config path, using snapshot black list: /data/user_de/0/vendor.qti.hardware.cacert.server
12-29 22:27:40.143  2291  2291 E EdXposed-Bridge: java.lang.NoSuchMethodError: com.android.internal.telephony.InboundSmsHandler#dispatchIntent(android.content.Intent,java.lang.String,int,android.os.Bundle,android.content.BroadcastReceiver,android.os.UserHandle)#exact
12-29 22:27:40.143  2291  2291 E EdXposed-Bridge: 	at de.robv.android.xposed.XposedHelpers.findMethodExact(XposedHelpers.java:344)
12-29 22:27:40.143  2291  2291 E EdXposed-Bridge: 	at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:185)
12-29 22:27:40.143  2291  2291 E EdXposed-Bridge: 	at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:260)
12-29 22:27:40.143  2291  2291 E EdXposed-Bridge: 	at com.crossbowffs.nekosms.xposed.SmsHandlerHook.hookDispatchIntent23(SmsHandlerHook.java:290)
12-29 22:27:40.143  2291  2291 E EdXposed-Bridge: 	at com.crossbowffs.nekosms.xposed.SmsHandlerHook.hookDispatchIntent(SmsHandlerHook.java:310)
12-29 22:27:40.143  2291  2291 E EdXposed-Bridge: 	at com.crossbowffs.nekosms.xposed.SmsHandlerHook.hookSmsHandler(SmsHandlerHook.java:320)
12-29 22:27:40.143  2291  2291 E EdXposed-Bridge: 	at com.crossbowffs.nekosms.xposed.SmsHandlerHook.handleLoadPackage(SmsHandlerHook.java:337)
12-29 22:27:40.143  2291  2291 E EdXposed-Bridge: 	at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(IXposedHookLoadPackage.java:37)
12-29 22:27:40.143  2291  2291 E EdXposed-Bridge: 	at de.robv.android.xposed.callbacks.XC_LoadPackage.call(XC_LoadPackage.java:61)
12-29 22:27:40.143  2291  2291 E EdXposed-Bridge: 	at de.robv.android.xposed.callbacks.XCallback.callAll(XCallback.java:117)
12-29 22:27:40.143  2291  2291 E EdXposed-Bridge: 	at com.elderdrivers.riru.edxp._hooker.impl.LoadedApkGetCL.afterHookedMethod(LoadedApkGetCL.java:68)
12-29 22:27:40.143  2291  2291 E EdXposed-Bridge: 	at de.robv.android.xposed.XC_MethodHook.callAfterHookedMethod(XC_MethodHook.java:68)
12-29 22:27:40.143  2291  2291 E EdXposed-Bridge: 	at EdHooker_.hook(Unknown Source:130)
12-29 22:27:40.143  2291  2291 E EdXposed-Bridge: 	at android.app.LoadedApk.getResources(LoadedApk.java:1188)
12-29 22:27:40.143  2291  2291 E EdXposed-Bridge: 	at android.app.ContextImpl.createAppContext(ContextImpl.java:2462)
12-29 22:27:40.143  2291  2291 E EdXposed-Bridge: 	at android.app.ContextImpl.createAppContext(ContextImpl.java:2454)
12-29 22:27:40.143  2291  2291 E EdXposed-Bridge: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6343)
12-29 22:27:40.143  2291  2291 E EdXposed-Bridge: 	at com.elderdrivers.riru.edxp._hooker.yahfa.HandleBindAppHooker.hook(HandleBindAppHooker.java:21)
12-29 22:27:40.143  2291  2291 E EdXposed-Bridge: 	at android.app.ActivityThread.access$1300(ActivityThread.java:219)
12-29 22:27:40.143  2291  2291 E EdXposed-Bridge: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1859)
12-29 22:27:40.143  2291  2291 E EdXposed-Bridge: 	at android.os.Handler.dispatchMessage(Handler.java:107)
12-29 22:27:40.143  2291  2291 E EdXposed-Bridge: 	at android.os.Looper.loop(Looper.java:214)
12-29 22:27:40.143  2291  2291 E EdXposed-Bridge: 	at android.app.ActivityThread.main(ActivityThread.java:7356)
12-29 22:27:40.143  2291  2291 E EdXposed-Bridge: 	at java.lang.reflect.Method.invoke(Native Method)
12-29 22:27:40.143  2291  2291 E EdXposed-Bridge: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
12-29 22:27:40.143  2291  2291 E EdXposed-Bridge: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
--------- beginning of crash
12-29 22:27:52.967  3716  3716 E EdXposed: can't access config path, using snapshot use_white_list: /data/user/0/com.android.nfc
12-29 22:27:52.967  3716  3716 E EdXposed: can't access config path, using snapshot black list: /data/user/0/com.android.nfc
12-29 22:27:53.242  3785  3785 E EdXposed: can't access config path, using snapshot use_white_list: /data/user/0/com.google.SSRestartDetector
12-29 22:27:53.242  3785  3785 E EdXposed: can't access config path, using snapshot black list: /data/user/0/com.google.SSRestartDetector
12-29 22:27:59.156  5141  5141 E EdXposed: can't access config path, using snapshot use_white_list: /data/user_de/0/com.android.bluetooth
12-29 22:27:59.156  5141  5141 E EdXposed: can't access config path, using snapshot black list: /data/user_de/0/com.android.bluetooth
12-29 22:28:08.256  1708  1708 I EdXposed-Bridge: Loading modules from /data/app/com.crossbowffs.nekosms-mDW4JU1erTvFnhMW8NBxGg==/base.apk
12-29 22:28:08.389  1708  1708 I EdXposed-Bridge:   Loading class com.crossbowffs.nekosms.xposed.SmsHandlerHook
12-29 22:28:08.392  1708  1708 I EdXposed-Bridge:   Loading class com.crossbowffs.nekosms.xposed.XposedUtilsHook
12-29 22:28:08.392  1708  1708 I EdXposed-Bridge: Loading modules from /data/app/com.edison.fingerface-7gNYWM_iae9nxw-eGJ7tWg==/base.apk
12-29 22:28:08.400  1708  1708 I EdXposed-Bridge:   Loading class com.edison.fingerface.XposedHandler
12-29 22:28:23.171  7700  7700 E EdXposed: can't access config path, using snapshot use_white_list: /data/user/0/com.google.RilConfigService
12-29 22:28:23.171  7700  7700 E EdXposed: can't access config path, using snapshot black list: /data/user/0/com.google.RilConfigService
12-29 22:30:22.402 14578 14578 E EdXposed: niceName:com.android.chrome_zygote, procName:zygote, appDataDir is null, blacklisted!
12-29 22:31:12.881 16738 16738 E EdXposed: can't parse /data/system
12-29 22:31:28.639 17329 17329 E EdXposed: niceName:com.android.chrome_zygote, procName:zygote, appDataDir is null, blacklisted!

**Comment by Greyh4t** [comment]
找到问题了，看最新的android源码发现 InboundSmsHandler类中的dispatchIntent方法变了，最后多了一个int参数，导致找不到方法
