### ISSUE TITLE
[BUG] Phone finish the boot process witth a black blinking screen

### ISSUE THREAD

**Issue by trmdi** [ElderDrivers/EdXposed#427]
**What happened?**
Phone finishes the boot process with a black blinking screen. Only the status bar and the navigation bar appears (blink) on the screen. The other part is just black.
It could only boot properly after trying to reboot lots of times.

**Xposed Module List**
Just my simple self-made module. I would upload the code if you need.

**Magisk Module List**
EdXposed's required modules, Youtube Vance.

**EdXposed and Riru**
EdXposed: 0.4.5.1 (on Magisk download page)

Riru: on Magisk download page

**相关Logcat/Logcat**
[error-1970-11-14-13-15-37.log](https://github.com/ElderDrivers/EdXposed/files/4016865/error-1970-11-14-13-15-37.log)
[boot-1970-11-14-13-15-37.log](https://github.com/ElderDrivers/EdXposed/files/4016866/boot-1970-11-14-13-15-37.log)

**Comment by MlgmXyysd** [comment]
@trmdi Android version?

**Comment by trmdi** [comment]
> @trmdi Android version?

LineageOS 16 (Android 9)

**Comment by MlgmXyysd** [comment]
@trmdi edxp 0.4.5.1?

**Comment by trmdi** [comment]
> @trmdi edxp 0.4.5.1?

Yes, it also happens with the latest version.

**Comment by MlgmXyysd** [comment]
@trmdi ok, wait for logs

**Comment by trmdi** [comment]
> @trmdi ok, wait for logs

Could you please give me the guide to get the log?

**Comment by MlgmXyysd** [comment]
@trmdi magisk download Log Catcher, you may need create no-stop file manually(check the module's readme)

**Comment by trmdi** [comment]
> @trmdi magisk download Log Catcher, you may need create no-stop file manually(check the module's readme)

Thanks, I will upload it. Now I have to remove the framework module to boot my phone normally.

**Comment by trmdi** [comment]
@MlgmXyysd I added logcat in the first comment.

**Comment by 18712886438** [comment]
```
--------- beginning of crash
[ 01-03 00:42:27.471  1987: 2149 E/AndroidRuntime ]
*** FATAL EXCEPTION IN SYSTEM PROCESS: android.display
java.lang.RuntimeException: Failed to boot service org.lineageos.platform.internal.display.LiveDisplayService: onBootPhase threw an exception during phase 1000
	at com.android.server.SystemServiceManager.startBootPhase(SystemServiceManager.java:158)
	at com.android.server.am.ActivityManagerService.finishBooting(ActivityManagerService.java:8186)
	at com.android.server.am.ActivityManagerService.bootAnimationComplete(ActivityManagerService.java:8239)
	at com.android.server.wm.WindowManagerService.performEnableScreen(WindowManagerService.java:3495)
	at com.android.server.wm.WindowManagerService.access$1100(WindowManagerService.java:272)
	at com.android.server.wm.WindowManagerService$H.handleMessage(WindowManagerService.java:4975)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.os.HandlerThread.run(HandlerThread.java:65)
	at com.android.server.ServiceThread.run(ServiceThread.java:44)
Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object[] java.util.Collection.toArray()' on a null object reference
	at java.util.ArrayList.addAll(ArrayList.java:588)
	at org.lineageos.platform.internal.display.PictureAdjustmentController.<init>(PictureAdjustmentController.java:55)
	at org.lineageos.platform.internal.display.LiveDisplayService.onBootPhase(LiveDisplayService.java:168)
	at com.android.server.SystemServiceManager.startBootPhase(SystemServiceManager.java:155)
	... 9 more
```

seems problem was here

**Comment by trmdi** [comment]
When comparing logcat of a failed boot vs a successful one, I found this in the fail boot:

    [ 11-15 14:55:35.142   304:  304 W/Riru     ]
    no Riru found in zygote64 (pid=312), restart required

**Comment by MlgmXyysd** [comment]
@trmdi it seems riru is failed, check riru's issues?

**Comment by trmdi** [comment]
Ah, I've just found another one has the same issue like me: https://github.com/RikkaApps/Riru/issues/66

**Comment by trmdi** [comment]
@RikkaW
Not sure if this is a Riru issue or an EdXposed one, but when comparing logcat of a failed boot vs a successful one, I found this in the failed boot:

    [ 11-15 14:55:35.142   304:  304 W/Riru     ]
    no Riru found in zygote64 (pid=312), restart required

**Comment by trmdi** [comment]
The issue seems to not happen when I downgrade Magisk to 19.3. (MagiskManager: 7.3.4, Riru: 19.5, EdXposed: 0.4.5.1, EdXposedManager: 4.5.3)
Probably the latest version 20.2 of Magisk breaks something.

Do you want to test that? @fireclouu

**Comment by fireclouu** [comment]
@trmdi riru-core now works for me with v19.6 release, but edxposed seems the faulty one now, tried downgrading but issue still occurs

**Comment by trmdi** [comment]
> @trmdi riru-core now works for me with v19.6 release, but edxposed seems the faulty one now, tried downgrading but issue still occurs

Yeah, a new version of any package could breaks another one. If you want to have the phone runs properly, you should downgrade all packages to a point that all of them are compatible with others.

**Comment by kotori2** [comment]
Closed as stale
