### ISSUE TITLE
[BUG] system-ui crashes in libart.so

### ISSUE THREAD

**Issue by Olit2000** [ElderDrivers/EdXposed#432]
**什么情况/What happened?**

my System-UI crashed once again. 
The guys from GravityBox told me its EdXposed related (see [my issue at GB](https://github.com/GravityBox/GravityBox/issues/2044))
The crashes seem random. Usually after some seconds the lockscreen re-appears, sometimes the crash causes a soft-boot (but without boot-animation)

**Xposed模块列表/Xposed Module List**

 - de.Maxr1998.xposed.maxlock
 - tw.fatminmin.xposed.minminguard
 - eu.faircode.xlua
 - com.fifsource.android.noplaygames
 - net.darkion.uniformedtransitions
 - com.tremendo.unclutterig
 - de.defim.apk.howgivelolli
 - top.fols.aapp.eternalprocessxposed
 - kmod.xposed
 - com.ceco.pie.gravitybox
 - com.crossbowffs.noautoshortcut
 - com.mayulive.swiftkeyexi
 - com.hazemam.InstantScreenOff
 - tk.wasdennnoch.scoop
 - me.rapperskull.burnttoastrevived
 - com.marz.instaprefs

but it does not seem module, but core related

**Magisk模块列表/Magisk Module List**
 - BusyBox for Android NDK
 - Magisk Manager for Recovery Mode (mm)
 - Riru - Core
 - Riru - EdXposed

**EdXposed及Riru版本/Versions of EdXposed and Riru**
EdXposed: v0.4.5.1_beta Sandhook
Riru: v19.5

**相关Logcat/Logcat**
```
--------- beginning of system
--------- beginning of crash
01-01 11:41:24.039  9798  9798 F libc    : Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 9798 (ndroid.systemui), pid 9798 (ndroid.systemui)
01-01 11:41:24.209 32090 32090 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
01-01 11:41:24.212 32090 32090 F DEBUG   : LineageOS Version: '16.0-20191228-NIGHTLY-klte'
01-01 11:41:24.212 32090 32090 F DEBUG   : Build fingerprint: 'samsung/kltexx/klte:6.0.1/MMB29M/G900FXXU1CRH1:user/release-keys'
01-01 11:41:24.212 32090 32090 F DEBUG   : Revision: '14'
01-01 11:41:24.212 32090 32090 F DEBUG   : ABI: 'arm'
01-01 11:41:24.212 32090 32090 F DEBUG   : pid: 9798, tid: 9798, name: ndroid.systemui  >>> com.android.systemui <<<
01-01 11:41:24.212 32090 32090 F DEBUG   : signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
01-01 11:41:24.212 32090 32090 F DEBUG   : Abort message: 'object.cc:223] Invalid state during hashcode ForwardingAddress'
01-01 11:41:24.212 32090 32090 F DEBUG   :     r0  00000000  r1  00002646  r2  00000006  r3  00000008
01-01 11:41:24.212 32090 32090 F DEBUG   :     r4  00002646  r5  00002646  r6  bee1f95c  r7  0000010c
01-01 11:41:24.212 32090 32090 F DEBUG   :     r8  0000000b  r9  aff3c834  r10 00003039  r11 00000003
01-01 11:41:24.212 32090 32090 F DEBUG   :     ip  00000041  sp  bee1f948  lr  b2d6d125  pc  b2d64e4a
01-01 11:41:24.241 32090 32090 F DEBUG   : 
01-01 11:41:24.241 32090 32090 F DEBUG   : backtrace:
01-01 11:41:24.241 32090 32090 F DEBUG   :     #00 pc 0001ce4a  /system/lib/libc.so (abort+58)
01-01 11:41:24.241 32090 32090 F DEBUG   :     #01 pc 00357253  /system/lib/libart.so (offset 0x34b000) (art::Runtime::Abort(char const*)+950)
01-01 11:41:24.241 32090 32090 F DEBUG   :     #02 pc 000071c3  /system/lib/libbase.so (android::base::LogMessage::~LogMessage()+506)
01-01 11:41:24.241 32090 32090 F DEBUG   :     #03 pc 002ce051  /system/lib/libart.so (offset 0x2b6000) (art::mirror::Object::IdentityHashCode()+164)
01-01 11:41:24.241 32090 32090 F DEBUG   :     #04 pc 001060b1  /system/framework/arm/boot.oat (offset 0x106000) (java.lang.Object.identityHashCodeNative [DEDUPED]+112)
01-01 11:41:24.241 32090 32090 F DEBUG   :     #05 pc 00158a7d  /system/framework/arm/boot.oat (offset 0x106000) (java.lang.Object.hashCode+60)
01-01 11:41:24.241 32090 32090 F DEBUG   :     #06 pc 00038a9b  /data/dalvik-cache/arm/system@priv-app@SystemUI@SystemUI.apk@classes.dex (deleted) (offset 0xac000)
--------- beginning of main
01-01 11:46:53.731 32125 32376 F libc    : Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 32376 (InflaterThread ), pid 32125 (ndroid.systemui)
01-01 11:46:54.490  3002  3002 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
01-01 11:46:54.490  3002  3002 F DEBUG   : LineageOS Version: '16.0-20191228-NIGHTLY-klte'
01-01 11:46:54.490  3002  3002 F DEBUG   : Build fingerprint: 'samsung/kltexx/klte:6.0.1/MMB29M/G900FXXU1CRH1:user/release-keys'
01-01 11:46:54.490  3002  3002 F DEBUG   : Revision: '14'
01-01 11:46:54.490  3002  3002 F DEBUG   : ABI: 'arm'
01-01 11:46:54.490  3002  3002 F DEBUG   : pid: 32125, tid: 32376, name: InflaterThread  >>> com.android.systemui <<<
01-01 11:46:54.490  3002  3002 F DEBUG   : signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
01-01 11:46:54.491  3002  3002 F DEBUG   : Abort message: 'monitor.cc:1120] Invalid monitor state ForwardingAddress'
01-01 11:46:54.491  3002  3002 F DEBUG   :     r0  00000000  r1  00007e78  r2  00000006  r3  00000008
01-01 11:46:54.491  3002  3002 F DEBUG   :     r4  00007d7d  r5  00007e78  r6  893399f4  r7  0000010c
01-01 11:46:54.491  3002  3002 F DEBUG   :     r8  0000000b  r9  00000000  r10 cfffffff  r11 aff3c8a8
01-01 11:46:54.491  3002  3002 F DEBUG   :     ip  00000041  sp  893399e0  lr  b2d6d125  pc  b2d64e4a
01-01 11:46:54.861  3002  3002 F DEBUG   : 
01-01 11:46:54.861  3002  3002 F DEBUG   : backtrace:
01-01 11:46:54.861  3002  3002 F DEBUG   :     #00 pc 0001ce4a  /system/lib/libc.so (abort+58)
01-01 11:46:54.861  3002  3002 F DEBUG   :     #01 pc 00357253  /system/lib/libart.so (offset 0x34b000) (art::Runtime::Abort(char const*)+950)
01-01 11:46:54.861  3002  3002 F DEBUG   :     #02 pc 000071c3  /system/lib/libbase.so (android::base::LogMessage::~LogMessage()+506)
01-01 11:46:54.861  3002  3002 F DEBUG   :     #03 pc 002dec9d  /system/lib/libart.so (offset 0x2b6000) (art::Monitor::MonitorEnter(art::Thread*, art::mirror::Object*, bool)+532)
01-01 11:46:54.861  3002  3002 F DEBUG   :     #04 pc 003df413  /system/lib/libart.so (offset 0x34c000) (artLockObjectFromCode+14)
01-01 11:46:54.861  3002  3002 F DEBUG   :     #05 pc 004182f7  /system/lib/libart.so (offset 0x34c000) (art_quick_lock_object+102)
01-01 11:46:54.862  3002  3002 F DEBUG   :     #06 pc 00aeb635  /system/framework/arm/boot-framework.oat (offset 0x383000) (android.util.Pools$SynchronizedPool.release+52)
01-01 11:46:54.862  3002  3002 F DEBUG   :     #07 pc 006b8a01  /system/framework/arm/boot-framework.oat (offset 0x383000) (android.content.res.TypedArray.recycle+96)
01-01 11:46:54.862  3002  3002 F DEBUG   :     #08 pc 00b0e611  /system/framework/arm/boot-framework.oat (offset 0x383000) (android.view.ViewStub.<init>+192)
01-01 11:46:54.862  3002  3002 F DEBUG   :     #09 pc 00b0e525  /system/framework/arm/boot-framework.oat (offset 0x383000) (android.view.ViewStub.<init>+60)
01-01 11:46:54.862  3002  3002 F DEBUG   :     #10 pc 00418175  /system/lib/libart.so (offset 0x34c000) (art_quick_invoke_stub_internal+68)
01-01 11:46:54.862  3002  3002 F DEBUG   :     #11 pc 003f16e5  /system/lib/libart.so (offset 0x34c000) (art_quick_invoke_stub+224)
01-01 11:46:54.862  3002  3002 F DEBUG   :     #12 pc 000a100d  /system/lib/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+136)
01-01 11:46:54.862  3002  3002 F DEBUG   :     #13 pc 00351131  /system/lib/libart.so (offset 0x2b6000) (art::(anonymous namespace)::InvokeWithArgArray(art::ScopedObjectAccessAlreadyRunnable const&, art::ArtMethod*, art::(anonymous namespace)::ArgArray*, art::JValue*, char const*)+52)
01-01 11:46:54.862  3002  3002 F DEBUG   :     #14 pc 00352583  /system/lib/libart.so (offset 0x2b6000) (art::InvokeMethod(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jobject*, _jobject*, unsigned int)+962)
01-01 11:46:54.862  3002  3002 F DEBUG   :     #15 pc 002fa21d  /system/lib/libart.so (offset 0x2b6000) (art::Constructor_newInstance0(_JNIEnv*, _jobject*, _jobjectArray*)+368)
01-01 11:46:54.862  3002  3002 F DEBUG   :     #16 pc 0010aee5  /system/framework/arm/boot.oat (offset 0x106000) (java.lang.String.concat [DEDUPED]+92)
01-01 11:46:54.862  3002  3002 F DEBUG   :     #17 pc 0032e1f9  /system/framework/arm/boot.oat (offset 0x106000) (java.lang.reflect.Constructor.newInstance+64)
01-01 11:46:54.862  3002  3002 F DEBUG   :     #18 pc 0099df1f  /system/framework/arm/boot-framework.oat (offset 0x383000) (android.view.LayoutInflater.createView+1494)
01-01 11:46:54.862  3002  3002 F DEBUG   :     #19 pc 00aba7d1  /system/framework/arm/boot-framework.oat (offset 0x383000) (com.android.internal.policy.PhoneLayoutInflater.onCreateView+120)
01-01 11:46:54.862  3002  3002 F DEBUG   :     #20 pc 0099f61d  /system/framework/arm/boot-framework.oat (offset 0x383000) (android.view.LayoutInflater.onCreateView+44)
01-01 11:46:54.862  3002  3002 F DEBUG   :     #21 pc 0099e7ed  /system/framework/arm/boot-framework.oat (offset 0x383000) (android.view.LayoutInflater.createViewFromTag+644)
01-01 11:46:54.862  3002  3002 F DEBUG   :     #22 pc 0099d569  /system/framework/arm/boot-framework.oat (offset 0x383000) (android.view.LayoutInflater.parseInclude+952)
01-01 11:46:54.862  3002  3002 F DEBUG   :     #23 pc 00418175  /system/lib/libart.so (offset 0x34c000) (art_quick_invoke_stub_internal+68)
01-01 11:46:54.862  3002  3002 F DEBUG   :     #24 pc 003f16e5  /system/lib/libart.so (offset 0x34c000) (art_quick_invoke_stub+224)
01-01 11:46:54.862  3002  3002 F DEBUG   :     #25 pc 000a100d  /system/lib/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+136)
01-01 11:46:54.863  3002  3002 F DEBUG   :     #26 pc 00351131  /system/lib/libart.so (offset 0x2b6000) (art::(anonymous namespace)::InvokeWithArgArray(art::ScopedObjectAccessAlreadyRunnable const&, art::ArtMethod*, art::(anonymous namespace)::ArgArray*, art::JValue*, char const*)+52)
01-01 11:46:54.863  3002  3002 F DEBUG   :     #27 pc 00352583  /system/lib/libart.so (offset 0x2b6000) (art::InvokeMethod(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jobject*, _jobject*, unsigned int)+962)
01-01 11:46:54.863  3002  3002 F DEBUG   :     #28 pc 00303251  /system/lib/libart.so (offset 0x2b6000) (art::Method_invoke(_JNIEnv*, _jobject*, _jobject*, _jobjectArray*)+40)
01-01 11:46:54.863  3002  3002 F DEBUG   :     #29 pc 0010c1f7  /system/framework/arm/boot.oat (offset 0x106000) (java.lang.Class.getDeclaredMethodInternal [DEDUPED]+110)
01-01 11:46:54.863  3002  3002 F DEBUG   :     #30 pc 0000a2e7  /dev/ashmem/dalvik-jit-code-cache (deleted)
01-01 11:46:57.064  3032  3032 F ndroid.systemu: runtime.cc:558]   | group="" sCount=1 dsCount=0 flags=1 obj=0x13880020 self=0xaa1af800
01-01 11:46:57.064  3032  3032 F ndroid.systemu: runtime.cc:558]   | sysTid=3056 nice=0 cgrp=default sched=0/0 handle=0x95a37970
01-01 11:46:57.064  3032  3032 F ndroid.systemu: runtime.cc:558]   | state=S schedstat=( 546303 2937239 4 ) utm=0 stm=0 core=2 HZ=100
01-01 11:46:57.064  3032  3032 F ndroid.systemu: runtime.cc:558]   | stack=0x9593c000-0x9593e000 stackSize=1010KB
01-01 11:46:57.064  3032  3032 F ndroid.systemu: runtime.cc:558]   | held mutexes=
01-01 11:46:57.064  3032  3032 F ndroid.systemu: runtime.cc:558]   native: #00 pc 00054d10  /system/lib/libc.so (__ioctl+8)
01-01 11:46:57.064  3032  3032 F ndroid.systemu: runtime.cc:558]   native: #01 pc 00021c4b  /system/lib/libc.so (ioctl+38)
01-01 11:46:57.064  3032  3032 F ndroid.systemu: runtime.cc:558]   native: #02 pc 0003d49b  /system/lib/libbinder.so (android::IPCThreadState::talkWithDriver(bool)+206)
01-01 11:46:57.064  3032  3032 F ndroid.systemu: runtime.cc:558]   native: #03 pc 0003d5eb  /system/lib/libbinder.so (android::IPCThreadState::getAndExecuteCommand()+10)
01-01 11:46:57.064  3032  3032 F ndroid.systemu: runtime.cc:558]   native: #04 pc 0003db73  /system/lib/libbinder.so (android::IPCThreadState::joinThreadPool(bool)+38)
01-01 11:46:57.064  3032  3032 F ndroid.systemu: runtime.cc:558]   native: #05 pc 0005466d  /system/lib/libbinder.so (android::PoolThread::threadLoop()+12)
01-01 11:46:57.064  3032  3032 F ndroid.systemu: runtime.cc:558]   native: #06 pc 0000c0b7  /system/lib/libutils.so (android::Thread::_threadLoop(void*)+170)
01-01 11:46:57.064  3032  3032 F ndroid.systemu: runtime.cc:558]   native: #07 pc 0006f1f3  /system/lib/libandroid_runtime.so (android::AndroidRuntime::javaThreadShell(void*)+82)
01-01 11:46:57.064  3032  3032 F ndroid.systemu: runtime.cc:558]   native: #08 pc 00064ac3  /system/lib/libc.so (__pthread_start(void*)+22)
01-01 11:46:57.064  3032  3032 F ndroid.systemu: runtime.cc:558]   native: #09 pc 0001e061  /system/lib/libc.so (__start_thread+32)
01-01 11:46:57.064  3032  3032 F ndroid.systemu: runtime.cc:558]   (no managed stack frames)
01-01 11:46:57.064  3032  3032 F ndroid.systemu: runtime.cc:558] 
01-01 11:46:57.064  3032  3032 F ndroid.systemu: runtime.cc:558] "Profile Saver" prio=5 tid=11 Native
01-01 11:46:57.064  3032  3032 F ndroid.systemu: runtime.cc:558]   | group="" sCount=1 dsCount=0 flags=1 obj=0x13900020 self=0xa8711400
01-01 11:46:57.064  3032  3032 F ndroid.systemu: runtime.cc:558]   | sysTid=3058 nice=9 cgrp=default sched=0/0 handle=0x95939970
01-01 11:46:57.064  3032  3032 F ndroid.systemu: runtime.cc:558]   | state=S schedstat=( 624792 5105572 2 ) utm=0 stm=0 core=3 HZ=100
01-01 11:46:57.064  3032  3032 F ndroid.systemu: runtime.cc:558]   | stack=0x9583e000-0x95840000 stackSize=1010KB
01-01 11:46:57.064  3032  3032 F ndroid.systemu: runtime.cc:558]   | held mutexes=
01-01 11:46:57.064  3032  3032 F ndroid.systemu: runtime.cc:558]   native: #00 pc 00019e2c  /system/lib/libc.so (syscall+32)
01-01 11:46:57.064  3032  3032 F ndroid.systemu: runtime.cc:558]   native: #01 pc 000a6fbb  /system/lib/libart.so (art::ConditionVariable::TimedWait(art::Thread*, long long, int)+106)
01-01 11:46:57.064  3032  3032 F ndroid.systemu: runtime.cc:558]   native: #02 pc 0026199f  /system/lib/libart.so (offset 1a6000) (art::ProfileSaver::Run()+142)
01-01 11:46:57.064  3032  3032 F ndroid.systemu: runtime.cc:558]   native: #03 pc 002643b9  /system/lib/libart.so (offset 1a6000) (art::ProfileSaver::RunProfileSaverThread(void*)+52)
01-01 11:46:57.064  3032  3032 F ndroid.systemu: runtime.cc:558]   native: #04 pc 00064ac3  /system/lib/libc.so (__pthread_start(void*)+22)
01-01 11:46:57.064  3032  3032 F ndroid.systemu: runtime.cc:558]   native: #05 pc 0001e061  /system/lib/libc.so (__start_thread+32)
01-01 11:46:57.064  3032  3032 F ndroid.systemu: runtime.cc:558]   (no managed stack frames)
01-01 11:46:57.064  3032  3032 F ndroid.systemu: runtime.cc:558] 
01-01 11:46:57.064  3032  3032 F ndroid.systemu: runtime.cc:558] Aborting thread:
01-01 11:46:57.064  3032  3032 F ndroid.systemu: runtime.cc:558] "main" prio=5 tid=1 Runnable
01-01 11:46:57.064  3032  3032 F ndroid.systemu: runtime.cc:558]   | group="" sCount=1 dsCount=0 flags=9 obj=0x73feb1f0 self=0xb0099000
01-01 11:46:57.064  3032  3032 F ndroid.systemu: runtime.cc:558]   | sysTid=3032 nice=0 cgrp=default sched=0/0 handle=0xb3e39494
01-01 11:46:57.064  3032  3032 F ndroid.systemu: runtime.cc:558]   | state=R schedstat=( 783517291 155727919 543 ) utm=57 stm=20 core=2 HZ=100
01-01 11:46:57.064  3032  3032 F ndroid.systemu: runtime.cc:558]   | stack=0xbe623000-0xbe625000 stackSize=8MB
01-01 11:46:57.064  3032  3032 F ndroid.systemu: runtime.cc:558]   | held mutexes= "abort lock" "mutator lock"(shared held)
01-01 11:46:57.064  3032  3032 F ndroid.systemu: runtime.cc:558]   native: #00 pc 002e1263  /system/lib/libart.so (offset 2b6000) (art::DumpNativeStack(std::__1::basic_ostream<char, std::__1::char_traits<char>>&, int, BacktraceMap*, char const*, art::ArtMethod*, void*, bool)+134)
01-01 11:46:57.064  3032  3032 F ndroid.systemu: runtime.cc:558]   native: #01 pc 00378bf9  /system/lib/libart.so (offset 34c000) (art::Thread::DumpStack(std::__1::basic_ostream<char, std::__1::char_traits<char>>&, bool, BacktraceMap*, bool) const+212)
01-01 11:46:57.064  3032  3032 F ndroid.systemu: runtime.cc:558]   native: #02 pc 00375207  /system/lib/libart.so (offset 34c000) (art::Thread::Dump(std::__1::basic_ostream<char, std::__1::char_traits<char>>&, bool, BacktraceMap*, bool) const+34)
01-01 11:46:57.064  3032  3032 F ndroid.systemu: runtime.cc:558]   native: #03 pc 0036324f  /system/lib/libart.so (offset 34c000) (art::AbortState::DumpThread(std::__1::basic_ostream<char, std::__1::char_traits<char>>&, art::Thread*) const+30)
01-01 11:46:57.064  3032  3032 F ndroid.systemu: runtime.cc:558]   native: #04 pc 0035725b  /system/lib/libart.so (offset 34b000) (art::Runtime::Abort(char const*)+958)
01-01 11:46:57.064  3032  3032 F ndroid.systemu: runtime.cc:558]   native: #05 pc 000071c3  /system/lib/libbase.so (android::base::LogMessage::~LogMessage()+506)
01-01 11:46:57.064  3032  3032 F ndroid.systemu: runtime.cc:558]   native: #06 pc 003dedf5  /system/lib/libart.so (offset 34c000) (_ZN3artL12GoToRunnableEPNS_6ThreadE.llvm.176016913+264)
01-01 11:46:57.064  3032  3032 F ndroid.systemu: runtime.cc:558]   native: #07 pc 003decc5  /system/lib/libart.so (offset 34c000) (art::JniMethodEnd(unsigned int, art::Thread*)+8)
01-01 11:46:57.065  3032  3032 F ndroid.systemu: runtime.cc:558]   native: #08 pc 00003bdd  /data/dalvik-cache/arm/system@framework@edxp.jar@classes.dex (offset 3000) (Java_com_swift_sandhook_SandHook_hookMethod__Ljava_lang_reflect_Member_2Ljava_lang_reflect_Method_2Ljava_lang_reflect_Method_2I+180)
01-01 11:46:57.065  3032  3032 F ndroid.systemu: runtime.cc:558]   at com.swift.sandhook.SandHook.hookMethod(Native method)
01-01 11:46:57.065  3032  3032 F ndroid.systemu: runtime.cc:558]   at com.swift.sandhook.SandHook.hook(SandHook.java:114)
01-01 11:46:57.065  3032  3032 F ndroid.systemu: runtime.cc:558]   - locked <0x0c3a538d> (a java.lang.Class<com.swift.sandhook.SandHook>)
01-01 11:46:57.065  3032  3032 F ndroid.systemu: runtime.cc:558]   at com.swift.sandhook.xposedcompat.methodgen.SandHookXposedBridge.hookMethod(SandHookXposedBridge.java:70)
01-01 11:46:57.065  3032  3032 F ndroid.systemu: runtime.cc:558]   - locked <0x0658b942> (a java.lang.Class<com.swift.sandhook.xposedcompat.methodgen.SandHookXposedBridge>)
01-01 11:46:57.065  3032  3032 F ndroid.systemu: runtime.cc:558]   at com.swift.sandhook.xposedcompat.XposedCompat.hookMethod(XposedCompat.java:64)
01-01 11:46:57.065  3032  3032 F ndroid.systemu: runtime.cc:558]   - locked <0x07452d53> (a java.lang.Class<com.swift.sandhook.xposedcompat.XposedCompat>)
01-01 11:46:57.065  3032  3032 F ndroid.systemu: runtime.cc:558]   at com.elderdrivers.riru.edxp.sandhook.config.SandHookProvider.hookMethod(SandHookProvider.java:28)
01-01 11:46:57.065  3032  3032 F ndroid.systemu: runtime.cc:558]   at de.robv.android.xposed.XposedBridge.hookMethodNative(XposedBridge.java:461)
01-01 11:46:57.065  3032  3032 F ndroid.systemu: runtime.cc:558]   - locked <0x0d75c690> (a java.lang.Class<de.robv.android.xposed.XposedBridge>)
01-01 11:46:57.065  3032  3032 F ndroid.systemu: runtime.cc:558]   at de.robv.android.xposed.XposedBridge.hookMethod(XposedBridge.java:238)
01-01 11:46:57.065  3032  3032 F ndroid.systemu: runtime.cc:558]   at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:187)
01-01 11:46:57.065  3032  3032 F ndroid.systemu: runtime.cc:558]   at com.ceco.pie.gravitybox.ModLockscreen.init(ModLockscreen.java:342)
01-01 11:46:57.065  3032  3032 F ndroid.systemu: runtime.cc:558]   at com.ceco.pie.gravitybox.GravityBox.handleLoadPackage(GravityBox.java:191)
01-01 11:46:57.065  3032  3032 F ndroid.systemu: runtime.cc:558]   at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(IXposedHookLoadPackage.java:37)
01-01 11:46:57.065  3032  3032 F ndroid.systemu: runtime.cc:558]   at de.robv.android.xposed.callbacks.XC_LoadPackage.call(XC_LoadPackage.java:61)
01-01 11:46:57.065  3032  3032 F ndroid.systemu: runtime.cc:558]   at de.robv.android.xposed.callbacks.XCallback.callAll(XCallback.java:117)
01-01 11:46:57.065  3032  3032 F ndroid.systemu: runtime.cc:558]   at com.elderdrivers.riru.edxp._hooker.impl.HandleBindApp.beforeHookedMethod(HandleBindApp.java:70)
01-01 11:46:57.065  3032  3032 F ndroid.systemu: runtime.cc:558]   at de.robv.android.xposed.XC_MethodHook.callBeforeHookedMethod(XC_MethodHook.java:51)
01-01 11:46:57.065  3032  3032 F ndroid.systemu: runtime.cc:558]   at com.swift.sandhook.xposedcompat.hookstub.HookStubManager.hookBridge(HookStubManager.java:276)
01-01 11:46:57.065  3032  3032 F ndroid.systemu: runtime.cc:558]   at com.swift.sandhook.xposedcompat.hookstub.MethodHookerStubs32.stub_hook_0(MethodHookerStubs32.java:198)
01-01 11:46:57.065  3032  3032 F ndroid.systemu: runtime.cc:558]   at android.app.ActivityThread.access$1100(ActivityThread.java:200)
01-01 11:46:57.065  3032  3032 F ndroid.systemu: runtime.cc:558]   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656)
01-01 11:46:57.065  3032  3032 F ndroid.systemu: runtime.cc:558]   at android.os.Handler.dispatchMessage(Handler.java:106)
01-01 11:46:57.065  3032  3032 F ndroid.systemu: runtime.cc:558]   at android.os.Looper.loop(Looper.java:193)
01-01 11:46:57.065  3032  3032 F ndroid.systemu: runtime.cc:558]   at android.app.ActivityThread.main(ActivityThread.java:6718)
01-01 11:46:57.065  3032  3032 F ndroid.systemu: runtime.cc:558]   at java.lang.reflect.Method.invoke(Native method)
01-01 11:46:57.065  3032  3032 F ndroid.systemu: runtime.cc:558]   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
01-01 11:46:57.065  3032  3032 F ndroid.systemu: runtime.cc:558]   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
01-01 11:46:57.065  3032  3032 F ndroid.systemu: runtime.cc:558] 
01-01 11:46:57.066  3032  3032 F libc    : Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 3032 (re-initialized>), pid 3032 (re-initialized>)
01-01 11:46:57.166  3063  3063 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
01-01 11:46:57.166  3063  3063 F DEBUG   : LineageOS Version: '16.0-20191228-NIGHTLY-klte'
01-01 11:46:57.166  3063  3063 F DEBUG   : Build fingerprint: 'samsung/kltexx/klte:6.0.1/MMB29M/G900FXXU1CRH1:user/release-keys'
01-01 11:46:57.166  3063  3063 F DEBUG   : Revision: '14'
01-01 11:46:57.166  3063  3063 F DEBUG   : ABI: 'arm'
01-01 11:46:57.166  3063  3063 F DEBUG   : pid: 3032, tid: 3032, name: re-initialized>  >>> <pre-initialized> <<<
01-01 11:46:57.166  3063  3063 F DEBUG   : signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
01-01 11:46:57.166  3063  3063 F DEBUG   : Abort message: 'thread-inl.h:267] Transitioning to runnable with checkpoint flag,  flags=2 state=67'
01-01 11:46:57.166  3063  3063 F DEBUG   :     r0  00000000  r1  00000bd8  r2  00000006  r3  00000008
01-01 11:46:57.166  3063  3063 F DEBUG   :     r4  00000bd8  r5  00000bd8  r6  bee1dee4  r7  0000010c
01-01 11:46:57.166  3063  3063 F DEBUG   :     r8  00000002  r9  bee1dfa0  r10 aff3b374  r11 afeebe48
01-01 11:46:57.166  3063  3063 F DEBUG   :     ip  00000041  sp  bee1ded0  lr  b2d6d125  pc  b2d64e4a
01-01 11:46:57.173  3063  3063 F DEBUG   : 
01-01 11:46:57.173  3063  3063 F DEBUG   : backtrace:
01-01 11:46:57.173  3063  3063 F DEBUG   :     #00 pc 0001ce4a  /system/lib/libc.so (abort+58)
01-01 11:46:57.173  3063  3063 F DEBUG   :     #01 pc 00357253  /system/lib/libart.so (offset 0x34b000) (art::Runtime::Abort(char const*)+950)
01-01 11:46:57.173  3063  3063 F DEBUG   :     #02 pc 000071c3  /system/lib/libbase.so (android::base::LogMessage::~LogMessage()+506)
01-01 11:46:57.173  3063  3063 F DEBUG   :     #03 pc 003dedf5  /system/lib/libart.so (offset 0x34c000) (_ZN3artL12GoToRunnableEPNS_6ThreadE.llvm.176016913+264)
01-01 11:46:57.173  3063  3063 F DEBUG   :     #04 pc 003decc5  /system/lib/libart.so (offset 0x34c000) (art::JniMethodEnd(unsigned int, art::Thread*)+8)
01-01 11:46:57.173  3063  3063 F DEBUG   :     #05 pc 00003bdd  /data/dalvik-cache/arm/system@framework@edxp.jar@classes.dex (offset 0x3000)
```

**Comment by MlgmXyysd** [comment]
i noticed u r running SandHook variant, try YAHFA and see again

**Comment by MlgmXyysd** [comment]
and....update to latest version(magisk 20.2, edxp 4491)

**Comment by drewcu** [comment]
Have the same issue as OP and was running SandHook on my LG V30 VS996 with Pie and Magisk 20.2.

Tried YAHFA 4492 and didn't experience any crashes, but also had very annoying LAG that I didn't have on SandHook. In my case, the lag wasn't worth the 1-2 crashes per week on SandHook so I am back on SandHook. 

Hopefully someone can figure out how to prevent these system-ui crashes with SandHook, thanks!

**Comment by Jasi2169** [comment]
The issue was there for me always on sandhook, yahfa is laggy on samsung stock roms on pie and android 10

I have been experiencing this from long , the random reboots, plz check build 4497 which says sandhook nullpointerexception fixed, i have not get any reboot yet with this build but old version had, plz verify i will report if i get

**Comment by Jasi2169** [comment]
More than 1 day no reboot yet with 4497 build

**Comment by Jasi2169** [comment]
no reboot i confirm build 4497 fix the samsung stock rom reboot/systemui issue

**Comment by Olit2000** [comment]
My phone doesn't even boot with that build (waited for 30 mins and then wiped system and reflashed, and went back to build 4463)

**Comment by KeetsScrimalittle1** [comment]
I'm on EdXposed 0.4.6.1, getting module list failed to load on 4.6.0, and Everytime I reboot with gravity box enabled my phone will reboot back to the splash screen before I unlock.  Usually happens a couple of times and I have to wait it out.  Doesn't occur with gravitybox module disabled.

**Comment by Olit2000** [comment]
I do now use EdXposed v0.4.6.1 build 4504 Sandhook (latest canary build) together with latest magisk canary build (20304) and the crashes went away. The EdXposed Manager detects EdXposed correctly again.
I hope the changes that solved the issue get released on the stable channel soon.

**Comment by YoYoJassie** [comment]
@MlgmXyysd this needs to be closed, i confirm issue os fixed since v4497 throughly tested.

**Comment by Olit2000** [comment]
This crashes went away but new came. I'll open a new issue for that if I know what causes these new crashes
