### ISSUE TITLE
[BUG]  'java.lang.Class java.lang.Object.getClass()' on a null object reference on Sandhook version

### ISSUE THREAD

**Issue by Firefds** [ElderDrivers/EdXposed#456]
**什么情况/What happened?**

On Samsung S8 with latest Android 9, when opening contacts app the app crashes.
This happens when using my Firefds Kit module with this code:
`try {
            XposedHelpers.findAndHookMethod(CSC_FEATURE_UTIL,
                    classLoader,
                    "getDisablePhoneNumberFormatting",
                    XC_MethodReplacement.returnConstant(prefs
                            .getBoolean(PREF_DISABLE_NUMBER_FORMATTING, false)));
        } catch (Throwable e) {
            XposedBridge.log(e);
        }`

The method the module is trying to hook to is:
`public static boolean getDisablePhoneNumberFormatting()
  {
    return sCscFeatureDataSource.h();
  }`

This crash only happens on EdXposed Sandhook version. When using YAHFA version this crash doesn't happen

**Xposed模块列表/Xposed Module List**

Firefds Kit [Pie]
Gravity Box [P]
NoAds For Youtube
YouTube Background Player

**Magisk模块列表/Magisk Module List**

Magisk 20.3
Magisk Manager 7.5.1

**EdXposed及Riru版本/Versions of EdXposed and Riru**

EdXposed:
0.4.5.1_beta Sandhook
Riru:
19.6

**相关Logcat/Logcat**
2020-01-31 23:25:27.661 14435-14458/? E/AndroidRuntime: FATAL EXCEPTION: RxSingleScheduler-1
    Process: com.samsung.android.contacts, PID: 14435
    a.a.c.h: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
        at a.a.e.d.h.a_(EmptyCompletableObserver.java:51)
        at a.a.e.e.a.v.a_(CompletableSubscribeOn.java:74)
        at a.a.e.e.a.l.b(CompletableFromAction.java:38)
        at a.a.b.a(Completable.java:1686)
        at a.a.e.e.a.v.run(CompletableSubscribeOn.java:64)
        at a.a.e.g.v.a(ScheduledDirectTask.java:38)
        at a.a.e.g.v.call(ScheduledDirectTask.java:26)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
        at com.samsung.android.dialtacts.util.c.c.a(AppLogDataSource.java:156)
        at com.samsung.android.dialtacts.util.c.c.k(AppLogDataSource.java:133)
        at com.samsung.android.dialtacts.util.b.k(AppLog.java:94)
        at com.samsung.android.dialtacts.model.internal.datasource.kr.k(TelephonyDataSource.java:310)
        at com.samsung.android.dialtacts.model.ak.a.b(SimModel.java:128)
        at com.samsung.android.contacts.ContactApplication.a(ContactApplication.java:75)
        at com.samsung.android.contacts.a.run(Unknown Source:2)
        at a.a.e.e.a.l.b(CompletableFromAction.java:34)
        at a.a.b.a(Completable.java:1686) 
        at a.a.e.e.a.v.run(CompletableSubscribeOn.java:64) 
        at a.a.e.g.v.a(ScheduledDirectTask.java:38) 
        at a.a.e.g.v.call(ScheduledDirectTask.java:26) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:764)

**Comment by MlgmXyysd** [comment]
@Firefds try to update to canary 4454, i fixed this npe bug

**Comment by Firefds** [comment]
@MlgmXyysd Using canary 45401 Sandhook - still an issue

**Comment by MlgmXyysd** [comment]
@Firefds not found getClass from code u provided

**Comment by MlgmXyysd** [comment]
@Firefds @ganyao114 see this

**Comment by Firefds** [comment]
@MlgmXyysd I provided the jar file of the apk that crashes.
[SamsungContacts-dex2jar.zip](https://github.com/ElderDrivers/EdXposed/files/4142548/SamsungContacts-dex2jar.zip)

**Comment by kotori2** [comment]
Closed as stale
