### ISSUE TITLE
[BUG] Caused by: java.lang.ClassNotFoundException: Didn't find class "de.robv.android.xposed.XposedHelpers"

### ISSUE THREAD

**Issue by Firefds** [ElderDrivers/EdXposed#463]
**什么情况/What happened?**

When importing de.robv.android.xposed.XposedHelpers or de.robv.android.xposed.XposedBridge into a class that isn't called under handleLoadPackage, Xposed classes aren't found.
I have tried both compileOnly and implementation of 'de.robv.android.xposed:api:82'.
There was no issue with this in some previous Ed Xposed version, at least on 4.1.2.

You can see source code of this class here - https://github.com/Firefds/FirefdsKit/blob/pie/firefdskit/src/main/java/sb/firefds/pie/firefdskit/utils/Utils.java

I'm using Samsung S8 on Android 9, but getting reports it doesn't work on Samsung Android 10 either.

**Magisk模块列表/Magisk Module List**

Magisk 20.3
Magisk Manager 7.5.1
Riru - Core v19.7
Riru - EdXposed v4.6.1_beta Sandhook

**EdXposed及Riru版本/Versions of EdXposed and Riru**

EdXposed: v4.6.1_beta Sandhook

Riru: v19.7

Manager: 4.5.4 (45401)

**相关Logcat/Logcat**
`2020-02-14 08:57:01.616 17061-17061/? E/FFK: java.lang.NoClassDefFoundError: Failed resolution of: Lde/robv/android/xposed/XposedHelpers;
        at sb.firefds.pie.firefdskit.utils.Utils.set(Utils.java:166)
        at sb.firefds.pie.firefdskit.utils.Utils.performQuickReboot(Utils.java:143)
        at sb.firefds.pie.firefdskit.activities.WanamRebootActivity.quickRebootDevice(WanamRebootActivity.java:70)
        at sb.firefds.pie.firefdskit.activities.WanamRebootActivity.onCreate(WanamRebootActivity.java:46)
        at android.app.Activity.performCreate(Activity.java:7327)
        at android.app.Activity.performCreate(Activity.java:7318)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3094)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3257)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1948)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7050)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "de.robv.android.xposed.XposedHelpers" on path: DexPathList[[zip file "/data/app/sb.firefds.pie.firefdskit-zxlbkfJUDX-DNIZSJIg_bg==/base.apk"],nativeLibraryDirectories=[/data/app/sb.firefds.pie.firefdskit-zxlbkfJUDX-DNIZSJIg_bg==/lib/arm64, /system/lib64, /system/vendor/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at sb.firefds.pie.firefdskit.utils.Utils.set(Utils.java:166) 
        at sb.firefds.pie.firefdskit.utils.Utils.performQuickReboot(Utils.java:143) 
        at sb.firefds.pie.firefdskit.activities.WanamRebootActivity.quickRebootDevice(WanamRebootActivity.java:70) 
        at sb.firefds.pie.firefdskit.activities.WanamRebootActivity.onCreate(WanamRebootActivity.java:46) 
        at android.app.Activity.performCreate(Activity.java:7327) 
        at android.app.Activity.performCreate(Activity.java:7318) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3094) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3257) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1948) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7050) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965) 
`

**Comment by Firefds** [comment]
Edit: Typo.. Happens on Ed Exposed 4.6.1

**Comment by kotori2** [comment]
https://github.com/Firefds/FirefdsKit/blob/pie/firefdskit/build.gradle#L47
change to `implementation` or `api`

**Comment by Firefds** [comment]
@kotori2 I already tried that. I get this error - 
`2020-02-16 16:59:51.457 28850-28850/? E/FFK: java.lang.RuntimeException: Stub!
        at de.robv.android.xposed.XposedHelpers.findClass(XposedHelpers.java:15)
        at sb.firefds.pie.firefdskit.utils.Utils.set(Utils.java:166)
        at sb.firefds.pie.firefdskit.utils.Utils.performQuickReboot(Utils.java:143)
        at sb.firefds.pie.firefdskit.activities.WanamRebootActivity.quickRebootDevice(WanamRebootActivity.java:70)
        at sb.firefds.pie.firefdskit.activities.WanamRebootActivity.onCreate(WanamRebootActivity.java:46)
        at android.app.Activity.performCreate(Activity.java:7327)
        at android.app.Activity.performCreate(Activity.java:7318)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3094)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3257)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1948)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7050)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)`

**Comment by kotori2** [comment]
looks like the framework jar is not loaded

**Comment by Firefds** [comment]
@MlgmXyysd @solohsu @ganyao114 still an issue on 0.4.6.3 (4545)

**Comment by activeliang** [comment]
> https://github.com/Firefds/FirefdsKit/blob/pie/firefdskit/build.gradle#L47
> change to `implementation` or `api`

change to `implementatioin` it works for me, thx~
