### ISSUE TITLE
[BUG] 无法在AVD上加载模块

### ISSUE THREAD

**Issue by Altonhe** [ElderDrivers/EdXposed#505]
**什么情况**

在安卓studio的官方模拟器上，无法加载模块

**Xposed模块列表**
Edxposed Manager
TrustmeaAlready

**Magisk模块列表/Magisk Module List**

Riru core
Riru EdXposed-YAHFA-v0.4.6.2.4529

**EdXposed及Riru版本/Versions of EdXposed and Riru**
```
EdXposed version: v0.4.6.2 (4529) (YAHFA)
EdXposed api: 91.0
Riru version: v19.8 (30)
Riru api: 4
Magisk: 20.4 (20400)
Android version: 10
Android sdk: 29
```
**相关Logcat/Logcat**

```
--------- beginning of head
EdXposed Log
Powered by Log Catcher
QQ support group: 855219808
Telegram support group: @Code_Of_MeowCat
Telegram channel: @EdXposed
--------- beginning of information
Manufacturer: Google
Brand: google
Device: generic_x86
Product: generic_x86
Model: Android SDK built for x86
Fingerprint: google/sdk_gphone_x86/generic_x86:10/QSR1.190920.001/5891938:user/release-keys
ROM description: sdk_gphone_x86-user 10 QSR1.190920.001 5891938 release-keys
Architecture: x86
Android build: QSR1.190920.001
Android version: 10
Android sdk: 29
EdXposed version: v0.4.6.2 (4529) (YAHFA)
EdXposed api: 91.0
Riru version: v19.8 (30)
Riru api: 4
Magisk: 20.4 (20400)
--------- beginning of main
--------- beginning of system
04-07 08:05:23.482  1851  1851 I EdXposed: onModuleLoaded: welcome to EdXposed!
04-07 08:05:23.482  1851  1851 I EdXposed: Start to install inline hooks
04-07 08:05:23.482  1851  1851 I EdXposed: Using api level 29
04-07 08:05:23.482  1851  1851 I EdXposed: Start to install Riru hook
04-07 08:05:23.499  1851  1851 I EdXposed: Riru hooks installed
04-07 08:05:23.592  1851  1851 I EdXposed: ART hooks installed
04-07 08:05:23.592  1851  1851 I EdXposed: system_property_get: dalvik.vm.dex2oat-filter -> quicken
04-07 08:05:23.592  1851  1851 I EdXposed: system_property_get: dalvik.vm.dex2oat-flags -> --inline-max-code-units=0
04-07 08:05:23.846  1851  1851 I EdXposed: using installer org.meowcat.edxposed.manager
04-07 08:05:23.846  1851  1851 I EdXposed: data path prefix: /data/user_de/0/
04-07 08:05:23.846  1851  1851 I EdXposed:   application list mode: false
04-07 08:05:23.846  1851  1851 I EdXposed:     using whitelist: false
04-07 08:05:23.846  1851  1851 I EdXposed:   dynamic modules mode: false
04-07 08:05:23.846  1851  1851 I EdXposed:   resources hook: true
04-07 08:05:23.846  1851  1851 I EdXposed:   deopt boot image: false
04-07 08:05:23.846  1851  1851 I EdXposed:   no module log: false
04-07 08:05:25.957  1851  1851 E EdXposed-Bridge: Cannot load any modules because /data/user_de/0/org.meowcat.edxposed.manager/conf/modules.list was not found
04-07 08:05:26.437  2116  2116 E EdXposed: mmap failed, errno = Permission denied
04-07 08:05:26.437  2116  2116 E EdXposed: cannot hook method
04-07 08:05:26.446  2116  2116 E EdXposed: error when hooking com.elderdrivers.riru.edxp._hooker.yahfa.StartBootstrapServicesHooker
04-07 08:05:26.446  2116  2116 E EdXposed: java.lang.RuntimeException: Failed to hook private void com.android.server.SystemServer.startBootstrapServices() with public static void com.elderdrivers.riru.edxp._hooker.yahfa.StartBootstrapServicesHooker.hook(java.lang.Object) throws java.lang.Throwable
04-07 08:05:26.446  2116  2116 E EdXposed: 	at com.elderdrivers.riru.edxp.core.yahfa.HookMain.backupAndHook(HookMain.java:136)
04-07 08:05:26.446  2116  2116 E EdXposed: 	at com.elderdrivers.riru.edxp.core.yahfa.HookMain.doHookDefault(HookMain.java:3097)
04-07 08:05:26.446  2116  2116 E EdXposed: 	at com.elderdrivers.riru.edxp.proxy.BaseRouter.startSystemServerHook(BaseRouter.java:134)
04-07 08:05:26.446  2116  2116 E EdXposed: 	at com.elderdrivers.riru.edxp._hooker.impl.SystemMain.afterHookedMethod(SystemMain.java:27)
04-07 08:05:26.446  2116  2116 E EdXposed: 	at de.robv.android.xposed.XC_MethodHook.callAfterHookedMethod(XC_MethodHook.java:68)
04-07 08:05:26.446  2116  2116 E EdXposed: 	at com.elderdrivers.riru.edxp._hooker.yahfa.SystemMainHooker.hook(SystemMainHooker.java:25)
04-07 08:05:26.446  2116  2116 E EdXposed: 	at com.android.server.SystemServer.createSystemContext(SystemServer.java:609)
04-07 08:05:26.446  2116  2116 E EdXposed: 	at com.android.server.SystemServer.run(SystemServer.java:494)
04-07 08:05:26.446  2116  2116 E EdXposed: 	at com.android.server.SystemServer.main(SystemServer.java:349)
04-07 08:05:26.446  2116  2116 E EdXposed: 	at java.lang.reflect.Method.invoke(Native Method)
04-07 08:05:26.446  2116  2116 E EdXposed: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
04-07 08:05:26.446  2116  2116 E EdXposed: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:908)
04-07 08:05:27.588  2116  2116 E EdXposed: mmap failed, errno = Permission denied
04-07 08:05:27.588  2116  2116 E EdXposed: cannot hook method
04-07 08:05:27.588  2116  2116 E EdXposed: error occur when generating dex. dexDir=null
04-07 08:05:27.588  2116  2116 E EdXposed: java.lang.RuntimeException: Failed to hook public java.lang.ClassLoader android.app.LoadedApk.getClassLoader() with public static java.lang.Object EdHooker_.hook(java.lang.Object)
04-07 08:05:27.588  2116  2116 E EdXposed: 	at com.elderdrivers.riru.edxp.core.yahfa.HookMain.backupAndHook(HookMain.java:136)
04-07 08:05:27.588  2116  2116 E EdXposed: 	at com.elderdrivers.riru.edxp.yahfa.dexmaker.DynamicBridge.hookMethod(DynamicBridge.java:9225)
04-07 08:05:27.588  2116  2116 E EdXposed: 	at com.elderdrivers.riru.edxp.yahfa.config.YahfaHookProvider.hookMethod(YahfaHookProvider.java:19)
04-07 08:05:27.588  2116  2116 E EdXposed: 	at de.robv.android.xposed.XposedBridge.hookMethodNative(XposedBridge.java:461)
04-07 08:05:27.588  2116  2116 E EdXposed: 	at de.robv.android.xposed.XposedBridge.hookMethod(XposedBridge.java:238)
04-07 08:05:27.588  2116  2116 E EdXposed: 	at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:187)
04-07 08:05:27.588  2116  2116 E EdXposed: 	at com.elderdrivers.riru.edxp._hooker.impl.LoadedApkCstr.afterHookedMethod(LoadedApkCstr.java:55)
04-07 08:05:27.588  2116  2116 E EdXposed: 	at de.robv.android.xposed.XC_MethodHook.callAfterHookedMethod(XC_MethodHook.java:68)
04-07 08:05:27.588  2116  2116 E EdXposed: 	at com.elderdrivers.riru.edxp._hooker.yahfa.LoadedApkConstructorHooker.hook(LoadedApkConstructorHooker.java:35)
04-07 08:05:27.588  2116  2116 E EdXposed: 	at android.app.ActivityThread.getPackageInfo(ActivityThread.java:2309)
04-07 08:05:27.588  2116  2116 E EdXposed: 	at android.app.ActivityThread.getPackageInfo(ActivityThread.java:2252)
04-07 08:05:27.588  2116  2116 E EdXposed: 	at android.app.ActivityThread.getPackageInfo(ActivityThread.java:2223)
04-07 08:05:27.588  2116  2116 E EdXposed: 	at android.app.ContextImpl.createPackageContextAsUser(ContextImpl.java:2183)
04-07 08:05:27.588  2116  2116 E EdXposed: 	at android.app.ContextImpl.createPackageContext(ContextImpl.java:2170)
04-07 08:05:27.588  2116  2116 E EdXposed: 	at android.content.ContextWrapper.createPackageContext(ContextWrapper.java:876)
04-07 08:05:27.588  2116  2116 E EdXposed: 	at android.app.ActivityThread.installProvider(ActivityThread.java:6942)
04-07 08:05:27.588  2116  2116 E EdXposed: 	at android.app.ActivityThread.installContentProviders(ActivityThread.java:6528)
04-07 08:05:27.588  2116  2116 E EdXposed: 	at android.app.ActivityThread.installSystemProviders(ActivityThread.java:7169)
04-07 08:05:27.588  2116  2116 E EdXposed: 	at com.android.server.am.ActivityManagerService.installSystemProviders(ActivityManagerService.java:7552)
04-07 08:05:27.588  2116  2116 E EdXposed: 	at com.android.server.SystemServer.startOtherServices(SystemServer.java:982)
04-07 08:05:27.588  2116  2116 E EdXposed: 	at com.android.server.SystemServer.run(SystemServer.java:512)
04-07 08:05:27.588  2116  2116 E EdXposed: 	at com.android.server.SystemServer.main(SystemServer.java:349)
04-07 08:05:27.588  2116  2116 E EdXposed: 	at java.lang.reflect.Method.invoke(Native Method)
04-07 08:05:27.588  2116  2116 E EdXposed: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
04-07 08:05:27.588  2116  2116 E EdXposed: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:908)
04-07 08:05:48.649  3783  3783 D EdXposedManager: ApplicationList: Force add modules to list
04-07 08:05:50.513  3783  3915 E EdXposedManager: AdvancedInstallerFragment -> http://edxp.meowcat.org/assets/version.json
04-07 08:05:51.808  3783  3783 I EdXposedManager: ModuleUtil -> updating modules.list
04-07 08:05:57.837  3783  4117 I EdXposedManager: RepoLoader -> Downloaded https://dl.xposed.info/repo/partial/18551.xml.gz with status 0 (error: null), size 66 bytes
04-07 08:05:57.840  3783  4117 I EdXposedManager: RepoLoader -> Updated repository https://dl-xda.xposed.info/repo/full.xml.gz to version 18551 (0 new / 0 removed modules)
```

**Comment by MlgmXyysd** [comment]
`mmap failed, errno = Permission denied`

这个情况是SELinux Policy未正确加载，自己走一波livepatch或者直接宽容模式

**Comment by Altonhe** [comment]
问题已解决
打开shell 输入
```
su
setenforce 0
```
之后软重启，edxp即可正常使用
