### ISSUE TITLE
[BUG] OnePlus 6T Chrome based apps crash with any module enabled.

### ISSUE THREAD

**Issue by LuisVervaet** [ElderDrivers/EdXposed#512]
**什么情况/What happened?**
When enabling any module in edXposed it causes any chrome based application to crash, this happenes in both versions 

如无法开机/模块无效等

**Xposed模块列表/Xposed Module List**

允许截图/Screenshot allowed

![Screenshot_20200414-091540](https://user-images.githubusercontent.com/39219859/79229152-8e59c800-7e30-11ea-8caf-5950e803a9f6.jpg)

**Magisk模块列表/Magisk Module List**

允许截图/Screenshot allowed
![Screenshot_20200414-091610](https://user-images.githubusercontent.com/39219859/79229184-9b76b700-7e30-11ea-95e1-c2e8437489ba.jpg)

**EdXposed及Riru版本/Versions of EdXposed and Riru**

EdXposed: 0.4.6.2

Riru: 19.8

**Comment by danielehrhardt** [comment]
Yes, same Issue here. If i try to start Google Chrome also.
Here the Logcat:
```
Failure starting process com.chrome.canary:sandboxed_process0:org.chromium.content.app.SandboxedProcessService0:15
java.lang.RuntimeException: Starting VM process through Zygote failed
	at android.os.ZygoteProcess.start(ZygoteProcess.java:340)
	at com.android.server.am.ProcessList.startProcess(ProcessList.java:1816)
	at com.android.server.am.ProcessList.lambda$startProcessLocked$0$ProcessList(ProcessList.java:1668)
	at com.android.server.am.-$$Lambda$ProcessList$vtq7LF5jIHO4t5NE03c8g7BT7Jc.run(Unknown Source:20)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.os.HandlerThread.run(HandlerThread.java:67)
	at com.android.server.ServiceThread.run(ServiceThread.java:44)
Caused by: android.os.ZygoteStartFailedEx: java.io.EOFException
	at android.os.ZygoteProcess.attemptZygoteSendArgsAndGetResult(ZygoteProcess.java:447)
	at android.os.ZygoteProcess.zygoteSendArgsAndGetResult(ZygoteProcess.java:419)
	at android.os.ZygoteProcess.startViaZygote(ZygoteProcess.java:635)
	at android.os.ZygoteProcess.start(ZygoteProcess.java:333)
	... 8 more
Caused by: java.io.EOFException
	at java.io.DataInputStream.readFully(DataInputStream.java:200)
	at java.io.DataInputStream.readInt(DataInputStream.java:389)
	at android.os.ZygoteProcess.attemptZygoteSendArgsAndGetResult(ZygoteProcess.java:435)
	... 11 more
```

**Comment by MlgmXyysd** [comment]
Chrome and xposed are old bugs in conflict. Add chromium related apps to the blacklist

**Comment by LuisVervaet** [comment]
> Chrome and xposed are old bugs in conflict. Add chromium related apps to the blacklist

How would I do this?

**Comment by LuisVervaet** [comment]
nvm I got it working, Go to settings > application mode > reboot > go to applications and blacklist google and google chrome

**Comment by ButterRhopa** [comment]
Same crash log on Lineageos 17.1. Add Google,chrome and Android WebView to the Edxposed Blacklist and reboot. Works well.

**Comment by ruinetto** [comment]
I had been trying to figure out how to get around this for a long time. Very annoying to discover the solution to this problem. I got it working with these instructions... Thank you so much!
