### ISSUE TITLE
[BUG] 云闪付等梆梆加固的应用在该框架下载不能运行

### ISSUE THREAD

**Issue by ohyeah521** [ElderDrivers/EdXposed#558]
云闪付  等梆梆加固的应用在该框架下载不能运行，

05-25 17:15:20.492 11654 11654 E com.unionpay: Not starting debugger since process cannot load the jdwp agent.
05-25 17:15:20.494  1470  1585 I ActivityManager: Start proc 11654:com.unionpay/u0a181 for activity com.unionpay/.activity.UPActivityWelcome
05-25 17:15:20.515 11654 11654 V Riru    : hook removed
05-25 17:15:20.515 11654 11654 V Riru    : edxp: forkAndSpecializePost
05-25 17:15:20.575 11654 11675 I com.unionpay: The ClassLoaderContext is a special shared library.
05-25 17:15:20.581   874  1323 D AudioPolicyService: setRecordSilenced() uid 10181 on silenced 0
05-25 17:15:20.588 11654 11654 D SandHook: method <public java.lang.ClassLoader android.app.LoadedApk.getClassLoader()> hook <replacement> success!
05-25 17:15:20.594 11654 11654 I com.unionpay: The ClassLoaderContext is a special shared library.
05-25 17:15:20.662 11654 11654 I Perf    : Connecting to perf service.
05-25 17:15:20.709  1470  3236 D EmbryoManager: prepare com.unionpay user 0
05-25 17:15:20.710   736   736 I Zygote  : Process 11654 exited due to signal (9)
05-25 17:15:20.710  1470  3236 I ActivityManager: Process com.unionpay (pid 11654) has died: fore TOP

**Comment by Howard20181** [comment]
云闪付请使用Google Play版本
同样的，中国移动APP也无法运行，暂时无解

**Comment by ohyeah521** [comment]
> 云闪付请使用Google Play版本
> 同样的，中国移动APP也无法运行，暂时无解

换了GooglePlay版本确实可以了

**Comment by addhaloka** [comment]
fuck梆梆加固就能运行了

**Comment by ohyeah521** [comment]
> fuck梆梆加固就能运行了

求fuck姿势

**Comment by Howard20181** [comment]
增加中国移动闪退日志
> java.lang.RuntimeException: Unable to get provider cn.migudm.live.core.utils.MGSDKInitializer: java.lang.IllegalArgumentException: Unknown URL content://com.greenpoint.android.mc10086.activity.Live.AmberInitializer/insert
 at android.app.ActivityThread.installProvider(ActivityThread.java:7248)
 at android.app.ActivityThread.installContentProviders(ActivityThread.java:6726)
 at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6621)
 at android.app.ActivityThread.access$1400(ActivityThread.java:229)
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1903)
 at android.os.Handler.dispatchMessage(Handler.java:107)
 at android.os.Looper.loop(Looper.java:238)
 at android.app.ActivityThread.main(ActivityThread.java:7619)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
Caused by: java.lang.IllegalArgumentException: Unknown URL content://com.greenpoint.android.mc10086.activity.Live.AmberInitializer/insert
 at android.content.ContentResolver.insert(ContentResolver.java:1840)
 at cn.migudm.live.core.utils.MGSDKInitializer.a(Unknown Source:112)
 at cn.migudm.live.core.utils.MGSDKInitializer.onCreate(Unknown Source:88)
 at android.content.ContentProvider.attachInfo(ContentProvider.java:2127)
 at android.content.ContentProvider.attachInfo(ContentProvider.java:2096)
 at android.app.ActivityThread.installProvider(ActivityThread.java:7243)
 ... 10 more
