### ISSUE TITLE
[BUG]三星s8安卓8.0-riru23之后的版本卡开机

### ISSUE THREAD

**Issue by fyant** [ElderDrivers/EdXposed#735]
Android version: 8.0.0
Android sdk: 26
Android build: R16NW
Fingerprint: samsung/dreamqltezc/dreamqltechn:8.0.0/R16NW/G9500ZCU2CRE1:user/release-keys
ROM build description: dreamqltezc-user 8.0.0 R16NW G9500ZCU2CRE1 release-keys
Architecture: arm64-v8a
Device: dreamqltechn
Manufacturer: samsung
Brand: samsung

**什么情况/What happened?**

(1).需要riru23之后的版本均卡开机,禁用所有模块测试,日志为4613y版
(2).riru23-4569y版部分模块无效QQ净化/网易云音乐插件2.8.2/flipster等,4586y版也是无效的,不知是不是全局模块问题后续版本卡开机
(3).刷完框架卸载包之后MXplayer图标消失,软件存在但是其他软件和目录都看不到,覆盖安装也不行,把riru和框架全部卸载图标还是消失,刷了4569Y版图标又出来了

**Xposed模块列表/Xposed Module List**

(1).禁用所有模块
(2).QQ净化/网易云音乐插件2.8.2/flipster
(3).刷完卸载包禁掉所有模块mx图标消失

**Magisk模块列表/Magisk Module List**

(1).riru23/log Catcher/4613y版
(2).riru23/log Catcher/4569y版
(3).禁用所有模块

**EdXposed及Riru版本/Version of EdXposed and Riru**

EdXposed: (1).4613y版
		  (2).4569y版
		  (3).装了框架刷卸载包

Riru:23

**相关日志/Related Logs**

[4613y版卡开机logCatcher-boot](https://github.com/fyant/log/blob/main/log/4613y%E7%89%88boot.log)
[4569y版模块无效log](https://github.com/fyant/log/blob/main/log/4569y%E7%89%88.txt)
[模块无效/图标消失软件](https://wwa.lanzous.com/b03bdx7pi)

为了帮助我们定位问题，请使用debug版EdXposed模块抓日志。
Please capture log with debug version, otherwise it won't help us locating the issue.

**Comment by kotori2** [comment]
> 4613y版卡开机logCatcher-boot

EdXposed not even loaded. Riru loaded but didn't load EdXposed. The crash was caused by system. 
```
05-10 06:24:24.322   673   673 E System  : Unable to open boot classpath entry: /system/framework/qcom.fmradio.jar
05-10 06:24:24.323   673   673 E System  : java.io.FileNotFoundException: File doesn't exist: /system/framework/qcom.fmradio.jar
05-10 06:24:24.323   673   673 E System  : 	at java.util.zip.ZipFile.<init>(ZipFile.java:212)
05-10 06:24:24.323   673   673 E System  : 	at java.util.zip.ZipFile.<init>(ZipFile.java:149)
05-10 06:24:24.323   673   673 E System  : 	at java.util.jar.JarFile.<init>(JarFile.java:160)
05-10 06:24:24.323   673   673 E System  : 	at java.util.jar.JarFile.<init>(JarFile.java:97)
05-10 06:24:24.323   673   673 E System  : 	at libcore.io.ClassPathURLStreamHandler.<init>(ClassPathURLStreamHandler.java:47)
05-10 06:24:24.323   673   673 E System  : 	at java.lang.VMClassLoader.createBootClassPathUrlHandlers(VMClassLoader.java:49)
05-10 06:24:24.323   673   673 E System  : 	at java.lang.VMClassLoader.<clinit>(VMClassLoader.java:32)
05-10 06:24:24.323   673   673 E System  : 	at java.lang.BootClassLoader.findResource(ClassLoader.java:1360)
05-10 06:24:24.323   673   673 E System  : 	at java.lang.BootClassLoader.getResource(ClassLoader.java:1406)
05-10 06:24:24.323   673   673 E System  : 	at java.lang.ClassLoader.getResourceAsStream(ClassLoader.java:987)
05-10 06:24:24.323   673   673 E System  : 	at java.lang.Class.getResourceAsStream(Class.java:2211)
05-10 06:24:24.323   673   673 E System  : 	at java.util.logging.LogManager.readConfiguration(LogManager.java:1297)
05-10 06:24:24.323   673   673 E System  : 	at java.util.logging.LogManager$3.run(LogManager.java:390)
05-10 06:24:24.323   673   673 E System  : 	at java.util.logging.LogManager$3.run(LogManager.java:388)
05-10 06:24:24.323   673   673 E System  : 	at java.security.AccessController.doPrivileged(AccessController.java:67)
05-10 06:24:24.323   673   673 E System  : 	at java.util.logging.LogManager.readPrimordialConfiguration(LogManager.java:387)
05-10 06:24:24.323   673   673 E System  : 	at java.util.logging.LogManager.-wrap5(Unknown Source:0)
05-10 06:24:24.323   673   673 E System  : 	at java.util.logging.LogManager$2.run(LogManager.java:336)
05-10 06:24:24.323   673   673 E System  : 	at java.security.AccessController.doPrivileged(AccessController.java:41)
05-10 06:24:24.323   673   673 E System  : 	at java.util.logging.LogManager.ensureLogManagerInitialized(LogManager.java:329)
05-10 06:24:24.323   673   673 E System  : 	at java.util.logging.LogManager.getLogManager(LogManager.java:369)
05-10 06:24:24.323   673   673 E System  : 	at java.util.logging.Logger.demandLogger(Logger.java:449)
05-10 06:24:24.323   673   673 E System  : 	at java.util.logging.Logger.getLogger(Logger.java:505)
05-10 06:24:24.323   673   673 E System  : 	at android.icu.util.TimeZone.<clinit>(TimeZone.java:95)
05-10 06:24:24.323   673   673 E System  : 	at java.util.TimeZone.setDefault(TimeZone.java:741)
05-10 06:24:24.323   673   673 E System  : 	at com.android.internal.os.RuntimeInit.commonInit(RuntimeInit.java:156)
05-10 06:24:24.323   673   673 E System  : 	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:280)
05-10 06:24:24.331   673   673 D AndroidRuntime: Calling main entry com.android.commands.pm.Pm
```

> 4569y版模块无效log

The module is working. 
```
12-17 06:19:09.979  9473  9473 I EdXposed-Bridge: music163plus:Loaded music163.
12-17 06:19:10.003  9473  9473 I EdXposed-Bridge: music163plus:versioncode:121
12-17 06:19:10.175  9473  9473 I EdXposed-Bridge: music163plus:已开启禁用更新com.netease.cloudmusic当前版本号121版本名:5.4.0
12-17 06:19:10.186  9473  9473 I EdXposed-Bridge: music163plus:已开启禁用更新com.netease.cloudmusic当前版本号121版本名:5.4.0
```

Also we don't accept logs except debug build.
