### ISSUE TITLE
[BUG] "Could not hook Xposed Installer" in log

### ISSUE THREAD

**Issue by rhjdvsgsgks** [ElderDrivers/EdXposed#788]
**什么情况/What happened?**

just some error logs

**Xposed模块列表/Xposed Module List**

none

**Magisk模块列表/Magisk Module List**

Riru
Riru - EdXposed

**版本信息/Versions**

Android: 9

Magisk: 21.2

Riru: 23.1

EdXposed: 4661 sandhook

**相关日志/Related Logs**

```
01-05 15:52:53.925  4748  4748 I EdXposed: Loading modules for org.meowcat.edxposed.manager
01-05 15:52:54.044  4748  4748 E EdXposed: Could not hook Xposed Installer
01-05 15:52:54.044  4748  4748 E EdXposed: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Class.getName()' on a null object reference
01-05 15:52:54.044  4748  4748 E EdXposed: 	at de.robv.android.xposed.XposedHelpers.findMethodExact(XposedHelpers.java:328)
01-05 15:52:54.044  4748  4748 E EdXposed: 	at com.elderdrivers.riru.edxp.hooker.XposedInstallerHooker.hookXposedInstaller(XposedInstallerHooker.java:98)
01-05 15:52:54.044  4748  4748 E EdXposed: 	at com.elderdrivers.riru.edxp._hooker.impl.LoadedApkGetCL.afterHookedMethod(LoadedApkGetCL.java:64)
01-05 15:52:54.044  4748  4748 E EdXposed: 	at de.robv.android.xposed.XC_MethodHook.callAfterHookedMethod(XC_MethodHook.java:68)
01-05 15:52:54.044  4748  4748 E EdXposed: 	at com.swift.sandhook.xposedcompat.hookstub.HookStubManager.hookBridge(HookStubManager.java:321)
01-05 15:52:54.044  4748  4748 E EdXposed: 	at com.swift.sandhook.xposedcompat.hookstub.MethodHookerStubs64.stub_hook_0(MethodHookerStubs64.java:78)
01-05 15:52:54.044  4748  4748 E EdXposed: 	at android.app.LoadedApk.getResources(LoadedApk.java:1037)
01-05 15:52:54.044  4748  4748 E EdXposed: 	at android.app.ContextImpl.createAppContext(ContextImpl.java:2345)
01-05 15:52:54.044  4748  4748 E EdXposed: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5773)
01-05 15:52:54.044  4748  4748 E EdXposed: 	at java.lang.reflect.Method.invoke(Native Method)
01-05 15:52:54.044  4748  4748 E EdXposed: 	at com.swift.sandhook.SandHook.callOriginMethod(SandHook.java:183)
01-05 15:52:54.044  4748  4748 E EdXposed: 	at com.swift.sandhook.SandHook.callOriginMethod(SandHook.java:161)
01-05 15:52:54.044  4748  4748 E EdXposed: 	at com.swift.sandhook.xposedcompat.hookstub.HookStubManager.hookBridge(HookStubManager.java:306)
01-05 15:52:54.044  4748  4748 E EdXposed: 	at com.swift.sandhook.xposedcompat.hookstub.MethodHookerStubs64.stub_hook_0(MethodHookerStubs64.java:198)
01-05 15:52:54.044  4748  4748 E EdXposed: 	at android.app.ActivityThread.access$1100(ActivityThread.java:205)
01-05 15:52:54.044  4748  4748 E EdXposed: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656)
01-05 15:52:54.044  4748  4748 E EdXposed: 	at android.os.Handler.dispatchMessage(Handler.java:106)
01-05 15:52:54.044  4748  4748 E EdXposed: 	at android.os.Looper.loop(Looper.java:280)
01-05 15:52:54.044  4748  4748 E EdXposed: 	at android.app.ActivityThread.main(ActivityThread.java:6706)
01-05 15:52:54.044  4748  4748 E EdXposed: 	at java.lang.reflect.Method.invoke(Native Method)
01-05 15:52:54.044  4748  4748 E EdXposed: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
01-05 15:52:54.044  4748  4748 E EdXposed: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by yujincheng08** [comment]
@kotori2 `org.meowcat.edxposed.manager.MainActivity` does not exist.

**Comment by kotori2** [comment]
ikr
