### ISSUE TITLE
[BUG] hook了所有类的同名方法

### ISSUE THREAD

**Issue by CwithW** [ElderDrivers/EdXposed#81]
**什么情况/What happened?**
hook了Application.class的attach(Context)方法,但是在其他地方也会调用并且param.thisObject不是Application

**Xposed模块列表/Xposed Module List**
自制模块
<details>
``
public class mainxposed implements IXposedHookLoadPackage {

    @Override
    public void handleLoadPackage(final XC_LoadPackage.LoadPackageParam lpparam) throws Throwable {
        if(BuildConfig.APPLICATION_ID.equals(lpparam.packageName)){
            XposedHelpers.findAndHookMethod("pub.chara.cwui.cwtools.utils.XposedUtil",lpparam.classLoader,"getBuildInt",XC_MethodReplacement.returnConstant(BuildConfig.VERSION_CODE));
            return;
        }
        XSharedPreferences preferences = new XSharedPreferences(BuildConfig.APPLICATION_ID,lpparam.packageName);
        if(!preferences.getBoolean("isExist", false)){
            preferences = new XSharedPreferences(BuildConfig.APPLICATION_ID,"global");
            if(!preferences.getBoolean("isExist",false)) return;
        }
        for (CharaModule module : Constant.modules) {
            module.attach(lpparam,preferences);
        }
        final XSharedPreferences finalPreferences = preferences;
        XposedHelpers.findAndHookMethod(Application.class, "attach", Context.class, new XC_MethodHook() {
            @Override
            protected void afterHookedMethod(MethodHookParam param) throws Throwable {
                Context context = (Context) param.args[0]; 
                Application thisApplication = (Application) param.thisObject; //line 37
                for (CharaModule module : Constant.modules) {
                    module.attachFromApplication(lpparam,thisApplication,context,finalPreferences);
                }
            }
        });
    }
}
``
</details>
**Magisk模块列表/Magisk Module List**

![image](https://user-images.githubusercontent.com/31593731/52895124-cd6e9800-31f0-11e9-97ba-60ae9df89ca4.png)

**EdXposed及Riru版本/Versions of EdXposed and Riru**

EdXposed:v0.2.9.8_beta1

Riru:v10

**相关Logcat/Logcat**
java.lang.ClassCastException: com.termux.app.TermuxActivity cannot be cast to android.app.Application
      at pub.chara.cwui.cwtools.xposed.mainxposed$1.afterHookedMethod(mainxposed.java:37)
      at de.robv.android.xposed.XC_MethodHook.callAfterHookedMethod(Unknown Source:0)
      at EdHooker1.hook(Unknown Source:142)
      at android.view.ContextThemeWrapper.attachBaseContext(Unknown Source:0)
      at android.app.Activity.attachBaseContext(Unknown Source:0)
      at android.app.Activity.attach(Unknown Source:8)
      at android.app.ActivityThread.performLaunchActivity(Unknown Source:290)
      at android.app.ActivityThread.handleLaunchActivity(Unknown Source:36)
      at android.app.servertransaction.LaunchActivityItem.execute(Unknown Source:57)
      at android.app.servertransaction.TransactionExecutor.executeCallbacks(Unknown Source:99)
      at android.app.servertransaction.TransactionExecutor.execute(Unknown Source:34)
      at android.app.ActivityThread$H.handleMessage(Unknown Source:36)
      at android.os.Handler.dispatchMessage(Unknown Source:21)
      at android.os.Looper.loop(Unknown Source:208)
      at android.app.ActivityThread.main(Unknown Source:107)
      at java.lang.reflect.Method.invoke(Native Method)
      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
      at com.android.internal.os.ZygoteInit.main(Unknown Source:274)
java.lang.ClassCastException: com.termux.app.TermuxService cannot be cast to android.app.Application
      at pub.chara.cwui.cwtools.xposed.mainxposed$1.afterHookedMethod(mainxposed.java:37)
      at de.robv.android.xposed.XC_MethodHook.callAfterHookedMethod(Unknown Source:0)
      at EdHooker1.hook(Unknown Source:142)
      at android.app.Service.attach(Unknown Source:0)
      at android.app.ActivityThread.handleCreateService(Unknown Source:70)
      at android.app.ActivityThread.access$1400(Unknown Source:0)
      at android.app.ActivityThread$H.handleMess

**Comment by solohsu** [comment]
Application的attach由于方法体太短默认情况下会被内联，导致没法hook到，至于强转失败是因为之前为音量增强模块加了一个临时解决方案，具体可以参考[这次的提交](https://github.com/ElderDrivers/EdXposed/commit/045104d1bf58e8a30eab1f3cf36ccc4037d469aa)

**Comment by solohsu** [comment]
Fixed with a80eae7190d85515dbab3694b8ba8fe4ba638059
