### ISSUE TITLE
[BUG] crash when open turemoney wallet app(5.18.0).(android.content.res.Resources$NotFoundException: Drawable th.co.truemoney.wallet:drawable/logo_splash with resource ID #0x7f0803ae)

### ISSUE THREAD

**Issue by tangs** [ElderDrivers/EdXposed#813]
**什么情况/What happened?**
crash when open turemoney wallet app(5.18.0).

**Xposed模块列表/Xposed Module List**

**Magisk模块列表/Magisk Module List**
Riru(Riru - Core) v21.3
Riru-EdXposed v0.4.6.2

**版本信息/Versions**

Android:
10

Magisk:
20.4(20400)

Riru:
v21.3

EdXposed:
v0.4.6.2

**相关日志/Related Logs**

        2021-01-27 11:53:10.486 1948-2123/? W/WindowManager: Token{62db651 ActivityRecord{165ef78 u0 th.co.truemoney.wallet/.activity.LoadingScreenActivity t1367}} failed creating starting window
    android.content.res.Resources$NotFoundException: Drawable th.co.truemoney.wallet:drawable/logo_splash with resource ID #0x7f0803ae
    Caused by: android.content.res.Resources$NotFoundException: File res/drawable/logo_splash.xml from drawable resource ID #0x7f0803ae
        at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:876)
        at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:659)
        at android.content.res.Resources.getDrawableForDensity(Resources.java:906)
        at android.content.res.XResources.getDrawableForDensity(XResources.java:871)
        at android.content.res.Resources.getDrawable(Resources.java:845)
        at android.content.res.XResources.getDrawable(XResources.java:793)
        at android.content.Context.getDrawable(Context.java:687)
        at com.android.server.policy.PhoneWindowManager.addSplashScreen(PhoneWindowManager.java:2386)
        at com.android.server.wm.SplashScreenStartingData.createStartingSurface(SplashScreenStartingData.java:56)
        at com.android.server.wm.AppWindowToken$1.run(AppWindowToken.java:2227)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.os.HandlerThread.run(HandlerThread.java:67)
        at com.android.server.ServiceThread.run(ServiceThread.java:44)
     Caused by: android.content.res.Resources$NotFoundException: Resource ID #0x7f08048b
        at android.content.res.ResourcesImpl.getValueForDensity(ResourcesImpl.java:246)
        at android.content.res.Resources.getValueForDensity(Resources.java:1369)
        at android.graphics.drawable.BitmapDrawable.updateStateFromTypedArray(BitmapDrawable.java:819)
        at android.graphics.drawable.BitmapDrawable.inflate(BitmapDrawable.java:775)
        at android.graphics.drawable.DrawableInflater.inflateFromXmlForDensity(DrawableInflater.java:144)
        at android.graphics.drawable.Drawable.createFromXmlInnerForDensity(Drawable.java:1402)
        at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:1391)
        at android.graphics.drawable.LayerDrawable.inflateLayers(LayerDrawable.java:284)
        at android.graphics.drawable.LayerDrawable.inflate(LayerDrawable.java:199)
        at android.graphics.drawable.DrawableInflater.inflateFromXmlForDensity(DrawableInflater.java:144)
        at android.graphics.drawable.Drawable.createFromXmlInnerForDensity(Drawable.java:1402)
        at android.graphics.drawable.Drawable.createFromXmlForDensity(Drawable.java:1361)
        at android.content.res.ResourcesImpl.loadXmlDrawable(ResourcesImpl.java:939)
        at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:862)
        at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:659) 
        at android.content.res.Resources.getDrawableForDensity(Resources.java:906) 
        at android.content.res.XResources.getDrawableForDensity(XResources.java:871) 
        at android.content.res.Resources.getDrawable(Resources.java:845) 
        at android.content.res.XResources.getDrawable(XResources.java:793) 
        at android.content.Context.getDrawable(Context.java:687) 
        at com.android.server.policy.PhoneWindowManager.addSplashScreen(PhoneWindowManager.java:2386) 
        at com.android.server.wm.SplashScreenStartingData.createStartingSurface(SplashScreenStartingData.java:56) 
        at com.android.server.wm.AppWindowToken$1.run(AppWindowToken.java:2227) 
        at android.os.Handler.handleCallback(Handler.java:883) 
        at android.os.Handler.dispatchMessage(Handler.java:100) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.os.HandlerThread.run(HandlerThread.java:67) 
        at com.android.server.ServiceThread.run(ServiceThread.java:44) 

021-01-27 11:53:10.722 13243-13243/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: th.co.truemoney.wallet, PID: 13243
    java.lang.RuntimeException: Unable to start activity ComponentInfo{th.co.truemoney.wallet/th.co.truemoney.wallet.activity.LoadingScreenActivity}: android.content.res.Resources$NotFoundException: Drawable th.co.truemoney.wallet:drawable/logo_splash with resource ID #0x7f0803ae
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3270)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: android.content.res.Resources$NotFoundException: Drawable th.co.truemoney.wallet:drawable/logo_splash with resource ID #0x7f0803ae
     Caused by: android.content.res.Resources$NotFoundException: File res/drawable/logo_splash.xml from drawable resource ID #0x7f0803ae
        at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:876)
        at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:659)
        at android.content.res.Resources.loadDrawable(Resources.java:916)
        at android.content.res.TypedArray.getDrawableForDensity(TypedArray.java:1006)
        at android.content.res.TypedArray.getDrawable(TypedArray.java:981)
        at android.content.res.XResources$XTypedArray.getDrawable(XResources.java:1371)
        at com.android.internal.policy.PhoneWindow.generateLayout(PhoneWindow.java:2549)
        at com.android.internal.policy.PhoneWindow.installDecor(PhoneWindow.java:2694)
        at com.android.internal.policy.PhoneWindow.getDecorView(PhoneWindow.java:2094)
        at androidx.appcompat.app.AppCompatDelegateImpl.ʅ(:575)
        at androidx.appcompat.app.AppCompatDelegateImpl.ſ(:518)
        at androidx.appcompat.app.AppCompatDelegateImpl.ɩ(:466)
        at androidx.appcompat.app.AppCompatActivity.setContentView(:140)
        at th.co.truemoney.wallet.activity.LoadingScreenActivity.onCreate(Unknown Source:1100)
        at android.app.Activity.performCreate(Activity.java:7825)
        at android.app.Activity.performCreate(Activity.java:7814)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1306)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: android.content.res.Resources$NotFoundException: Resource ID #0x7f08048b
        at android.content.res.ResourcesImpl.getValueForDensity(ResourcesImpl.java:246)
        at android.content.res.Resources.getValueForDensity(Resources.java:1369)
        at android.graphics.drawable.BitmapDrawable.updateStateFromTypedArray(BitmapDrawable.java:819)
        at android.graphics.drawable.BitmapDrawable.inflate(BitmapDrawable.java:775)

**Comment by MlgmXyysd** [comment]
EdXposed:
v0.4.6.2
