### ISSUE TITLE
[BUG] Android 12 crashes and restarts abnormally

### ISSUE THREAD

**Issue by huyuxin95** [ElderDrivers/EdXposed#899]
```
java.lang.IllegalArgumentException: android: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
at android.app.PendingIntent.checkFlags(PendingIntent.java:375)
at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:645)
at android.app.PendingIntent.getBroadcast(PendingIntent.java:632)
at com.jozein.xedgepro.xposed.p$s1.c(Unknown Source:84)
at com.jozein.xedgepro.xposed.p$s1.b(Unknown Source:9)
at com.jozein.xedgepro.xposed.p.G3(Unknown Source:39)
at com.jozein.xedgepro.xposed.p.B0(Unknown Source:0)
at com.jozein.xedgepro.xposed.p$y0.b(Unknown Source:12)
at com.jozein.xedgepro.c.e0.d(Unknown Source:11)
at com.jozein.xedgepro.c.e0$e$a.onTorchModeChanged(Unknown Source:48)
at android.hardware.camera2.CameraManager$CameraManagerGlobal.lambda$postSingleTorchUpdate$0(CameraManager.java:1887)
at android.hardware.camera2.CameraManager$CameraManagerGlobal$$ExternalSyntheticLambda2.run(Unknown Source:6)
at android.os.Handler.handleCallback(Handler.java:938)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:210)
at android.os.Looper.loop(Looper.java:299)
at android.os.HandlerThread.run(HandlerThread.java:67)
at com.android.server.ServiceThread.run(ServiceThread.java:46)
at com.android.server.UiThread.run(UiThread.java:45)
```

Please adapt Android 12 according to the developer documentation as soon as possible. Thank you

https://developer.android.google.cn/about/versions/12/behavior-changes-12?hl=zh-cn#pending-intent-mutability

**Comment by MlgmXyysd** [comment]
Thank you for contacting us. We are planning the adaptation of Android Snow Cone. Please wait patiently.

**Comment by C0rn3j** [comment]
Any news regarding Android 12 (and 13) support? I see the Readme still claims up to Android 11 only

**Comment by huyuxin95** [comment]
这是来自邮箱的自动回复邮件。
 
您好，我已收到你的发送的邮件，我将会尽快给您回复。

**Comment by ChRriiZz** [comment]
> ```
> java.lang.IllegalArgumentException: android: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
> Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
> at android.app.PendingIntent.checkFlags(PendingIntent.java:375)
> at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:645)
> at android.app.PendingIntent.getBroadcast(PendingIntent.java:632)
> at com.jozein.xedgepro.xposed.p$s1.c(Unknown Source:84)
> at com.jozein.xedgepro.xposed.p$s1.b(Unknown Source:9)
> at com.jozein.xedgepro.xposed.p.G3(Unknown Source:39)
> at com.jozein.xedgepro.xposed.p.B0(Unknown Source:0)
> at com.jozein.xedgepro.xposed.p$y0.b(Unknown Source:12)
> at com.jozein.xedgepro.c.e0.d(Unknown Source:11)
> at com.jozein.xedgepro.c.e0$e$a.onTorchModeChanged(Unknown Source:48)
> at android.hardware.camera2.CameraManager$CameraManagerGlobal.lambda$postSingleTorchUpdate$0(CameraManager.java:1887)
> at android.hardware.camera2.CameraManager$CameraManagerGlobal$$ExternalSyntheticLambda2.run(Unknown Source:6)
> at android.os.Handler.handleCallback(Handler.java:938)
> at android.os.Handler.dispatchMessage(Handler.java:99)
> at android.os.Looper.loopOnce(Looper.java:210)
> at android.os.Looper.loop(Looper.java:299)
> at android.os.HandlerThread.run(HandlerThread.java:67)
> at com.android.server.ServiceThread.run(ServiceThread.java:46)
> at com.android.server.UiThread.run(UiThread.java:45)
> ```
> 
> Please adapt Android 12 according to the developer documentation as soon as possible. Thank you
> 
> https://developer.android.google.cn/about/versions/12/behavior-changes-12?hl=zh-cn#pending-intent-mutability
