### ISSUE TITLE
[BUG] Android S java crash causes phone to restart

### ISSUE THREAD

**Issue by zhang8615050** [ElderDrivers/EdXposed#917]
```
02-23 12:04:24.261  1000  2352  2587 E AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: android.ui
02-23 12:04:24.261  1000  2352  2587 E AndroidRuntime: java.lang.IllegalArgumentException: android: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
02-23 12:04:24.261  1000  2352  2587 E AndroidRuntime: Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
02-23 12:04:24.261  1000  2352  2587 E AndroidRuntime: 	at android.app.PendingIntent.checkFlags(PendingIntent.java:375)
02-23 12:04:24.261  1000  2352  2587 E AndroidRuntime: 	at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:645)
02-23 12:04:24.261  1000  2352  2587 E AndroidRuntime: 	at android.app.PendingIntent.getBroadcast(PendingIntent.java:632)
02-23 12:04:24.261  1000  2352  2587 E AndroidRuntime: 	at com.jozein.xedgepro.xposed.p$v1.c(Unknown Source:81)
02-23 12:04:24.261  1000  2352  2587 E AndroidRuntime: 	at com.jozein.xedgepro.xposed.p$v1.b(Unknown Source:8)
02-23 12:04:24.261  1000  2352  2587 E AndroidRuntime: 	at com.jozein.xedgepro.xposed.p.J3(Unknown Source:39)
02-23 12:04:24.261  1000  2352  2587 E AndroidRuntime: 	at com.jozein.xedgepro.xposed.p.A0(Unknown Source:0)
02-23 12:04:24.261  1000  2352  2587 E AndroidRuntime: 	at com.jozein.xedgepro.xposed.p$b1.b(Unknown Source:12)
02-23 12:04:24.261  1000  2352  2587 E AndroidRuntime: 	at com.jozein.xedgepro.c.f0.d(Unknown Source:11)
02-23 12:04:24.261  1000  2352  2587 E AndroidRuntime: 	at com.jozein.xedgepro.c.f0$e$a.onTorchModeChanged(Unknown Source:48)
02-23 12:04:24.261  1000  2352  2587 E AndroidRuntime: 	at android.hardware.camera2.CameraManager$CameraManagerGlobal.lambda$postSingleTorchUpdate$0(CameraManager.java:1893)
02-23 12:04:24.261  1000  2352  2587 E AndroidRuntime: 	at android.hardware.camera2.CameraManager$CameraManagerGlobal$$ExternalSyntheticLambda2.run(Unknown Source:6)
02-23 12:04:24.261  1000  2352  2587 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
02-23 12:04:24.261  1000  2352  2587 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
02-23 12:04:24.261  1000  2352  2587 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:210)
02-23 12:04:24.261  1000  2352  2587 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:299)
02-23 12:04:24.261  1000  2352  2587 E AndroidRuntime: 	at android.os.HandlerThread.run(HandlerThread.java:67)
02-23 12:04:24.261  1000  2352  2587 E AndroidRuntime: 	at com.android.server.ServiceThread.run(ServiceThread.java:46)
02-23 12:04:24.261  1000  2352  2587 E AndroidRuntime: 	at com.android.server.UiThread.run(UiThread.java:45)
```
This problem has occurred frequently recently.
Please adapt to Android S as soon as possible according to the Google developer documentation. thanks
https://developer.android.google.cn/about/versions/12/behavior-changes-12?hl=zh-cn#pending-intent-mutability

**Comment by wj2008** [comment]
这还没适配S吧
