### ISSUE TITLE
[BUG] Switch the flashlight on and off, the phone will automatically restart

### ISSUE THREAD

**Issue by ylc0710** [ElderDrivers/EdXposed#923]
**什么情况/What happened?**
06-29 15:24:23.572  1000  1723  1775 E AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: android.ui
06-29 15:24:23.572  1000  1723  1775 E AndroidRuntime: java.lang.IllegalArgumentException: android: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
06-29 15:24:23.572  1000  1723  1775 E AndroidRuntime: Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
06-29 15:24:23.572  1000  1723  1775 E AndroidRuntime: 	at android.app.PendingIntent.checkFlags(PendingIntent.java:375)
06-29 15:24:23.572  1000  1723  1775 E AndroidRuntime: 	at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:645)
06-29 15:24:23.572  1000  1723  1775 E AndroidRuntime: 	at android.app.PendingIntent.getBroadcast(PendingIntent.java:632)
06-29 15:24:23.572  1000  1723  1775 E AndroidRuntime: 	at com.jozein.xedgepro.xposed.p$o1.a(Unknown Source:76)
06-29 15:24:23.572  1000  1723  1775 E AndroidRuntime: 	at com.jozein.xedgepro.xposed.p$o1.a(Unknown Source:0)
06-29 15:24:23.572  1000  1723  1775 E AndroidRuntime: 	at com.jozein.xedgepro.xposed.p.a(Unknown Source:48)
06-29 15:24:23.572  1000  1723  1775 E AndroidRuntime: 	at com.jozein.xedgepro.xposed.p.a(Unknown Source:0)
06-29 15:24:23.572  1000  1723  1775 E AndroidRuntime: 	at com.jozein.xedgepro.xposed.p$v0.b(Unknown Source:12)
06-29 15:24:23.572  1000  1723  1775 E AndroidRuntime: 	at com.jozein.xedgepro.c.c0.a(Unknown Source:11)
06-29 15:24:23.572  1000  1723  1775 E AndroidRuntime: 	at com.jozein.xedgepro.c.c0$e$a.onTorchModeChanged(Unknown Source:48)
06-29 15:24:23.572  1000  1723  1775 E AndroidRuntime: 	at android.hardware.camera2.CameraManager$CameraManagerGlobal.lambda$postSingleTorchUpdate$0(CameraManager.java:1900)
06-29 15:24:23.572  1000  1723  1775 E AndroidRuntime: 	at android.hardware.camera2.CameraManager$CameraManagerGlobal$$ExternalSyntheticLambda2.run(Unknown Source:6)
06-29 15:24:23.572  1000  1723  1775 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
06-29 15:24:23.572  1000  1723  1775 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
06-29 15:24:23.572  1000  1723  1775 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:210)
06-29 15:24:23.572  1000  1723  1775 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:299)
06-29 15:24:23.572  1000  1723  1775 E AndroidRuntime: 	at android.os.HandlerThread.run(HandlerThread.java:67)
06-29 15:24:23.572  1000  1723  1775 E AndroidRuntime: 	at com.android.server.ServiceThread.run(ServiceThread.java:46)
06-29 15:24:23.572  1000  1723  1775 E AndroidRuntime: 	at com.android.server.UiThread.run(UiThread.java:45)

**Xposed模块列表/Xposed Module List**

**Magisk模块列表/Magisk Module List**

**版本信息/Versions**

Android: Android S

Magisk:

Riru:

EdXposed:

**相关日志/Related Logs**

**Comment by vqsld** [comment]
EdXp doesnt support Android 12...
